// Code generated by tddsplit. DO NOT EDIT.

package lawgate

import (
	core "github.com/aphrollo/aphrollo-tools/internal/tdd/core"
)

const Allow = core.Allow

type gateEntry = core.GateEntry

func GateLogPath() string { return core.GateLogPath() }

func parseGateLine(p0 string) (gateEntry, bool) { return core.ParseGateLine(p0) }
