// Code generated by tddsplit. DO NOT EDIT.

package lawgate

import (
	core "github.com/aphrollo/aphrollo-tools/internal/tdd/core"
	time "time"
)

const Block = core.Block

const Warn = core.Warn

type Decision = core.Decision

type GateResult = core.GateResult

func AppendGateLog(p0 string, p1 string, p2 string, p3 string, p4 time.Duration) {
	core.AppendGateLog(p0, p1, p2, p3, p4)
}

func LogToken(p0 string) string { return core.LogToken(p0) }

func StateDir() string { return core.StateDir() }

func addGateWorktree(p0 string) (string, error) { return core.AddGateWorktree(p0) }

func readStagedTree(p0 string, p1 string) (string, error) { return core.ReadStagedTree(p0, p1) }

func removeGateWorktree(p0 string, p1 string) { core.RemoveGateWorktree(p0, p1) }
