// Code generated by tddsplit. DO NOT EDIT.

package lawgate

import (
	suite "github.com/aphrollo/aphrollo-tools/internal/tdd/suite"
)

const outcomeCheckError = suite.OutcomeCheckError

type stageOutcome = suite.StageOutcome

func applyEdit(p0 string, p1 string, p2 string, p3 bool) string {
	return suite.ApplyEdit(p0, p1, p2, p3)
}

func cargoAphrolloPackages(p0 string, p1 string) []string { return suite.CargoAphrolloPackages(p0, p1) }

func fixtureLawFromPath(p0 string) (string, bool) { return suite.FixtureLawFromPath(p0) }

func gitRead(p0 string, p1 ...string) (string, error) { return suite.GitRead(p0, p1...) }

func laneBaseSHA(p0 string) string { return suite.LaneBaseSHA(p0) }

func verdictFor(p0 string, p1 string, p2 string, p3 string, p4 stageOutcome) GateResult {
	return suite.VerdictFor(p0, p1, p2, p3, p4)
}
