// Code generated by tddsplit. DO NOT EDIT.

package lawgate

import (
	gitx "github.com/aphrollo/aphrollo-tools/internal/tdd/gitx"
)

const stagedDiffFilter = gitx.StagedDiffFilter

func RepoRoot(p0 string) string { return gitx.RepoRoot(p0) }

func TrunkBranch(p0 string) string { return gitx.TrunkBranch(p0) }

func cleanGitEnv() []string { return gitx.CleanGitEnv() }

func git(p0 string, p1 ...string) (string, error) { return gitx.Git(p0, p1...) }

func gitBinary() string { return gitx.GitBinary() }

func lastNonEmptyLine(p0 string) string { return gitx.LastNonEmptyLine(p0) }

func mergeInProgressRef(p0 string) string { return gitx.MergeInProgressRef(p0) }

func stagedFiles(p0 string) []string { return gitx.StagedFiles(p0) }
