// Code generated by tddsplit. DO NOT EDIT.

package lawgate

import (
	core "github.com/aphrollo/aphrollo-tools/internal/tdd/core"
)

const Allow = core.Allow

type Event = core.Event

type gateEntry = core.GateEntry

func ReadEvents(p0 string) []Event { return core.ReadEvents(p0) }

func parseGateLine(p0 string) (gateEntry, bool) { return core.ParseGateLine(p0) }
