// Code generated by tddsplit. DO NOT EDIT.

package lawgate

import (
	ratchet "github.com/aphrollo/aphrollo-tools/internal/ratchet"
)

func BaselineStage(p0 string, p1 string) GateResult { return baselineStage(p0, p1) }

func ExistingAncestorDir(p0 string) string { return existingAncestorDir(p0) }

func GitBlob(p0 string, p1 string) (string, bool) { return gitBlob(p0, p1) }

func LaneChangedPaths(p0 string) []string { return laneChangedPaths(p0) }

func RatchetCheckFn(p0 ratchet.Options) (ratchet.Result, error) { return ratchetCheckFn(p0) }

func RatchetFixtureStage(p0 string, p1 string) GateResult { return ratchetFixtureStage(p0, p1) }

func RatchetHintLine(p0 string) string { return ratchetHintLine(p0) }

func RatchetStage(p0 string, p1 string) GateResult { return ratchetStage(p0, p1) }

func RepoRootNear(p0 string) string { return repoRootNear(p0) }

func StagedTouchesLaws(p0 string) bool { return stagedTouchesLaws(p0) }

func TrackedFiles(p0 string) []string { return trackedFiles(p0) }

func TrackedIgnoredFiles(p0 string) []string { return trackedIgnoredFiles(p0) }
