// Code generated by tddsplit. DO NOT EDIT.

package lock

import (
	core "github.com/aphrollo/aphrollo-tools/internal/tdd/core"
)

func SetPidRunningForTest(p0 func(pid int) bool) func() { return core.SetPidRunningForTest(p0) }
