// Code generated by tddsplit. DO NOT EDIT.

package lock

import (
	core "github.com/aphrollo/aphrollo-tools/internal/tdd/core"
	time "time"
)

const sharedLockFileMode = core.SharedLockFileMode

type Runner = core.Runner

type gateEntry = core.GateEntry

func AppendGateLog(p0 string, p1 string, p2 string, p3 string, p4 time.Duration) {
	core.AppendGateLog(p0, p1, p2, p3, p4)
}

func SessionID() string { return core.SessionID() }

func StateDir() string { return core.StateDir() }

func TryAcquireFileLock(p0 string) (func(), bool) { return core.TryAcquireFileLock(p0) }

func ensureSharedSubdir(p0 string) error { return core.EnsureSharedSubdir(p0) }

func gateLogStageToken(p0 string) string { return core.GateLogStageToken(p0) }

func parseGateLine(p0 string) (gateEntry, bool) { return core.ParseGateLine(p0) }

func pidRunningFn(p0 int) bool { return core.PidRunningFn(p0) }

func plural(p0 int) string { return core.Plural(p0) }

func primaryCheckoutRoot(p0 string) string { return core.PrimaryCheckoutRoot(p0) }

func sameProject(p0 string, p1 string) bool { return core.SameProject(p0, p1) }
