// Code generated by tddsplit. DO NOT EDIT.

//go:build !windows

package lock

func GlobalSlotOwnerPath(p0 int) string { return globalSlotOwnerPath(p0) }

func QueueWaiterPath(p0 string, p1 int) string { return queueWaiterPath(p0, p1) }

func QueueWaitersDir() string { return queueWaitersDir() }
