// Code generated by tddsplit. DO NOT EDIT.

package lock

import (
	time "time"
)

const BuildLockPollInterval = buildLockPollInterval

const BuildSlotsEnv = buildSlotsEnv

const MaxAncestryDepth = maxAncestryDepth

const SuiteFloorMargin = suiteFloorMargin

type ProcSample = procSample

type SuiteFloor = suiteFloor

var FutureMtimeChecked = &futureMtimeChecked

var LintLockDeadline = lintLockDeadline

func AcquireBuildSlot(p0 string, p1 time.Duration, p2 string, p3 string) (BuildSlot, func(), bool) {
	return acquireBuildSlot(p0, p1, p2, p3)
}

func AcquireGlobalSlot(p0 time.Duration, p1 string, p2 string) (BuildSlot, func(), bool) {
	return acquireGlobalSlot(p0, p1, p2)
}

func BuildSlotCount() int { return buildSlotCount() }

func BuildSlotHolderDescription(p0 string) string { return buildSlotHolderDescription(p0) }

func BuildToolPids() ([]int, bool) { return buildToolPids() }

func CappedFloor(p0 time.Duration, p1 time.Duration) time.Duration { return cappedFloor(p0, p1) }

func CargoConfigJobs(p0 string) (int, bool) { return cargoConfigJobs(p0) }

func CargoTomlHasWorkspaceTable(p0 string) bool { return cargoTomlHasWorkspaceTable(p0) }

func CargoWorkspaceRoot(p0 string) string { return cargoWorkspaceRoot(p0) }

func CsvPids(p0 string) []int { return csvPids(p0) }

func DescribeOwner(p0 BuildLockOwner) string { return describeOwner(p0) }

func EffectiveBuildLockPath() string { return effectiveBuildLockPath() }

func EnsureSharedDir(p0 string) error { return ensureSharedDir(p0) }

func ForeignLoadReport(p0 int) string { return foreignLoadReport(p0) }

func FreeSpaceGB(p0 string) (int, bool) { return freeSpaceGB(p0) }

func GlobalCapacityHolderDescription() string { return globalCapacityHolderDescription() }

func GoRaceLockKey() string { return goRaceLockKey() }

func GoTmpDir(p0 string) string { return goTmpDir(p0) }

func GoTmpEnv(p0 string) []string { return goTmpEnv(p0) }

func InvalidateFutureStampedArtifacts(p0 string) { invalidateFutureStampedArtifacts(p0) }

func IsSettledVerdict(p0 string) bool { return isSettledVerdict(p0) }

func LitterDirsFor(p0 string, p1 bool, p2 string) []string { return litterDirsFor(p0, p1, p2) }

func LockDir() string { return lockDir() }

func LockLitterDirs() []string { return lockLitterDirs() }

func LockWaitLogAfter() time.Duration { return lockWaitLogAfter() }

func MachineAvailGB() int { return machineAvailGB() }

func MachineRAMGB() int { return machineRAMGB() }

func MutantsBudgetMemoryGB(p0 int, p1 int) (int, string) { return mutantsBudgetMemoryGB(p0, p1) }

func MutantsMemoryTerm(p0 int, p1 int, p2 int, p3 string) (int, string, string, bool) {
	return mutantsMemoryTerm(p0, p1, p2, p3)
}

func PostEditLockWait() time.Duration { return postEditLockWait() }

func PrecommitLockWait() time.Duration { return precommitLockWait() }

func ProcessExePath(p0 int) (string, bool) { return processExePath(p0) }

func ReadBuildLockOwnerAt(p0 string) (BuildLockOwner, bool) { return readBuildLockOwnerAt(p0) }

func RecordedSuiteFloor(p0 string, p1 string) suiteFloor { return recordedSuiteFloor(p0, p1) }

func RemoveBuildLockOwnerAt(p0 string) { removeBuildLockOwnerAt(p0) }

func ResolveTargetDir(p0 func(string) string, p1 string) string { return resolveTargetDir(p0, p1) }

func RunnerTargetDir(p0 Runner, p1 string) string { return runnerTargetDir(p0, p1) }

func SetBuildJobs(p0 int) func() { return setBuildJobs(p0) }

func SetBuildLockPathOverride(p0 string) func() { return setBuildLockPathOverride(p0) }

func SharedLockCandidates() []string { return sharedLockCandidates() }

func SharedTargetLockPath(p0 string) string { return sharedTargetLockPath(p0) }

func SlotJobs(p0 int, p1 int) int { return slotJobs(p0, p1) }

func StoreFutureMtimeMarker(p0 string, p1 time.Time) { storeFutureMtimeMarker(p0, p1) }

func SuiteFloorFrom(p0 []float64) suiteFloor { return suiteFloorFrom(p0) }

func TargetLockPath(p0 string) string { return targetLockPath(p0) }

func TotalCargoJobs() int { return totalCargoJobs() }

func WriteBuildLockOwnerAt(p0 string, p1 string, p2 string) { writeBuildLockOwnerAt(p0, p1, p2) }

func WriteSharedRecord(p0 string, p1 []byte) error { return writeSharedRecord(p0, p1) }
