package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// writeTree writes files (slash paths relative to dir) under dir.
func writeTree(t *testing.T, dir string, files map[string]string) {
	t.Helper()
	for name, body := range files {
		p := filepath.Join(dir, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
}

// aliasFixture is one unsplit package p: a.go holds a constant, a seam var a
// test in its own file reassigns, a read-only var, a type with an unexported
// field and a variadic func; b.go uses all of them, and reads the field.
var aliasFixture = map[string]string{
	"go.mod": "module example.com/fx\n\ngo 1.26\n",
	"p/a.go": `package p

import "strings"

const limit = 3

var hook = func(n int) bool { return n > limit }

var names = []string{"a"}

type thing struct{ name string }

func helper(s string, rest ...string) (string, error) { return s + strings.Join(rest, ""), nil }
`,
	"p/a_test.go": `package p

import "testing"

func TestHook_StubIsSeen(t *testing.T) {
	old := hook
	hook = func(int) bool { return true }
	defer func() { hook = old }()
	if !hook(0) {
		t.Fatal("stub not seen")
	}
}
`,
	"p/b.go": `package p

func Use() bool {
	t := thing{name: "x"}
	_, _ = helper(t.name)
	_ = names
	return hook(limit)
}
`,
}

const aliasManifest = `root p
[packages]
low L0 p/low
p   L1 p
[files]
a.go      low
a_test.go low
b.go      p
`

func analyzeFixture(t *testing.T, files map[string]string, manifest, levels string) *Analysis {
	t.Helper()
	repo := t.TempDir()
	writeTree(t, repo, files)
	m, err := ParseManifest(strings.NewReader(manifest))
	if err != nil {
		t.Fatal(err)
	}
	lv, err := ParseLevels(levels)
	if err != nil {
		t.Fatal(err)
	}
	a, err := Analyze(repo, m, lv)
	if err != nil {
		t.Fatal(err)
	}
	return a
}

func TestAnalyze_ConsumerAliasesFollowTheKindRules(t *testing.T) {
	a := analyzeFixture(t, aliasFixture, aliasManifest, "L0")
	deps := string(a.Generated["p/api_low.go"])
	for _, want := range []string{
		"// Code generated by tddsplit. DO NOT EDIT.",
		"const limit = low.Limit",
		"func hook(p0 int) bool { return low.Hook(p0) }",
		"var names = low.Names",
		"type thing = low.Thing",
		"func helper(p0 string, p1 ...string) (string, error) { return low.Helper(p0, p1...) }",
	} {
		if !strings.Contains(deps, want) {
			t.Errorf("p/api_low.go lacks %q:\n%s", want, deps)
		}
	}
	if strings.Contains(deps, "var hook") {
		t.Errorf("the seam hook is copied as a var, so a stub assigned in low never reaches p:\n%s", deps)
	}
}

func TestAnalyze_ExportFileCallsThroughToTheSeam(t *testing.T) {
	a := analyzeFixture(t, aliasFixture, aliasManifest, "L0")
	exp := string(a.Generated["p/low/export.go"])
	for _, want := range []string{
		"package low",
		"const Limit = limit",
		"func Hook(p0 int) bool { return hook(p0) }",
		"var Names = names",
		"type Thing = thing",
		"func Helper(p0 string, p1 ...string) (string, error) { return helper(p0, p1...) }",
	} {
		if !strings.Contains(exp, want) {
			t.Errorf("p/low/export.go lacks %q:\n%s", want, exp)
		}
	}
}

func TestAnalyze_ReportsAnUnexportedFieldReadAcrossTheBoundary(t *testing.T) {
	a := analyzeFixture(t, aliasFixture, aliasManifest, "L0")
	found := false
	for _, r := range a.Reports {
		if strings.Contains(r, "field name") && strings.Contains(r, "b.go") {
			found = true
		}
	}
	if !found {
		t.Errorf("no report names field name read from b.go; reports:\n%s", strings.Join(a.Reports, "\n"))
	}
}

func TestAnalyze_ReportsAReferenceToAHigherLevel(t *testing.T) {
	files := map[string]string{
		"go.mod": "module example.com/fx\n\ngo 1.26\n",
		"p/a.go": "package p\n\nfunc low() int { return high() }\n",
		"p/b.go": "package p\n\nfunc high() int { return 1 }\n\n// Top keeps low reachable.\nfunc Top() int { return low() }\n",
	}
	manifest := "root p\n[packages]\nlow L0 p/low\np L1 p\n[files]\na.go low\nb.go p\n"
	a := analyzeFixture(t, files, manifest, "L0")
	found := false
	for _, r := range a.Reports {
		if strings.Contains(r, "high") && strings.Contains(r, "a.go") {
			found = true
		}
	}
	if !found {
		t.Errorf("no report names the upward reference to high from a.go; reports:\n%s", strings.Join(a.Reports, "\n"))
	}
}

func TestAnalyze_ExportNameTakenFallsBackToAnXPrefix(t *testing.T) {
	files := map[string]string{
		"go.mod": "module example.com/fx\n\ngo 1.26\n",
		"p/a.go": "package p\n\nfunc helper() int { return 1 }\n\n// Helper is a different function that already owns the exported name.\nfunc Helper() int { return 2 }\n",
		"p/b.go": "package p\n\n// Use reaches across the split.\nfunc Use() int { return helper() }\n",
	}
	manifest := "root p\n[packages]\nlow L0 p/low\np L1 p\n[files]\na.go low\nb.go p\n"
	a := analyzeFixture(t, files, manifest, "L0")
	if deps, want := string(a.Generated["p/api_low.go"]), "func helper() int { return low.Xhelper() }"; !strings.Contains(deps, want) {
		t.Errorf("p/api_low.go lacks %q:\n%s", want, deps)
	}
	if exp, want := string(a.Generated["p/low/export.go"]), "func Xhelper() int { return helper() }"; !strings.Contains(exp, want) {
		t.Errorf("p/low/export.go lacks %q:\n%s", want, exp)
	}
}

func TestAnalyze_RelocationOfAPlatformPairChecksEachHalfOnItsOwnPlatform(t *testing.T) {
	files := map[string]string{
		"go.mod":         "module example.com/fx\n\ngo 1.26\n",
		"p/x_windows.go": "package p\n\nfunc f() int { return 1 }\n",
		"p/x_other.go":   "//go:build !windows\n\npackage p\n\nfunc f() int { return 2 }\n",
		"p/y.go":         "package p\n\n// Use calls f.\nfunc Use() int { return f() }\n",
	}
	manifest := "root p\n[packages]\np L0 p\n[files]\nx_windows.go p\nx_other.go p\ny.go p\n" +
		"[relocate]\nf x_windows.go xw.go\nf x_other.go xo.go\n"
	a := analyzeFixture(t, files, manifest, "L0")
	var pending, wrong []string
	for _, r := range a.Reports {
		if strings.HasPrefix(r, "pending relocation") {
			pending = append(pending, r)
		}
		if strings.Contains(r, "neither") {
			wrong = append(wrong, r)
		}
	}
	if len(pending) != 2 || len(wrong) != 0 {
		t.Errorf("want both halves pending and no misplaced report; got pending=%q misplaced=%q", pending, wrong)
	}
}

// A test left in p that assigns a seam var moving to low would assign the
// generated call-through func instead, which does not compile. The report
// must name the assignment so the carve-out adds a setter first.
func TestAnalyze_ReportsATestAssigningASeamThatMovesBelowIt(t *testing.T) {
	files := map[string]string{
		"go.mod":      "module example.com/fx\n\ngo 1.26\n",
		"p/a.go":      "package p\n\nvar probe = func(n int) bool { return n > 0 }\n",
		"p/b.go":      "package p\n\n// Use reads the seam.\nfunc Use() bool { return probe(1) }\n",
		"p/b_test.go": "package p\n\nimport \"testing\"\n\nfunc TestUse_Stubbed(t *testing.T) {\n\tprev := probe\n\tprobe = func(int) bool { return false }\n\tdefer func() { probe = prev }()\n\tif Use() {\n\t\tt.Fatal(\"stub not seen\")\n\t}\n}\n",
	}
	manifest := "root p\n[packages]\nlow L0 p/low\np L1 p\n[files]\na.go low\nb.go p\nb_test.go p\n"
	a := analyzeFixture(t, files, manifest, "L0")
	var hits []string
	for _, r := range a.Reports {
		if strings.Contains(r, "assigns seam var probe") {
			hits = append(hits, r)
		}
	}
	if len(hits) != 1 || !strings.Contains(hits[0], "p/b_test.go:7") || !strings.Contains(hits[0], "p/b_test.go:8") {
		t.Errorf("want one finding naming both assignments at p/b_test.go:7 and :8; reports:\n%s", strings.Join(a.Reports, "\n"))
	}
}

// go vet's composites check refuses an unkeyed literal of a struct type from
// another package. A type whose declaration moves turns every unkeyed literal
// of it left behind into such a literal, so each site is reported, elided
// element types included; a keyed literal and one in the type's own package
// are not.
func TestAnalyze_ReportsEachUnkeyedLiteralOfAStructThatMovesAway(t *testing.T) {
	files := map[string]string{
		"go.mod": "module example.com/fx\n\ngo 1.26\n",
		"p/a.go": "package p\n\ntype pair struct{ K, V string }\n\nvar own = pair{\"a\", \"b\"}\n",
		"p/b.go": "package p\n\n// Use builds pairs.\nfunc Use() []pair {\n\tx := pair{\"k\", \"v\"}\n\ty := pair{K: \"k\"}\n\treturn []pair{x, y, {\"e\", \"f\"}, own}\n}\n",
	}
	manifest := "root p\n[packages]\nlow L0 p/low\np L1 p\n[files]\na.go low\nb.go p\n"
	a := analyzeFixture(t, files, manifest, "L0")
	var hits []string
	for _, r := range a.Reports {
		if strings.Contains(r, "unkeyed") {
			hits = append(hits, r)
		}
	}
	want := []string{"p/b.go:5:7", "p/b.go:7:22"}
	if len(hits) != len(want) {
		t.Fatalf("want %d unkeyed findings, got %d:\n%s", len(want), len(hits), strings.Join(a.Reports, "\n"))
	}
	for i, w := range want {
		if !strings.Contains(hits[i], w) || !strings.Contains(hits[i], "pair") {
			t.Errorf("finding %d = %q, want it to name pair at %s", i, hits[i], w)
		}
	}
}

// A var holding a lock (a sync.Map here) aliased by value is a copy: vet's
// copylocks refuses it, and the consumer would read a second, empty map. It
// is aliased by pointer instead, and reported so a reader knows why.
func TestAnalyze_AliasesALockBearingVarByPointer(t *testing.T) {
	files := map[string]string{
		"go.mod": "module example.com/fx\n\ngo 1.26\n",
		"p/a.go": "package p\n\nimport \"sync\"\n\nvar seen sync.Map\n\n// Guard is already exported.\nvar Guard sync.Mutex\n\nfunc mark(k string) { seen.Store(k, true) }\n",
		"p/b.go": "package p\n\n// Use marks a key through low and reads it back from p.\nfunc Use() bool {\n\tGuard.Lock()\n\tdefer Guard.Unlock()\n\tmark(\"k\")\n\t_, ok := seen.Load(\"k\")\n\treturn ok\n}\n",
	}
	manifest := "root p\n[packages]\nlow L0 p/low\np L1 p\n[files]\na.go low\nb.go p\n"
	a := analyzeFixture(t, files, manifest, "L0")
	if exp, want := string(a.Generated["p/low/export.go"]), "var Seen = &seen"; !strings.Contains(exp, want) {
		t.Errorf("p/low/export.go lacks %q:\n%s", want, exp)
	}
	for _, want := range []string{"var seen = low.Seen", "var Guard = &low.Guard"} {
		if api := string(a.Generated["p/api_low.go"]); !strings.Contains(api, want) {
			t.Errorf("p/api_low.go lacks %q:\n%s", want, api)
		}
	}
	found := false
	for _, r := range a.Reports {
		if strings.Contains(r, "seen") && strings.Contains(r, "pointer") {
			found = true
		}
	}
	if !found {
		t.Errorf("no report says seen is aliased by pointer; reports:\n%s", strings.Join(a.Reports, "\n"))
	}
}
