package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/ast"
	"go/build"
	"go/importer"
	"go/parser"
	"go/token"
	"go/types"
	"io"
	"io/fs"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"sort"
	"strings"
)

// genHeader opens every file the generator writes. A file starting with it
// is regenerated on every run and never analysed as source.
const genHeader = "// Code generated by tddsplit. DO NOT EDIT."

// srcFile is one file of the unsplit package, wherever it lives today.
type srcFile struct {
	Key    string // manifest key: path relative to the package dir it lives in
	Path   string // repo-relative, slash-separated
	Dir    string // repo-relative package dir it lives in today
	Target string // manifest package
}

func (f srcFile) isGo() bool   { return strings.HasSuffix(f.Key, ".go") && !strings.Contains(f.Key, "/") }
func (f srcFile) isTest() bool { return strings.HasSuffix(f.Key, "_test.go") }

// listSources walks the root dir and every non-prep package dir under it.
// Each file's key is relative to the deepest package dir holding it.
// Generated files are skipped; unmapped files come back with Target "".
func listSources(repo string, m *Manifest) ([]srcFile, error) {
	var dirs []string
	for _, p := range m.Packages {
		if p.Level != LevelPrep {
			dirs = append(dirs, p.Dir)
		}
	}
	sort.Slice(dirs, func(i, j int) bool { return len(dirs[i]) > len(dirs[j]) })
	var prepDirs []string
	for _, p := range m.Packages {
		if p.Level == LevelPrep {
			prepDirs = append(prepDirs, p.Dir)
		}
	}
	var out []srcFile
	rootAbs := filepath.Join(repo, filepath.FromSlash(m.Root))
	err := filepath.WalkDir(rootAbs, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, _ := filepath.Rel(repo, p)
		rel = filepath.ToSlash(rel)
		if d.IsDir() {
			for _, pd := range prepDirs {
				if rel == pd {
					return filepath.SkipDir
				}
			}
			return nil
		}
		if generated(p) {
			return nil
		}
		for _, dir := range dirs {
			if strings.HasPrefix(rel, dir+"/") {
				key := strings.TrimPrefix(rel, dir+"/")
				target, _ := m.PackageOf(key)
				out = append(out, srcFile{Key: key, Path: rel, Dir: dir, Target: target})
				return nil
			}
		}
		return fmt.Errorf("%s lies under no declared package dir", rel)
	})
	sort.Slice(out, func(i, j int) bool { return out[i].Path < out[j].Path })
	return out, err
}

func generated(p string) bool {
	if !strings.HasSuffix(p, ".go") {
		return false
	}
	f, err := os.Open(p)
	if err != nil {
		return false
	}
	defer f.Close()
	line, _ := bufio.NewReader(f).ReadString('\n')
	return strings.TrimSpace(line) == genHeader
}

// checked is the unsplit package reassembled from wherever its files live
// today and type-checked for one GOOS.
type checked struct {
	GOOS   string
	Fset   *token.FileSet
	Pkg    *types.Package
	Info   *types.Info
	Files  []*ast.File
	ByFile map[*ast.File]srcFile
	ByName map[string]srcFile // token file name -> source
}

// typecheck parses every Go file matching goos, renames its package clause
// back to the root package name in memory, and type-checks the lot as one
// package. External test files (package x_test) are returned by path only.
func typecheck(repo, rootName, importPath string, srcs []srcFile, goos string) (*checked, []string, error) {
	ctx := build.Default
	ctx.GOOS, ctx.GOARCH, ctx.CgoEnabled = goos, "amd64", false
	c := &checked{GOOS: goos, Fset: token.NewFileSet(), ByFile: map[*ast.File]srcFile{}, ByName: map[string]srcFile{}}
	var external []string
	imports := map[string]bool{}
	for _, s := range srcs {
		if !s.isGo() {
			continue
		}
		abs := filepath.Join(repo, filepath.FromSlash(s.Path))
		ok, err := ctx.MatchFile(filepath.Dir(abs), filepath.Base(abs))
		if err != nil {
			return nil, nil, err
		}
		if !ok {
			continue
		}
		f, err := parser.ParseFile(c.Fset, abs, nil, parser.ParseComments)
		if err != nil {
			return nil, nil, err
		}
		if strings.HasSuffix(f.Name.Name, "_test") {
			external = append(external, s.Path)
			continue
		}
		f.Name.Name = rootName
		for _, im := range f.Imports {
			imports[strings.Trim(im.Path.Value, `"`)] = true
		}
		c.Files = append(c.Files, f)
		c.ByFile[f] = s
		c.ByName[abs] = s
	}
	exports, err := exportData(repo, goos, imports)
	if err != nil {
		return nil, nil, err
	}
	lookup := func(p string) (io.ReadCloser, error) {
		file, ok := exports[p]
		if !ok {
			return nil, fmt.Errorf("no export data for %s", p)
		}
		return os.Open(file)
	}
	var typeErrs []string
	conf := types.Config{
		Importer: importer.ForCompiler(c.Fset, "gc", lookup),
		Error:    func(err error) { typeErrs = append(typeErrs, err.Error()) },
	}
	c.Info = &types.Info{Uses: map[*ast.Ident]types.Object{}, Defs: map[*ast.Ident]types.Object{}, Types: map[ast.Expr]types.TypeAndValue{}}
	c.Pkg, _ = conf.Check(importPath, c.Fset, c.Files, c.Info)
	if len(typeErrs) > 0 {
		return nil, nil, fmt.Errorf("GOOS=%s: the reassembled package does not type-check, so no analysis of it can be trusted:\n%s", goos, strings.Join(typeErrs, "\n"))
	}
	return c, external, nil
}

// exportData asks `go list` for the compiled export data of every import and
// its dependencies, built for goos.
func exportData(repo, goos string, imports map[string]bool) (map[string]string, error) {
	args := []string{"list", "-e", "-export", "-deps", "-f", "{{if .Export}}{{.ImportPath}}\t{{.Export}}{{end}}"}
	var paths []string
	for p := range imports {
		if p != "unsafe" && p != "C" {
			paths = append(paths, p)
		}
	}
	sort.Strings(paths)
	out := map[string]string{}
	if len(paths) == 0 {
		return out, nil
	}
	cmd := exec.Command("go", append(args, paths...)...)
	cmd.Dir = repo
	cmd.Env = append(os.Environ(), "GOOS="+goos, "GOARCH=amd64", "CGO_ENABLED=0")
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	stdout, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("go list -export (GOOS=%s): %v\n%s", goos, err, stderr.String())
	}
	for _, line := range strings.Split(string(stdout), "\n") {
		if ip, file, ok := strings.Cut(line, "\t"); ok {
			out[ip] = file
		}
	}
	return out, nil
}

// srcOf maps a position back to the source file that declares it.
func (c *checked) srcOf(pos token.Pos) (srcFile, bool) {
	tf := c.Fset.File(pos)
	if tf == nil {
		return srcFile{}, false
	}
	s, ok := c.ByName[tf.Name()]
	return s, ok
}

// modulePath reads the module path from repo/go.mod.
func modulePath(repo string) (string, error) {
	data, err := os.ReadFile(filepath.Join(repo, "go.mod"))
	if err != nil {
		return "", err
	}
	for _, line := range strings.Split(string(data), "\n") {
		if rest, ok := strings.CutPrefix(strings.TrimSpace(line), "module "); ok {
			return strings.TrimSpace(rest), nil
		}
	}
	return "", fmt.Errorf("go.mod: no module line")
}

// importPathOf joins the module path and a repo-relative dir.
func importPathOf(module, dir string) string { return path.Join(module, dir) }
