// Code generated by tddsplit. DO NOT EDIT.

package merge

import (
	core "github.com/aphrollo/aphrollo-tools/internal/tdd/core"
	time "time"
)

const premergeDisplayName = core.PremergeDisplayName

type GateResult = core.GateResult

type Runner = core.Runner

type gateEntry = core.GateEntry

func AppendGateLog(p0 string, p1 string, p2 string, p3 string, p4 time.Duration) {
	core.AppendGateLog(p0, p1, p2, p3, p4)
}

func LogToken(p0 string) string { return core.LogToken(p0) }

func StateDir() string { return core.StateDir() }

func aphrolloTomlFlag(p0 string, p1 string) bool { return core.AphrolloTomlFlag(p0, p1) }

func parseGateLine(p0 string) (gateEntry, bool) { return core.ParseGateLine(p0) }

func primaryCheckoutRoot(p0 string) string { return core.PrimaryCheckoutRoot(p0) }

func sameProject(p0 string, p1 string) bool { return core.SameProject(p0, p1) }

func tomlBoolSetIn(p0 string, p1 string, p2 string) (bool, bool) {
	return core.TomlBoolSetIn(p0, p1, p2)
}
