// Code generated by tddsplit. DO NOT EDIT.

package merge

import (
	escape "github.com/aphrollo/aphrollo-tools/internal/tdd/escape"
	io "io"
)

const gateNotesRef = escape.GateNotesRef

type EscapeRecord = escape.EscapeRecord

func EscapeLogPath() string { return escape.EscapeLogPath() }

func NoteMergeGateEscape(p0 string, p1 string, p2 io.Writer) { escape.NoteMergeGateEscape(p0, p1, p2) }

func PostCommit(p0 string) { escape.PostCommit(p0) }

func StampGreenSuiteIfProven(p0 string) { escape.StampGreenSuiteIfProven(p0) }

func gateGreenNote(p0 string) string { return escape.GateGreenNote(p0) }

func stampGreenSuite(p0 string) { escape.StampGreenSuite(p0) }
