// Code generated by tddsplit. DO NOT EDIT.

package merge

import (
	core "github.com/aphrollo/aphrollo-tools/internal/tdd/core"
)

type Event = core.Event

func AppendEvent(p0 Event) { core.AppendEvent(p0) }

func GateLogPath() string { return core.GateLogPath() }

func parseGateLine(p0 string) (gateEntry, bool) { return core.ParseGateLine(p0) }
