// Code generated by tddsplit. DO NOT EDIT.

package merge

import (
	precommit "github.com/aphrollo/aphrollo-tools/internal/tdd/precommit"
)

const golangciLint = precommit.GolangciLint

func Precommit(p0 string, p1 SuiteRunner) GateResult { return precommit.Precommit(p0, p1) }
