// Code generated by tddsplit. DO NOT EDIT.

package merge

import (
	lock "github.com/aphrollo/aphrollo-tools/internal/tdd/lock"
)

func cargoWorkspaceRoot(p0 string) string { return lock.CargoWorkspaceRoot(p0) }
