// Code generated by tddsplit. DO NOT EDIT.

package merge

import (
	suite "github.com/aphrollo/aphrollo-tools/internal/tdd/suite"
)

type SuiteRunner = suite.SuiteRunner

type mutantsConfigTable = suite.MutantsConfigTable

func cargoAphrolloFlag(p0 string, p1 string) bool { return suite.CargoAphrolloFlag(p0, p1) }

func cargoAphrolloPackages(p0 string, p1 string) []string { return suite.CargoAphrolloPackages(p0, p1) }

func indexTree(p0 string) string { return suite.IndexTree(p0) }

func mechCacheCovers(p0 string, p1 string, p2 Runner) bool { return suite.MechCacheCovers(p0, p1, p2) }

func mutantsConfigTables(p0 string) []mutantsConfigTable { return suite.MutantsConfigTables(p0) }

func worktreeStateHash(p0 string) string { return suite.WorktreeStateHash(p0) }
