// Code generated by tddsplit. DO NOT EDIT.

package merge

import (
	suite "github.com/aphrollo/aphrollo-tools/internal/tdd/suite"
)

type SuiteRunner = suite.SuiteRunner

type mechCacheFile = suite.MechCacheFile

type mutantsConfigTable = suite.MutantsConfigTable

func cargoAphrolloFlag(p0 string, p1 string) bool { return suite.CargoAphrolloFlag(p0, p1) }

func cargoAphrolloPackages(p0 string, p1 string) []string { return suite.CargoAphrolloPackages(p0, p1) }

func indexTree(p0 string) string { return suite.IndexTree(p0) }

func loadMechCache(p0 string) *mechCacheFile { return suite.LoadMechCache(p0) }

func mechCachePath() string { return suite.MechCachePath() }

func mechKeyPrefix(p0 string, p1 string) string { return suite.MechKeyPrefix(p0, p1) }

func mutantsConfigTables(p0 string) []mutantsConfigTable { return suite.MutantsConfigTables(p0) }

func worktreeStateHash(p0 string) string { return suite.WorktreeStateHash(p0) }
