// Code generated by tddsplit. DO NOT EDIT.

package merge

import (
	precommit "github.com/aphrollo/aphrollo-tools/internal/tdd/precommit"
)

type rootGroup = precommit.RootGroup

func Mechanical(p0 string, p1 SuiteRunner) GateResult { return precommit.Mechanical(p0, p1) }

func stagedRootGroups(p0 string) []rootGroup { return precommit.StagedRootGroups(p0) }
