// Code generated by tddsplit. DO NOT EDIT.

package merge

import (
	context "context"
	mutation "github.com/aphrollo/aphrollo-tools/internal/tdd/mutation"
	io "io"
)

type MutantOutcome = mutation.MutantOutcome

func SetFreeSpaceForTest(p0 int, p1 bool) func() { return mutation.SetFreeSpaceForTest(p0, p1) }

func SetMutantsExecForTest(p0 func(ctx context.Context, dir string, env []string, argv []string, log io.Writer) (int, error)) func() {
	return mutation.SetMutantsExecForTest(p0)
}

func cargoMutantsOutcomesPath(p0 string) string { return mutation.CargoMutantsOutcomesPath(p0) }

func mutantLineOf(p0 string, p1 int, p2 int, p3 string) string {
	return mutation.MutantLineOf(p0, p1, p2, p3)
}

func setMutantsJobsForTest(p0 int, p1 string) func() { return mutation.SetMutantsJobsForTest(p0, p1) }

func setMutantsListCountForTest(p0 int, p1 bool) func() {
	return mutation.SetMutantsListCountForTest(p0, p1)
}
