// Code generated by tddsplit. DO NOT EDIT.

package merge

import (
	mutation "github.com/aphrollo/aphrollo-tools/internal/tdd/mutation"
)

type MutantsConfig = mutation.MutantsConfig

func ReadMutantsConfig(p0 string) (MutantsConfig, error) { return mutation.ReadMutantsConfig(p0) }

func measureTempDir(p0 string) string { return mutation.MeasureTempDir(p0) }
