// Code generated by tddsplit. DO NOT EDIT.

package merge

import (
	postedit "github.com/aphrollo/aphrollo-tools/internal/tdd/postedit"
	syscall "syscall"
)

func detachedAttrs() *syscall.SysProcAttr { return postedit.DetachedAttrs() }
