// Code generated by tddsplit. DO NOT EDIT.

package merge

import (
	escape "github.com/aphrollo/aphrollo-tools/internal/tdd/escape"
)

func commitCarriesGreenGate(p0 string, p1 string) bool { return escape.CommitCarriesGreenGate(p0, p1) }

func greenSuiteStampFile(p0 string) string { return escape.GreenSuiteStampFile(p0) }
