// Code generated by tddsplit. DO NOT EDIT.

package merge

import (
	context "context"
	tddtest "github.com/aphrollo/aphrollo-tools/internal/tdd/internal/tddtest"
	testing "testing"
	time "time"
)

type measuredCall = tddtest.MeasuredCall

func argvValueOf(t *testing.T, argv []string, flag string) string {
	t.Helper()
	return tddtest.ArgvValueOf(t, argv, flag)
}

func bigFileLines(pkg string, head, tail int) string { return tddtest.BigFileLines(pkg, head, tail) }

func captureStderr(t *testing.T, fn func()) string { t.Helper(); return tddtest.CaptureStderr(t, fn) }

func commitInitial(t *testing.T, repo string) { t.Helper(); tddtest.CommitInitial(t, repo) }

func currentBranch(t *testing.T, repoRoot string) string {
	t.Helper()
	return tddtest.CurrentBranch(t, repoRoot, git)
}

func declareMutantsAtMerge(t *testing.T, root string) {
	t.Helper()
	tddtest.DeclareMutantsAtMerge(t, root)
}

func gitDo(t *testing.T, dir string, args ...string) { t.Helper(); tddtest.GitDo(t, dir, args...) }

func gitInit(t *testing.T, dir string) { t.Helper(); tddtest.GitInit(t, dir) }

func gitOutT(t *testing.T, dir string, args ...string) string {
	t.Helper()
	return tddtest.GitOutT(t, dir, args...)
}

func gitValue(t *testing.T, dir string, args ...string) string {
	t.Helper()
	return tddtest.GitValue(t, dir, args...)
}

func isQualityRunner(r Runner) bool {
	if r.Cmd == golangciLint {
		return true
	}
	if len(r.Args) == 0 {
		return false
	}
	if r.Cmd == "go" {
		return r.Args[0] == "vet"
	}
	if r.Cmd != "cargo" {
		return false
	}
	return r.Args[0] == "fmt" || r.Args[0] == "clippy" || r.Args[0] == "check"
}

func makeCargoWorkspaceRepo(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	gitInit(t, root)
	write(t, root, "Cargo.toml", "[workspace]\nmembers = [\"crates/alpha\", \"crates/beta\"]\n")
	write(t, root, "crates/alpha/Cargo.toml", "[package]\nname = \"alpha\"\nversion = \"0.1.0\"\nedition = \"2021\"\n")
	write(t, root, "crates/beta/Cargo.toml", "[package]\nname = \"beta\"\nversion = \"0.1.0\"\nedition = \"2021\"\n")
	gitDo(t, root, "add", ".")
	gitDo(t, root, "commit", "-qm", "base")
	return root
}

func makeForkedRepo(t *testing.T) (root, trunk string) {
	t.Helper()
	return tddtest.MakeForkedRepo(t, git)
}

func makeGoRepo(t *testing.T) string { t.Helper(); return tddtest.MakeGoRepo(t) }

func makeMultiRootRepo(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	gitInit(t, root)
	write(t, root, "Cargo.toml", "[workspace]\nmembers = [\"crates/a\"]\n")
	write(t, root, "crates/a/Cargo.toml", "[package]\nname = \"a\"\nversion = \"0.1.0\"\n")
	write(t, root, "crates/a/src/lib.rs", "pub fn base() -> i32 { 0 }\n")
	write(t, root, "tools/py/pyproject.toml", "[tool]\n")
	write(t, root, "tools/py/x.py", "def base():\n    return 1\n")
	gitDo(t, root, "add", ".")
	gitDo(t, root, "commit", "-qm", "base")
	return root
}

func outcomeFields(m MutantOutcome) tddtest.Outcome {
	return tddtest.Outcome{Name: mutantLineOf(m.File, m.Line, m.Col, m.Mutation), Package: m.Package, File: m.File, Line: m.Line, Col: m.Col, Status: m.Status}
}

func readEscapes(t *testing.T) []EscapeRecord {
	t.Helper()
	return tddtest.ReadEscapes[EscapeRecord](t, EscapeLogPath())
}

func readFileString(t *testing.T, path string) string {
	t.Helper()
	return tddtest.ReadFileString(t, path)
}

func recordRunner(seen *[]Runner, root string) SuiteRunner {
	return tddtest.RecordRunner(seen, root, recordableRun, SuiteResult{Passed: true})
}

func recordableRun(r Runner) (Runner, bool) {
	if isQualityRunner(r) {
		return r, false
	}
	r.Deadline = time.Time{}
	return r, true
}

func requireNoMutantsMeasurement(t *testing.T, cfgDir string) {
	t.Helper()
	tddtest.RequireNoMutantsMeasurement(t, cfgDir, func(line string) (string, string, bool) { e, ok := parseGateLine(line); return e.Stage, e.Verdict, ok })
}

func stubMutantsExec(t *testing.T, reply func(ctx context.Context, n int, c measuredCall) (int, error)) *[]measuredCall {
	t.Helper()
	return tddtest.StubMutantsExec(t, SetMutantsExecForTest, setMutantsListCountForTest, reply)
}

func write(t *testing.T, dir, rel, content string) { t.Helper(); tddtest.Write(t, dir, rel, content) }

func writeMeasureBase(t *testing.T, root string) { t.Helper(); tddtest.WriteMeasureBase(t, root) }

func writeOutcomesIn(t *testing.T, outDir string, mutants ...MutantOutcome) {
	t.Helper()
	tddtest.WriteOutcomes(t, cargoMutantsOutcomesPath(outDir), outcomeFields, mutants...)
}
