// Code generated by tddsplit. DO NOT EDIT.

package failfirst

import (
	core "github.com/aphrollo/aphrollo-tools/internal/tdd/core"
	time "time"
)

const Source = core.Source

const Test = core.Test

type GateResult = core.GateResult

type Kind = core.Kind

type Outcome = core.Outcome

type Runner = core.Runner

var sourceExts = core.SourceExts

func AppendGateLog(p0 string, p1 string, p2 string, p3 string, p4 time.Duration) {
	core.AppendGateLog(p0, p1, p2, p3, p4)
}

func ClassifyFile(p0 string) Kind { return core.ClassifyFile(p0) }

func StateDir() string { return core.StateDir() }

func dedupeSorted(p0 []string) []string { return core.DedupeSorted(p0) }

func goEmbedsFile(p0 string) bool { return core.GoEmbedsFile(p0) }

func repoStateKey(p0 string) string { return core.RepoStateKey(p0) }

func warnGateLogUnwritable(p0 string) { core.WarnGateLogUnwritable(p0) }

func writeFileAtomic(p0 string, p1 []byte) error { return core.WriteFileAtomic(p0, p1) }
