// Code generated by tddsplit. DO NOT EDIT.

package failfirst

import (
	suite "github.com/aphrollo/aphrollo-tools/internal/tdd/suite"
)

func RetainedSuiteOutput(p0 string) (string, error) { return suite.RetainedSuiteOutput(p0) }

func goRunFilter(p0 []string) string { return suite.GoRunFilter(p0) }
