// Code generated by tddsplit. DO NOT EDIT.

package failfirst

import (
	lock "github.com/aphrollo/aphrollo-tools/internal/tdd/lock"
	time "time"
)

type BuildSlot = lock.BuildSlot

func SetPostEditLockWaitForTest(p0 time.Duration) func() { return lock.SetPostEditLockWaitForTest(p0) }

func SetPrecommitLockWait(p0 time.Duration) func() { return lock.SetPrecommitLockWait(p0) }

func acquireBuildSlot(p0 string, p1 time.Duration, p2 string, p3 string) (BuildSlot, func(), bool) {
	return lock.AcquireBuildSlot(p0, p1, p2, p3)
}

func setBuildLockPathOverride(p0 string) func() { return lock.SetBuildLockPathOverride(p0) }
