// Code generated by tddsplit. DO NOT EDIT.

package failfirst

import (
	lock "github.com/aphrollo/aphrollo-tools/internal/tdd/lock"
	time "time"
)

func ResolveCargoTargetDir(p0 string) string { return lock.ResolveCargoTargetDir(p0) }

func cargoWorkspaceRoot(p0 string) string { return lock.CargoWorkspaceRoot(p0) }

func precommitLockWait() time.Duration { return lock.PrecommitLockWait() }
