// Code generated by tddsplit. DO NOT EDIT.

package failfirst

import (
	suite "github.com/aphrollo/aphrollo-tools/internal/tdd/suite"
	time "time"
)

const Green = suite.Green

const GreenWithWarnings = suite.GreenWithWarnings

const Red = suite.Red

const RedMissingImpl = suite.RedMissingImpl

const ambiguousTest = suite.AmbiguousTest

const outcomeCheckError = suite.OutcomeCheckError

const outcomeTimeout = suite.OutcomeTimeout

type SuiteResult = suite.SuiteResult

type SuiteRunner = suite.SuiteRunner

type goTestEvent = suite.GoTestEvent

type mutantsConfigTable = suite.MutantsConfigTable

type rustSplit = suite.RustSplit

type stageOutcome = suite.StageOutcome

var cargoTestResultRe = suite.CargoTestResultRe

var pytestSummaryCategoryRe = suite.PytestSummaryCategoryRe

var testDeclRes = suite.TestDeclRes

func DetectRunner(p0 string) (Runner, bool) { return suite.DetectRunner(p0) }

func ExtractFailingTests(p0 string) []string { return suite.ExtractFailingTests(p0) }

func cargoModuleFilterPath(p0 string, p1 string) string { return suite.CargoModuleFilterPath(p0, p1) }

func cargoPackagesOwning(p0 string, p1 []string) []string { return suite.CargoPackagesOwning(p0, p1) }

func cargoTargetNamer(p0 string) func(pos int) string { return suite.CargoTargetNamer(p0) }

func cmdString(p0 Runner) string { return suite.CmdString(p0) }

func declaresTest(p0 string, p1 string) (bool, bool) { return suite.DeclaresTest(p0, p1) }

func firstDeclaredList(p0 []mutantsConfigTable, p1 string) []string {
	return suite.FirstDeclaredList(p0, p1)
}

func hashNonEmpty(p0 string) string { return suite.HashNonEmpty(p0) }

func logLockWait(p0 string, p1 string, p2 Runner, p3 time.Duration) {
	suite.LogLockWait(p0, p1, p2, p3)
}

func mutantsConfigTables(p0 string) []mutantsConfigTable { return suite.MutantsConfigTables(p0) }

func narrowFailFirstTests(p0 Runner, p1 string, p2 []string) Runner {
	return suite.NarrowFailFirstTests(p0, p1, p2)
}

func runCargoLocked(p0 SuiteRunner, p1 Runner, p2 string, p3 time.Duration, p4 time.Duration, p5 time.Duration) (SuiteResult, time.Duration, bool) {
	return suite.RunCargoLocked(p0, p1, p2, p3, p4, p5)
}

func rustFileIsTestModule(p0 string, p1 string, p2 string) bool {
	return suite.RustFileIsTestModule(p0, p1, p2)
}

func splitRustTests(p0 string, p1 bool) (rustSplit, bool) { return suite.SplitRustTests(p0, p1) }

func toRootRelative(p0 string, p1 string, p2 []string) []string {
	return suite.ToRootRelative(p0, p1, p2)
}

func vacuousNames(p0 Runner, p1 SuiteResult) ([]string, error) { return suite.VacuousNames(p0, p1) }

func verdictFor(p0 string, p1 string, p2 string, p3 string, p4 stageOutcome) GateResult {
	return suite.VerdictFor(p0, p1, p2, p3, p4)
}

func withGateProfile(p0 Runner, p1 string) Runner { return suite.WithGateProfile(p0, p1) }
