// Code generated by tddsplit. DO NOT EDIT.

package failfirst

import (
	suite "github.com/aphrollo/aphrollo-tools/internal/tdd/suite"
)

func goRunFilter(p0 []string) string { return suite.GoRunFilter(p0) }
