// Code generated by tddsplit. DO NOT EDIT.

package failfirst

import (
	core "github.com/aphrollo/aphrollo-tools/internal/tdd/core"
)

const Ignore = core.Ignore

type gateEntry = core.GateEntry

func parseGateLine(p0 string) (gateEntry, bool) { return core.ParseGateLine(p0) }
