// Code generated by tddsplit. DO NOT EDIT.

package failfirst

import (
	gitx "github.com/aphrollo/aphrollo-tools/internal/tdd/gitx"
)

func git(p0 string, p1 ...string) (string, error) { return gitx.Git(p0, p1...) }

func gitApply(p0 string, p1 string) error { return gitx.GitApply(p0, p1) }

func gitBinary() string { return gitx.GitBinary() }

func gitStaged(p0 string, p1 []string) (string, error) { return gitx.GitStaged(p0, p1) }

func stagedFiles(p0 string) []string { return gitx.StagedFiles(p0) }

func stagedFilesErr(p0 string) ([]string, error) { return gitx.StagedFilesErr(p0) }
