// Code generated by tddsplit. DO NOT EDIT.

package failfirst

const EditProduction = editProduction

const EditTestOnly = editTestOnly

const EditUnknown = editUnknown

const GcOriginFile = gcOriginFile

type FailFirstOutcome = failFirstOutcome

type FileAdd = fileAdd

type LedgerEdit = ledgerEdit

func FailFirstStage(p0 string, p1 string, p2 []string, p3 []string, p4 SuiteRunner) GateResult {
	return failFirstStage(p0, p1, p2, p3, p4)
}

func FailFirstStageWithRustNotice(p0 string, p1 string, p2 []string, p3 []string, p4 SuiteRunner) GateResult {
	return failFirstStageWithRustNotice(p0, p1, p2, p3, p4)
}

func FailFirstViolated(p0 string, p1 []string, p2 []string, p3 SuiteRunner) failFirstOutcome {
	return failFirstViolated(p0, p1, p2, p3)
}

func FailFirstViolatedAt(p0 string, p1 string, p2 []string, p3 []string, p4 SuiteRunner) failFirstOutcome {
	return failFirstViolatedAt(p0, p1, p2, p3, p4)
}

func FailFirstWorktreeDir(p0 string) string { return failFirstWorktreeDir(p0) }

func HeadSHAFor(p0 string) string { return headSHAFor(p0) }

func LoadEditLedger(p0 string) []ledgerEdit { return loadEditLedger(p0) }

func NamesPath(p0 string, p1 string) bool { return namesPath(p0, p1) }

func ProofInputs(p0 string, p1 []string) []string { return proofInputs(p0, p1) }

func ReadFailFirstEnv(p0 string) []string { return readFailFirstEnv(p0) }

func RecordEdit(p0 string, p1 string) string { return recordEdit(p0, p1) }

func RecordEditVerdict(p0 string, p1 string, p2 string, p3 Outcome, p4 string) {
	recordEditVerdict(p0, p1, p2, p3, p4)
}

func ResolvedDevTarget(p0 string) string { return resolvedDevTarget(p0) }

func SplitKinds(p0 []string) ([]string, []string) { return splitKinds(p0) }

func StagedAdds(p0 string) []fileAdd { return stagedAdds(p0) }
