// Code generated by tddsplit. DO NOT EDIT.

package failfirst

import (
	tddtest "github.com/aphrollo/aphrollo-tools/internal/tdd/internal/tddtest"
	testing "testing"
)

const ledgerWidgetFixed = tddtest.LedgerWidgetFixed

const ledgerWidgetImpl = tddtest.LedgerWidgetImpl

const ledgerWidgetWithTest = tddtest.LedgerWidgetWithTest

const vacuousPkgJSONLine = tddtest.VacuousPkgJSONLine

func captureStderr(t *testing.T, fn func()) string { t.Helper(); return tddtest.CaptureStderr(t, fn) }

func gateLineFields(line string) (stage, verdict string, ok bool) {
	e, ok := parseGateLine(line)
	return e.Stage, e.Verdict, ok
}

func gateLogText(t *testing.T, cfg string) string { t.Helper(); return tddtest.GateLogText(t, cfg) }

func gitDo(t *testing.T, dir string, args ...string) { t.Helper(); tddtest.GitDo(t, dir, args...) }

func ledgerRepo(t *testing.T) string { t.Helper(); return tddtest.LedgerRepo(t) }

func makeCargoRepo(t *testing.T) string { t.Helper(); return tddtest.MakeCargoRepo(t) }

func makeGoRepo(t *testing.T) string { t.Helper(); return tddtest.MakeGoRepo(t) }

func requireLoggedVerdict(t *testing.T, cfg, verdict string) {
	t.Helper()
	tddtest.RequireLoggedVerdict(t, cfg, verdict, gateLineFields)
}

func withIsolatedBuildLock(t *testing.T) {
	t.Helper()
	tddtest.IsolateBuildLock(t, setBuildLockPathOverride, SetPostEditLockWaitForTest, SetPrecommitLockWait)
}

func write(t *testing.T, dir, rel, content string) { t.Helper(); tddtest.Write(t, dir, rel, content) }
