package cli

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func declareUndercover(t *testing.T, repo string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(repo, "aphrollo.toml"), []byte("[aphrollo]\nundercover = true\n"), 0o600); err != nil {
		t.Fatal(err)
	}
}

func ghWasCalled(t *testing.T, log string) bool {
	t.Helper()
	data, _ := os.ReadFile(log)
	return strings.Contains(string(data), "issue create")
}

func TestGateIssue_RefusesATellInTheTitleOrBodyBeforeCallingGh(t *testing.T) {
	repo, log := stubIssueRepo(t, "https://github.com/o/r/issues/12")
	declareUndercover(t, repo)
	for _, c := range []struct {
		args  []string
		quote []string
	}{
		{[]string{"gate", "issue", "Claude drifts at 60 Hz", "--repo", repo}, []string{"issue title", "Claude drifts at 60 Hz"}},
		{[]string{"gate", "issue", "the rig drifts", "--body", "Seen twice.\n\n_Generated by [Claude Code](https://x.example)_", "--repo", repo}, []string{"issue body", "line 3"}},
	} {
		var out, errb bytes.Buffer
		if code := Run(c.args, strings.NewReader(""), &out, &errb); code == 0 {
			t.Errorf("%v: want a refusal, got exit 0", c.args)
		}
		for _, want := range c.quote {
			if !strings.Contains(errb.String(), want) {
				t.Errorf("%v: refusal %q lacks %q", c.args, errb.String(), want)
			}
		}
	}
	if ghWasCalled(t, log) {
		t.Error("a refused issue reached gh")
	}
}

func TestGateIssue_PassesOrdinaryTextToGh(t *testing.T) {
	repo, log := stubIssueRepo(t, "https://github.com/o/r/issues/12")
	declareUndercover(t, repo)
	var out, errb bytes.Buffer
	code := Run([]string{"gate", "issue", "the cursor drifts in Cairo", "--body", "The AIR case too.", "--repo", repo}, strings.NewReader(""), &out, &errb)
	if code != 0 {
		t.Fatalf("exit %d: %s", code, errb.String())
	}
	if !ghWasCalled(t, log) {
		t.Error("an ordinary issue never reached gh")
	}
}

func TestGateIssue_UndercoverIsInertWhenTheRepoNeverAsked(t *testing.T) {
	repo, log := stubIssueRepo(t, "https://github.com/o/r/issues/12")
	var out, errb bytes.Buffer
	if code := Run([]string{"gate", "issue", "Claude drifts", "--repo", repo}, strings.NewReader(""), &out, &errb); code != 0 {
		t.Fatalf("exit %d: %s", code, errb.String())
	}
	if !ghWasCalled(t, log) {
		t.Error("the issue never reached gh in a repo that never opted in")
	}
}

func TestGateFeedback_RefusesATellBeforeCallingGh(t *testing.T) {
	repo, log := stubIssueRepo(t, "https://github.com/o/tool/issues/3")
	declareUndercover(t, repo)
	var out, errb bytes.Buffer
	code := Run([]string{"gate", "feedback", "the gate rejected a clean commit", "--body", "ran under opus-5", "--repo", repo, "--upstream", "o/tool"}, strings.NewReader(""), &out, &errb)
	if code == 0 {
		t.Fatal("want a refusal, got exit 0")
	}
	if !strings.Contains(errb.String(), "ran under opus-5") {
		t.Errorf("refusal %q does not quote the line", errb.String())
	}
	if ghWasCalled(t, log) {
		t.Error("a refused report reached gh")
	}
}

func TestGateFeedback_PassesOrdinaryTextToGh(t *testing.T) {
	repo, log := stubIssueRepo(t, "https://github.com/o/tool/issues/3")
	declareUndercover(t, repo)
	var out, errb bytes.Buffer
	code := Run([]string{"gate", "feedback", "the gate rejected a clean commit", "--body", "a fable about the tortoise was refused", "--repo", repo, "--upstream", "o/tool"}, strings.NewReader(""), &out, &errb)
	if code != 0 {
		t.Fatalf("exit %d: %s", code, errb.String())
	}
	if !ghWasCalled(t, log) {
		t.Error("an ordinary report never reached gh")
	}
}
