// Code generated by tddsplit. DO NOT EDIT.

package precommit

import (
	core "github.com/aphrollo/aphrollo-tools/internal/tdd/core"
)

const Ignore = core.Ignore

const premergeLogToken = core.PremergeLogToken

type Event = core.Event

type sessionState = core.SessionState

func GateLogPath() string { return core.GateLogPath() }

func ReadEvents(p0 string) []Event { return core.ReadEvents(p0) }

func loadSession(p0 string) (*sessionState, string) { return core.LoadSession(p0) }

func parseGateLine(p0 string) (gateEntry, bool) { return core.ParseGateLine(p0) }
