// Code generated by tddsplit. DO NOT EDIT.

package precommit

import (
	failfirst "github.com/aphrollo/aphrollo-tools/internal/tdd/failfirst"
)

type failFirstOutcome = failfirst.FailFirstOutcome

func failFirstViolated(p0 string, p1 []string, p2 []string, p3 SuiteRunner) failFirstOutcome {
	return failfirst.FailFirstViolated(p0, p1, p2, p3)
}

func failFirstViolatedAt(p0 string, p1 string, p2 []string, p3 []string, p4 SuiteRunner) failFirstOutcome {
	return failfirst.FailFirstViolatedAt(p0, p1, p2, p3, p4)
}

func namesPath(p0 string, p1 string) bool { return failfirst.NamesPath(p0, p1) }

func proofInputs(p0 string, p1 []string) []string { return failfirst.ProofInputs(p0, p1) }
