// Code generated by tddsplit. DO NOT EDIT.

package precommit

import (
	suite "github.com/aphrollo/aphrollo-tools/internal/tdd/suite"
	time "time"
)

const Green = suite.Green

const outcomeCheckError = suite.OutcomeCheckError

const outcomeContention = suite.OutcomeContention

const outcomeFail = suite.OutcomeFail

const outcomePass = suite.OutcomePass

const outcomeSkipped = suite.OutcomeSkipped

const outcomeTimeout = suite.OutcomeTimeout

const outcomeVacuous = suite.OutcomeVacuous

type SuiteResult = suite.SuiteResult

type SuiteRunner = suite.SuiteRunner

type stageOutcome = suite.StageOutcome

type suiteProofLedger = suite.SuiteProofLedger

func DetectRunner(p0 string) (Runner, bool) { return suite.DetectRunner(p0) }

func ExtractFailingTests(p0 string) []string { return suite.ExtractFailingTests(p0) }

func cargoAlwaysRunPackages(p0 string) []string { return suite.CargoAlwaysRunPackages(p0) }

func cargoAphrolloFlag(p0 string, p1 string) bool { return suite.CargoAphrolloFlag(p0, p1) }

func cargoClippyCleanPackages(p0 string) []string { return suite.CargoClippyCleanPackages(p0) }

func cargoPackageFor(p0 string, p1 string) string { return suite.CargoPackageFor(p0, p1) }

func cargoPackagesOwning(p0 string, p1 []string) []string { return suite.CargoPackagesOwning(p0, p1) }

func cargoVerbArgs(p0 string) []string { return suite.CargoVerbArgs(p0) }

func cargoWorkspaceDepsFn(p0 string) (map[string][]string, error) {
	return suite.CargoWorkspaceDepsFn(p0)
}

func clippyScope(p0 string, p1 string, p2 string, p3 []string) []string {
	return suite.ClippyScope(p0, p1, p2, p3)
}

func cmdString(p0 Runner) string { return suite.CmdString(p0) }

func dependentsOf(p0 map[string][]string, p1 []string) []string { return suite.DependentsOf(p0, p1) }

func dirHasGoFiles(p0 string) bool { return suite.DirHasGoFiles(p0) }

func doctestRunners(p0 string, p1 []string) []Runner { return suite.DoctestRunners(p0, p1) }

func filesUnderRoot(p0 string, p1 string, p2 []string) []string {
	return suite.FilesUnderRoot(p0, p1, p2)
}

func gateSuiteProof() *suiteProofLedger { return suite.GateSuiteProof() }

func goPackageDir(p0 string, p1 string) string { return suite.GoPackageDir(p0, p1) }

func indexTree(p0 string) string { return suite.IndexTree(p0) }

func logLockWait(p0 string, p1 string, p2 Runner, p3 time.Duration) {
	suite.LogLockWait(p0, p1, p2, p3)
}

func logSuiteVerdict(p0 string, p1 string, p2 string, p3 string, p4 SuiteResult) {
	suite.LogSuiteVerdict(p0, p1, p2, p3, p4)
}

func mechCacheAdd(p0 string) { suite.MechCacheAdd(p0) }

func mechCacheHit(p0 string) bool { return suite.MechCacheHit(p0) }

func mechKey(p0 string, p1 string, p2 Runner) string { return suite.MechKey(p0, p1, p2) }

func narrowToStaged(p0 Runner, p1 string, p2 []string) (Runner, bool) {
	return suite.NarrowToStaged(p0, p1, p2)
}

func reportSuitesNotRun(p0 string, p1 string, p2 string, p3 Runner, p4 []string) {
	suite.ReportSuitesNotRun(p0, p1, p2, p3, p4)
}

func resetSuiteProof() { suite.ResetSuiteProof() }

func runCargoLocked(p0 SuiteRunner, p1 Runner, p2 string, p3 time.Duration, p4 time.Duration, p5 time.Duration) (SuiteResult, time.Duration, bool) {
	return suite.RunCargoLocked(p0, p1, p2, p3, p4, p5)
}

func stagedProjectRoots(p0 string, p1 []string) []string { return suite.StagedProjectRoots(p0, p1) }

func suiteNoun(p0 string) string { return suite.SuiteNoun(p0) }

func suiteTouchedNames(p0 Runner) []string { return suite.SuiteTouchedNames(p0) }

func toRootRelative(p0 string, p1 string, p2 []string) []string {
	return suite.ToRootRelative(p0, p1, p2)
}

func untestedVerdict(p0 Runner, p1 SuiteResult) string { return suite.UntestedVerdict(p0, p1) }

func vacuousNames(p0 Runner, p1 SuiteResult) ([]string, error) { return suite.VacuousNames(p0, p1) }

func verdictFor(p0 string, p1 string, p2 string, p3 string, p4 stageOutcome) GateResult {
	return suite.VerdictFor(p0, p1, p2, p3, p4)
}

func withGateProfile(p0 Runner, p1 string) Runner { return suite.WithGateProfile(p0, p1) }

func worktreeStateHash(p0 string) string { return suite.WorktreeStateHash(p0) }
