// Code generated by tddsplit. DO NOT EDIT.

package precommit

import (
	mutation "github.com/aphrollo/aphrollo-tools/internal/tdd/mutation"
)

type MutantsConfig = mutation.MutantsConfig

func mutantsConfigStage(p0 string, p1 string) (MutantsConfig, GateResult) {
	return mutation.MutantsConfigStage(p0, p1)
}

func mutantsStage(p0 string, p1 string) GateResult { return mutation.MutantsStage(p0, p1) }
