// Code generated by tddsplit. DO NOT EDIT.

package precommit

import (
	gitx "github.com/aphrollo/aphrollo-tools/internal/tdd/gitx"
)

func TrunkBranch(p0 string) string { return gitx.TrunkBranch(p0) }

func branchIsTrunk(p0 string, p1 string) bool { return gitx.BranchIsTrunk(p0, p1) }

func git(p0 string, p1 ...string) (string, error) { return gitx.Git(p0, p1...) }

func mergeInProgressRef(p0 string) string { return gitx.MergeInProgressRef(p0) }

func stagedBaseRev(p0 string) string { return gitx.StagedBaseRev(p0) }

func stagedFiles(p0 string) []string { return gitx.StagedFiles(p0) }

func stagedFilesErr(p0 string) ([]string, error) { return gitx.StagedFilesErr(p0) }
