// Code generated by tddsplit. DO NOT EDIT.

package precommit

import (
	ratchet "github.com/aphrollo/aphrollo-tools/internal/ratchet"
	lawgate "github.com/aphrollo/aphrollo-tools/internal/tdd/lawgate"
)

func baselineStage(p0 string, p1 string) GateResult { return lawgate.BaselineStage(p0, p1) }

func gitBlob(p0 string, p1 string) (string, bool) { return lawgate.GitBlob(p0, p1) }

func laneChangedPaths(p0 string) []string { return lawgate.LaneChangedPaths(p0) }

func ratchetCheckFn(p0 ratchet.Options) (ratchet.Result, error) { return lawgate.RatchetCheckFn(p0) }

func ratchetStage(p0 string, p1 string) GateResult { return lawgate.RatchetStage(p0, p1) }

func trackedFiles(p0 string) []string { return lawgate.TrackedFiles(p0) }

func trackedIgnoredFiles(p0 string) []string { return lawgate.TrackedIgnoredFiles(p0) }
