// Code generated by tddsplit. DO NOT EDIT.

package precommit

import (
	smell "github.com/aphrollo/aphrollo-tools/internal/tdd/smell"
)

const commitPhase = smell.CommitPhase

type lang = smell.Lang

type phase = smell.Phase

type policy = smell.Policy

var suppressionPolicies = smell.SuppressionPolicies

var testOracleWarnings = smell.TestOracleWarnings

func concatPolicies(p0 ...[]policy) []policy { return smell.ConcatPolicies(p0...) }

func evaluateAdded(p0 string, p1 map[int]bool, p2 lang, p3 []policy, p4 phase) Decision {
	return smell.EvaluateAdded(p0, p1, p2, p3, p4)
}

func langOf(p0 string) lang { return smell.LangOf(p0) }
