// Code generated by tddsplit. DO NOT EDIT.

package precommit

import (
	gitx "github.com/aphrollo/aphrollo-tools/internal/tdd/gitx"
)

const reflogActionEnv = gitx.ReflogActionEnv

func RepoRoot(p0 string) string { return gitx.RepoRoot(p0) }

func cleanGitEnv() []string { return gitx.CleanGitEnv() }

func gitOut(p0 string, p1 ...string) string { return gitx.GitOut(p0, p1...) }
