// Code generated by tddsplit. DO NOT EDIT.

package precommit

import (
	postedit "github.com/aphrollo/aphrollo-tools/internal/tdd/postedit"
)

func PostEdit(p0 []byte, p1 SuiteRunner) string { return postedit.PostEdit(p0, p1) }
