// Code generated by tddsplit. DO NOT EDIT.

package precommit

import (
	gitx "github.com/aphrollo/aphrollo-tools/internal/tdd/gitx"
)

func CommitStagedSubset(p0 string, p1 []string, p2 string) (string, error) {
	return gitx.CommitStagedSubset(p0, p1, p2)
}

func TrunkBranch(p0 string) string { return gitx.TrunkBranch(p0) }

func branchIsTrunk(p0 string, p1 string) bool { return gitx.BranchIsTrunk(p0, p1) }

func git(p0 string, p1 ...string) (string, error) { return gitx.Git(p0, p1...) }

func gitApplyIndex(p0 string, p1 string) error { return gitx.GitApplyIndex(p0, p1) }

func gitOut(p0 string, p1 ...string) string { return gitx.GitOut(p0, p1...) }

func gitStaged(p0 string, p1 []string) (string, error) { return gitx.GitStaged(p0, p1) }

func mergeInProgressRef(p0 string) string { return gitx.MergeInProgressRef(p0) }

func stagedBaseRev(p0 string) string { return gitx.StagedBaseRev(p0) }

func stagedFiles(p0 string) []string { return gitx.StagedFiles(p0) }

func stagedFilesErr(p0 string) ([]string, error) { return gitx.StagedFilesErr(p0) }

func trunkSyncTip(p0 string) (string, bool) { return gitx.TrunkSyncTip(p0) }
