// Code generated by tddsplit. DO NOT EDIT.

package precommit

import (
	postedit "github.com/aphrollo/aphrollo-tools/internal/tdd/postedit"
	time "time"
)

func buildLockHolderNote(p0 string) string { return postedit.BuildLockHolderNote(p0) }

func greenLabel(p0 Outcome, p1 string, p2 time.Duration) string {
	return postedit.GreenLabel(p0, p1, p2)
}

func tailSnippet(p0 string) string { return postedit.TailSnippet(p0) }

func treatAsEmptyPass(p0 SuiteResult) bool { return postedit.TreatAsEmptyPass(p0) }
