// Code generated by tddsplit. DO NOT EDIT.

package precommit

import (
	core "github.com/aphrollo/aphrollo-tools/internal/tdd/core"
	time "time"
)

const Block = core.Block

const Source = core.Source

const Test = core.Test

const premergeDisplayName = core.PremergeDisplayName

type Decision = core.Decision

type GateResult = core.GateResult

type Kind = core.Kind

type Outcome = core.Outcome

type Runner = core.Runner

type gateEntry = core.GateEntry

var ignoredDirs = core.IgnoredDirs

func AppendGateLog(p0 string, p1 string, p2 string, p3 string, p4 time.Duration) {
	core.AppendGateLog(p0, p1, p2, p3, p4)
}

func ClassifyFile(p0 string) Kind { return core.ClassifyFile(p0) }

func StateDir() string { return core.StateDir() }

func dedupeSorted(p0 []string) []string { return core.DedupeSorted(p0) }

func maskTokens(p0 string, p1 bool, p2 bool, p3 bool) string { return core.MaskTokens(p0, p1, p2, p3) }

func parseGateLine(p0 string) (gateEntry, bool) { return core.ParseGateLine(p0) }

func quotedWords(p0 string) []string { return core.QuotedWords(p0) }

func sameProject(p0 string, p1 string) bool { return core.SameProject(p0, p1) }

func stripQuoted(p0 string) string { return core.StripQuoted(p0) }
