// Code generated by tddsplit. DO NOT EDIT.

package precommit

import (
	core "github.com/aphrollo/aphrollo-tools/internal/tdd/core"
	time "time"
)

const Block = core.Block

const HeadWorktreeDir = core.HeadWorktreeDir

const HeadWorktreePrefix = core.HeadWorktreePrefix

const Source = core.Source

const StateSchema = core.StateSchema

const Test = core.Test

const premergeDisplayName = core.PremergeDisplayName

type Decision = core.Decision

type GateResult = core.GateResult

type Kind = core.Kind

type Outcome = core.Outcome

type Runner = core.Runner

type gateEntry = core.GateEntry

var ignoredDirs = core.IgnoredDirs

func AppendGateLog(p0 string, p1 string, p2 string, p3 string, p4 time.Duration) {
	core.AppendGateLog(p0, p1, p2, p3, p4)
}

func AppendGateLogDetail(p0 string, p1 string, p2 string, p3 string, p4 time.Duration, p5 map[string]string) {
	core.AppendGateLogDetail(p0, p1, p2, p3, p4, p5)
}

func ClassifyFile(p0 string) Kind { return core.ClassifyFile(p0) }

func StateDir() string { return core.StateDir() }

func addGateWorktree(p0 string) (string, error) { return core.AddGateWorktree(p0) }

func aphrolloTomlString(p0 string, p1 string) (string, bool) { return core.AphrolloTomlString(p0, p1) }

func dedupeSorted(p0 []string) []string { return core.DedupeSorted(p0) }

func maskTokens(p0 string, p1 bool, p2 bool, p3 bool) string { return core.MaskTokens(p0, p1, p2, p3) }

func quotedWords(p0 string) []string { return core.QuotedWords(p0) }

func readGateEntries(p0 string, p1 time.Time) []gateEntry { return core.ReadGateEntries(p0, p1) }

func readStateJSON(p0 string, p1 any) (bool, bool) { return core.ReadStateJSON(p0, p1) }

func removeGateWorktree(p0 string, p1 string) { core.RemoveGateWorktree(p0, p1) }

func samePath(p0 string, p1 string) bool { return core.SamePath(p0, p1) }

func sameProject(p0 string, p1 string) bool { return core.SameProject(p0, p1) }

func stripQuoted(p0 string) string { return core.StripQuoted(p0) }

func writeFileAtomic(p0 string, p1 []byte) error { return core.WriteFileAtomic(p0, p1) }
