// Code generated by tddsplit. DO NOT EDIT.

package precommit

import (
	lock "github.com/aphrollo/aphrollo-tools/internal/tdd/lock"
	time "time"
)

const buildLockPollInterval = lock.BuildLockPollInterval

const buildSlotsEnv = lock.BuildSlotsEnv

const maxAncestryDepth = lock.MaxAncestryDepth

const suiteFloorMargin = lock.SuiteFloorMargin

type BuildSlot = lock.BuildSlot

type procSample = lock.ProcSample

func ResolveCargoTargetDir(p0 string) string { return lock.ResolveCargoTargetDir(p0) }

func SetLockWaitLogThresholdForTest(p0 time.Duration) func() {
	return lock.SetLockWaitLogThresholdForTest(p0)
}

func SetMachineLoadSampleForTest(p0 func(stop <-chan struct{}) (int, float64, []procSample, bool)) func() {
	return lock.SetMachineLoadSampleForTest(p0)
}

func SetPostEditLockWaitForTest(p0 time.Duration) func() { return lock.SetPostEditLockWaitForTest(p0) }

func SetPrecommitLockWait(p0 time.Duration) func() { return lock.SetPrecommitLockWait(p0) }

func TryAcquireBuildSlot(p0 string, p1 string, p2 string) (BuildSlot, func(), bool) {
	return lock.TryAcquireBuildSlot(p0, p1, p2)
}

func acquireBuildSlot(p0 string, p1 time.Duration, p2 string, p3 string) (BuildSlot, func(), bool) {
	return lock.AcquireBuildSlot(p0, p1, p2, p3)
}

func cappedFloor(p0 time.Duration, p1 time.Duration) time.Duration { return lock.CappedFloor(p0, p1) }

func isSettledVerdict(p0 string) bool { return lock.IsSettledVerdict(p0) }

func resolveTargetDir(p0 func(string) string, p1 string) string { return lock.ResolveTargetDir(p0, p1) }

func setBuildLockPathOverride(p0 string) func() { return lock.SetBuildLockPathOverride(p0) }

func suiteFloorFrom(p0 []float64) suiteFloor { return lock.SuiteFloorFrom(p0) }
