// Code generated by tddsplit. DO NOT EDIT.

package precommit

import (
	failfirst "github.com/aphrollo/aphrollo-tools/internal/tdd/failfirst"
)

const DefaultPrecommitTimeout = failfirst.DefaultPrecommitTimeout

type HeadGreen = failfirst.HeadGreen

func ProveGreenAtHead(p0 string, p1 string, p2 []string, p3 []string, p4 SuiteRunner) (HeadGreen, bool) {
	return failfirst.ProveGreenAtHead(p0, p1, p2, p3, p4)
}

func failFirstStage(p0 string, p1 string, p2 []string, p3 []string, p4 SuiteRunner) GateResult {
	return failfirst.FailFirstStage(p0, p1, p2, p3, p4)
}

func failFirstStageWithRustNotice(p0 string, p1 string, p2 []string, p3 []string, p4 SuiteRunner) GateResult {
	return failfirst.FailFirstStageWithRustNotice(p0, p1, p2, p3, p4)
}

func pytestExecRunner(p0 string, p1 Runner) (Runner, string) {
	return failfirst.PytestExecRunner(p0, p1)
}

func pytestRemedyRoot(p0 string) string { return failfirst.PytestRemedyRoot(p0) }

func resolvedDevTarget(p0 string) string { return failfirst.ResolvedDevTarget(p0) }

func splitKinds(p0 []string) ([]string, []string) { return failfirst.SplitKinds(p0) }
