// Code generated by tddsplit. DO NOT EDIT.

package precommit

import (
	lawgate "github.com/aphrollo/aphrollo-tools/internal/tdd/lawgate"
)

func ratchetFixtureStage(p0 string, p1 string) GateResult { return lawgate.RatchetFixtureStage(p0, p1) }
