// Code generated by tddsplit. DO NOT EDIT.

package precommit

import (
	lock "github.com/aphrollo/aphrollo-tools/internal/tdd/lock"
	time "time"
)

type BuildLockOwner = lock.BuildLockOwner

type suiteFloor = lock.SuiteFloor

var lintLockDeadline = lock.LintLockDeadline

func AcquireLintLock(p0 string, p1 string, p2 time.Duration) (func(), time.Duration, bool, bool) {
	return lock.AcquireLintLock(p0, p1, p2)
}

func ReadBuildSlotOwner(p0 string) (BuildLockOwner, bool) { return lock.ReadBuildSlotOwner(p0) }

func cargoWorkspaceRoot(p0 string) string { return lock.CargoWorkspaceRoot(p0) }

func foreignLoadReport(p0 int) string { return lock.ForeignLoadReport(p0) }

func precommitLockWait() time.Duration { return lock.PrecommitLockWait() }

func recordedSuiteFloor(p0 string, p1 string) suiteFloor { return lock.RecordedSuiteFloor(p0, p1) }

func runnerTargetDir(p0 Runner, p1 string) string { return lock.RunnerTargetDir(p0, p1) }
