// Code generated by tddsplit. DO NOT EDIT.

package precommit

import (
	core "github.com/aphrollo/aphrollo-tools/internal/tdd/core"
)

const Ignore = core.Ignore

const premergeLogToken = core.PremergeLogToken

type sessionState = core.SessionState

func GateLogPath() string { return core.GateLogPath() }

func loadSession(p0 string) (*sessionState, string) { return core.LoadSession(p0) }
