// Code generated by tddsplit. DO NOT EDIT.

package precommit

import (
	suite "github.com/aphrollo/aphrollo-tools/internal/tdd/suite"
	time "time"
)

const BuildOnly = suite.BuildOnly

const NoTestsSelected = suite.NoTestsSelected

const WritingTest = suite.WritingTest

type stageOutcomeKind = suite.StageOutcomeKind

var registeredStages = suite.RegisteredStages

func NarrowToRelatedTests(p0 Runner, p1 string, p2 string) Runner {
	return suite.NarrowToRelatedTests(p0, p1, p2)
}

func RetainedSuiteOutput(p0 string) (string, error) { return suite.RetainedSuiteOutput(p0) }

func RunSuite(p0 time.Duration) SuiteRunner { return suite.RunSuite(p0) }

func SetCargoTestTargetsForTest(p0 func(root string) map[string]map[string]bool) func() {
	return suite.SetCargoTestTargetsForTest(p0)
}

func SetCargoWorkspaceDepsForTest(p0 func(root string) (map[string][]string, error)) func() {
	return suite.SetCargoWorkspaceDepsForTest(p0)
}

func cargoAphrolloPackages(p0 string, p1 string) []string { return suite.CargoAphrolloPackages(p0, p1) }

func cargoRunnerAt(p0 string, p1 ...string) (Runner, bool) { return suite.CargoRunnerAt(p0, p1...) }

func cargoVacuousTargets(p0 string) []string { return suite.CargoVacuousTargets(p0) }

func hasGateProfile(p0 string) bool { return suite.HasGateProfile(p0) }

func narrowFailFirstTests(p0 Runner, p1 string, p2 []string) Runner {
	return suite.NarrowFailFirstTests(p0, p1, p2)
}

func nextestInstalled() bool { return suite.NextestInstalled() }

func packageHasDoctests(p0 string) bool { return suite.PackageHasDoctests(p0) }

func parseWorkspaceDeps(p0 []byte) (map[string][]string, error) { return suite.ParseWorkspaceDeps(p0) }

func vacuousGoPackages(p0 string) ([]string, error) { return suite.VacuousGoPackages(p0) }
