// Code generated by tddsplit. DO NOT EDIT.

package precommit

import (
	escape "github.com/aphrollo/aphrollo-tools/internal/tdd/escape"
	io "io"
	time "time"
)

type Stats = escape.Stats

func GateStats(p0 io.Reader, p1 time.Time) Stats { return escape.GateStats(p0, p1) }

func RenderGateStats(p0 Stats) string { return escape.RenderGateStats(p0) }
