// Code generated by tddsplit. DO NOT EDIT.

package precommit

const GolangciLint = golangciLint

type OwedSuite = owedSuite

func CommitOwedSuites(p0 string) []owedSuite { return commitOwedSuites(p0) }

func LinterVersion(p0 string) string { return linterVersion(p0) }

func LookLinter() bool { return lookLinter() }

func PinnedLinterVersion(p0 string) string { return pinnedLinterVersion(p0) }
