// Code generated by tddsplit. DO NOT EDIT.

package precommit

const GolangciLint = golangciLint

type RootGroup = rootGroup

func LinterVersion(p0 string) string { return linterVersion(p0) }

func LookLinter() bool { return lookLinter() }

func PinnedLinterVersion(p0 string) string { return pinnedLinterVersion(p0) }

func StagedRootGroups(p0 string) []rootGroup { return stagedRootGroups(p0) }
