package precommit

import (
	"reflect"
	"testing"
)

const lockBeforeLeftpadBump = `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "alpha"
version = "0.1.0"
dependencies = [
 "leftpad",
]

[[package]]
name = "beta"
version = "0.1.0"

[[package]]
name = "leftpad"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "aaaa"
`

const lockAfterLeftpadBump = `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "alpha"
version = "0.1.0"
dependencies = [
 "leftpad",
]

[[package]]
name = "beta"
version = "0.1.0"

[[package]]
name = "leftpad"
version = "1.0.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "bbbb"
`

// A dependency bump moves one package's locked version; lockfileScope must
// narrow to that package plus the workspace crate depending on it, and leave
// out the workspace crate that does not.
func TestLockfileScope_NarrowsToMovedPackageAndItsWorkspaceDependent(t *testing.T) {
	root := t.TempDir()
	gitInit(t, root)
	write(t, root, "Cargo.lock", lockBeforeLeftpadBump)
	gitDo(t, root, "add", ".")
	gitDo(t, root, "commit", "-qm", "base lockfile")

	write(t, root, "Cargo.lock", lockAfterLeftpadBump)
	gitDo(t, root, "add", "Cargo.lock")

	stubWorkspaceGraph(t, map[string][]string{"alpha": nil, "beta": nil})

	got := lockfileScope("g", root, root, []string{"Cargo.lock"})
	want := []string{"alpha"}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("lockfileScope = %v, want %v (alpha depends on the moved package, beta does not)", got, want)
	}
}

// Cargo.toml staged alongside Cargo.lock keeps the wide, whole-workspace
// scope: a manifest change can reshape the build in ways a lockfile diff
// alone cannot see.
func TestLockfileScope_NilWhenCargoTomlAlsoChanged(t *testing.T) {
	root := t.TempDir()
	got := lockfileScope("g", root, root, []string{"Cargo.toml", "Cargo.lock"})
	if got != nil {
		t.Fatalf("lockfileScope = %v, want nil (a manifest change must keep the workspace-wide scope)", got)
	}
}

// A Cargo.lock with no HEAD revision to diff against (e.g. a base commit
// that predates the file) must fall back to the wide scope rather than
// treating "no baseline" as "nothing moved".
func TestLockfileScope_NilWhenNoHeadRevisionToDiff(t *testing.T) {
	root := t.TempDir()
	gitInit(t, root)
	write(t, root, "unrelated.txt", "x")
	gitDo(t, root, "add", ".")
	gitDo(t, root, "commit", "-qm", "base, no Cargo.lock yet")
	write(t, root, "Cargo.lock", lockAfterLeftpadBump)
	gitDo(t, root, "add", "Cargo.lock")

	got := lockfileScope("g", root, root, []string{"Cargo.lock"})
	if got != nil {
		t.Fatalf("lockfileScope = %v, want nil (no HEAD Cargo.lock to diff against)", got)
	}
}

// A version bump touching no package any workspace crate depends on narrows
// to an empty, non-nil scope: a real narrowing to zero, which
// workspaceManifestCheckStage reads as "skip the check", never as the
// wide-scope failure signal (nil).
func TestLockfileScope_EmptyNotNilWhenMovedPackageHasNoWorkspaceDependent(t *testing.T) {
	root := t.TempDir()
	gitInit(t, root)
	write(t, root, "Cargo.lock", lockBeforeLeftpadBump)
	gitDo(t, root, "add", ".")
	gitDo(t, root, "commit", "-qm", "base lockfile")
	write(t, root, "Cargo.lock", lockAfterLeftpadBump)
	gitDo(t, root, "add", "Cargo.lock")

	// Neither alpha nor beta is a workspace member in this graph, so the
	// bumped leftpad's only "dependent" (alpha) does not count.
	stubWorkspaceGraph(t, map[string][]string{})

	got := lockfileScope("g", root, root, []string{"Cargo.lock"})
	if got == nil {
		t.Fatal("lockfileScope = nil, want an empty non-nil slice (moved package affects no workspace crate)")
	}
	if len(got) != 0 {
		t.Fatalf("lockfileScope = %v, want empty", got)
	}
}

// parseCargoLock reads name, version and dependencies out of a real
// multi-package lockfile, stripping a disambiguated "name version"
// dependency entry down to its bare name.
func TestParseCargoLock_ReadsNameVersionAndDependencies(t *testing.T) {
	data := `version = 3

[[package]]
name = "alpha"
version = "0.1.0"
dependencies = [
 "leftpad",
 "getrandom 0.2.15",
]

[[package]]
name = "leftpad"
version = "1.0.0"
`
	got, err := parseCargoLock(data)
	if err != nil {
		t.Fatalf("parseCargoLock: %v", err)
	}
	want := []lockPackage{
		{name: "alpha", version: "0.1.0", deps: []string{"leftpad", "getrandom"}},
		{name: "leftpad", version: "1.0.0"},
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("parseCargoLock = %+v, want %+v", got, want)
	}
}
