// Code generated by tddsplit. DO NOT EDIT.

package precommit

import (
	context "context"
	tddtest "github.com/aphrollo/aphrollo-tools/internal/tdd/internal/tddtest"
	testing "testing"
)

const checkStageLoadFixtureLeaf = tddtest.CheckStageLoadFixtureLeaf

const exampleCompiledOutput = tddtest.ExampleCompiledOutput

const nextestSixPassedOutput = tddtest.NextestSixPassedOutput

const syntheticPIDBase = tddtest.SyntheticPIDBase

const timeoutLoadFixtureLeaf = tddtest.TimeoutLoadFixtureLeaf

type measuredCall = tddtest.MeasuredCall

var laneSource = tddtest.LaneSource

func baselineRepo(t *testing.T, path, before, after string) string {
	t.Helper()
	return tddtest.BaselineRepo(t, path, before, after)
}

func commitAll(t *testing.T, root string) { t.Helper(); tddtest.CommitAll(t, root) }

func fakeRun(passed bool, output string) SuiteRunner {
	return tddtest.FakeRun[Runner](SuiteResult{Passed: passed, Output: output})
}

func foreignChainSample(leaf int, name string, pctOneCore, cpuHours float64) []procSample {
	return tddtest.ForeignChainSample(leaf, name, pctOneCore, cpuHours, maxAncestryDepth, newProcSample)
}

func gateLineFields(line string) (stage, verdict string, ok bool) {
	e, ok := parseGateLine(line)
	return e.Stage, e.Verdict, ok
}

func gateLogText(t *testing.T, cfg string) string { t.Helper(); return tddtest.GateLogText(t, cfg) }

func gitAddAll(t *testing.T, root string) { t.Helper(); tddtest.GitAddAll(t, root) }

func gitOutT(t *testing.T, dir string, args ...string) string {
	t.Helper()
	return tddtest.GitOutT(t, dir, args...)
}

func isSuiteVerb(r Runner) bool {
	if r.Cmd != "cargo" || len(r.Args) == 0 {
		return false
	}
	return r.Args[0] == "test" || (len(r.Args) > 1 && r.Args[0] == "nextest" && r.Args[1] == "run")
}

func makeMeasureRepo(t *testing.T, lane map[string]string) (root, base string) {
	t.Helper()
	return tddtest.MakeMeasureRepo(t, setMutantsJobsForTest, lane)
}

func mkGoModule(t *testing.T) string { t.Helper(); return tddtest.MkGoModule(t) }

func mkProject(t *testing.T, markers ...string) string {
	t.Helper()
	return tddtest.MkProject(t, markers...)
}

func mustWrite(t *testing.T, path, content string) { t.Helper(); tddtest.MustWrite(t, path, content) }

func newProcSample(pid, ppid int, name string, pctOneCore, cpuHours float64, creation uint64) procSample {
	return procSample{PID: pid, PPID: ppid, Name: name, PctOneCore: pctOneCore, CPUHours: cpuHours, Creation: creation}
}

func outcomeFields(m MutantOutcome) tddtest.Outcome {
	return tddtest.Outcome{Name: mutantLineOf(m.File, m.Line, m.Col, m.Mutation), Package: m.Package, File: m.File, Line: m.Line, Col: m.Col, Status: m.Status}
}

func postPayload(tool, file string) []byte { return tddtest.PostPayload(tool, file) }

func readFileString(t *testing.T, path string) string {
	t.Helper()
	return tddtest.ReadFileString(t, path)
}

func requireLoggedVerdict(t *testing.T, cfg, verdict string) {
	t.Helper()
	tddtest.RequireLoggedVerdict(t, cfg, verdict, gateLineFields)
}

func stubMutantsExec(t *testing.T, reply func(ctx context.Context, n int, c measuredCall) (int, error)) *[]measuredCall {
	t.Helper()
	return tddtest.StubMutantsExec(t, SetMutantsExecForTest, setMutantsListCountForTest, reply)
}

func withIsolatedBuildLock(t *testing.T) {
	t.Helper()
	tddtest.IsolateBuildLock(t, setBuildLockPathOverride, SetPostEditLockWaitForTest, SetPrecommitLockWait)
}

func writeMeasureBase(t *testing.T, root string) { t.Helper(); tddtest.WriteMeasureBase(t, root) }

func writeOutcomes(t *testing.T, root string, mutants ...MutantOutcome) {
	t.Helper()
	tddtest.WriteOutcomes(t, cargoMutantsOutcomesPath(mutantsShardDir(root, 0)), outcomeFields, mutants...)
}
