// Code generated by tddsplit. DO NOT EDIT.

package smell

import (
	suite "github.com/aphrollo/aphrollo-tools/internal/tdd/suite"
)

func zigTestLines(p0 string) map[int]bool { return suite.ZigTestLines(p0) }
