// Code generated by tddsplit. DO NOT EDIT.

package smell

import (
	core "github.com/aphrollo/aphrollo-tools/internal/tdd/core"
)

const Allow = core.Allow

const Block = core.Block

const Warn = core.Warn

type Action = core.Action

type Decision = core.Decision

func maskTokens(p0 string, p1 bool, p2 bool, p3 bool) string { return core.MaskTokens(p0, p1, p2, p3) }
