// Code generated by tddsplit. DO NOT EDIT.

package smell

import (
	suite "github.com/aphrollo/aphrollo-tools/internal/tdd/suite"
)

func applyEdit(p0 string, p1 string, p2 string, p3 bool) string {
	return suite.ApplyEdit(p0, p1, p2, p3)
}

func declaresTest(p0 string, p1 string) (bool, bool) { return suite.DeclaresTest(p0, p1) }
