// Code generated by tddsplit. DO NOT EDIT.

package smell

const CommitPhase = commitPhase

const EditPhase = editPhase

type Lang = lang

type Phase = phase

type Policy = policy

type PreToolUseInput = preToolUseInput

type View = view

var OracleSmells = oracleSmells

var SourcePolicies = sourcePolicies

var SuppressionPolicies = suppressionPolicies

var TestOracleWarnings = testOracleWarnings

var TestPolicies = testPolicies

func AddedLines(p0 string, p1 string) map[int]bool { return addedLines(p0, p1) }

func ConcatPolicies(p0 ...[]policy) []policy { return concatPolicies(p0...) }

func EditImages(p0 preToolUseInput, p1 string) (string, string) { return editImages(p0, p1) }

func EvaluateAdded(p0 string, p1 map[int]bool, p2 lang, p3 []policy, p4 phase) Decision {
	return evaluateAdded(p0, p1, p2, p3, p4)
}

func IntersectLines(p0 map[int]bool, p1 map[int]bool) map[int]bool { return intersectLines(p0, p1) }

func LangOf(p0 string) lang { return langOf(p0) }

func NewView(p0 string, p1 lang) view { return newView(p0, p1) }

func QualityNotesOn(p0 string, p1 string, p2 map[int]bool) []string {
	return qualityNotesOn(p0, p1, p2)
}
