// Code generated by tddsplit. DO NOT EDIT.

package gitx

import (
	io "io"
)

const RealGitEnv = realGitEnv

const ReflogActionEnv = reflogActionEnv

const StagedDiffFilter = stagedDiffFilter

type MergeTip = mergeTip

func BranchIsTrunk(p0 string, p1 string) bool { return branchIsTrunk(p0, p1) }

func CleanGitEnv() []string { return cleanGitEnv() }

func Git(p0 string, p1 ...string) (string, error) { return git(p0, p1...) }

func GitApply(p0 string, p1 string) error { return gitApply(p0, p1) }

func GitBinary() string { return gitBinary() }

func GitOut(p0 string, p1 ...string) string { return gitOut(p0, p1...) }

func GitStaged(p0 string, p1 []string) (string, error) { return gitStaged(p0, p1) }

func GitStdin(p0 string, p1 io.Reader, p2 ...string) (string, error) { return gitStdin(p0, p1, p2...) }

func LastNonEmptyLine(p0 string) string { return lastNonEmptyLine(p0) }

func MergeInProgressRef(p0 string) string { return mergeInProgressRef(p0) }

func MergeTipOf(p0 string) (mergeTip, bool) { return mergeTipOf(p0) }

func RevTree(p0 string, p1 string) (string, bool) { return revTree(p0, p1) }

func StagedBaseRev(p0 string) string { return stagedBaseRev(p0) }

func StagedFiles(p0 string) []string { return stagedFiles(p0) }

func StagedFilesErr(p0 string) ([]string, error) { return stagedFilesErr(p0) }

func TrunkSyncTip(p0 string) (string, bool) { return trunkSyncTip(p0) }
