// Code generated by tddsplit. DO NOT EDIT.

package escape

import (
	host "github.com/aphrollo/aphrollo-tools/internal/integrate/host"
	suite "github.com/aphrollo/aphrollo-tools/internal/tdd/suite"
	time "time"
)

const Green = suite.Green

type suiteProofLedger = suite.SuiteProofLedger

var ghAvailable = suite.GhAvailable

var suiteRanGreen = suite.SuiteRanGreen

func ExtractFailingTests(p0 string) []string { return suite.ExtractFailingTests(p0) }

func cargoAphrolloPackages(p0 string, p1 string) []string { return suite.CargoAphrolloPackages(p0, p1) }

func cargoAphrolloString(p0 string, p1 string) (string, bool) {
	return suite.CargoAphrolloString(p0, p1)
}

func consumeProvenSuiteStamp(p0 string) string { return suite.ConsumeProvenSuiteStamp(p0) }

func diffHeaderPath(p0 string) (string, bool) { return suite.DiffHeaderPath(p0) }

func fixtureLawFromPath(p0 string) (string, bool) { return suite.FixtureLawFromPath(p0) }

func gateSuiteProof() *suiteProofLedger { return suite.GateSuiteProof() }

func gcStatePath(p0 string) string { return suite.GcStatePath(p0) }

func gitHubHost(p0 string, p1 time.Duration) host.Host { return suite.GitHubHost(p0, p1) }

func gitRead(p0 string, p1 ...string) (string, error) { return suite.GitRead(p0, p1...) }

func hasGitHubRemote(p0 string) bool { return suite.HasGitHubRemote(p0) }

func stampProvenSuite(p0 string) { suite.StampProvenSuite(p0) }

func stampTree(p0 string, p1 string) { suite.StampTree(p0, p1) }
