// Code generated by tddsplit. DO NOT EDIT.

package escape

import (
	core "github.com/aphrollo/aphrollo-tools/internal/tdd/core"
)

const Source = core.Source

const Test = core.Test

type Kind = core.Kind

type gateEntry = core.GateEntry

func ClassifyFile(p0 string) Kind { return core.ClassifyFile(p0) }

func GateLogPath() string { return core.GateLogPath() }

func StateDir() string { return core.StateDir() }

func aphrolloTomlString(p0 string, p1 string) (string, bool) { return core.AphrolloTomlString(p0, p1) }

func dedupeSorted(p0 []string) []string { return core.DedupeSorted(p0) }

func firstLine(p0 string) string { return core.FirstLine(p0) }

func fitRunes(p0 string, p1 int) string { return core.FitRunes(p0, p1) }

func normalizeRepoSpelling(p0 string) string { return core.NormalizeRepoSpelling(p0) }

func parseGateLine(p0 string) (gateEntry, bool) { return core.ParseGateLine(p0) }

func quotedWords(p0 string) []string { return core.QuotedWords(p0) }

func repoStateKey(p0 string) string { return core.RepoStateKey(p0) }

func writeFileAtomic(p0 string, p1 []byte) error { return core.WriteFileAtomic(p0, p1) }
