// Code generated by tddsplit. DO NOT EDIT.

package escape

import (
	gitx "github.com/aphrollo/aphrollo-tools/internal/tdd/gitx"
)

type mergeTip = gitx.MergeTip

func RepoRoot(p0 string) string { return gitx.RepoRoot(p0) }

func git(p0 string, p1 ...string) (string, error) { return gitx.Git(p0, p1...) }

func gitOut(p0 string, p1 ...string) string { return gitx.GitOut(p0, p1...) }

func lastNonEmptyLine(p0 string) string { return gitx.LastNonEmptyLine(p0) }

func mergeTipOf(p0 string) (mergeTip, bool) { return gitx.MergeTipOf(p0) }

func revTree(p0 string, p1 string) (string, bool) { return gitx.RevTree(p0, p1) }
