// Code generated by tddsplit. DO NOT EDIT.

package escape

import (
	core "github.com/aphrollo/aphrollo-tools/internal/tdd/core"
)

func ReadEvents(p0 string) []Event { return core.ReadEvents(p0) }
