// Code generated by tddsplit. DO NOT EDIT.

package escape

import (
	io "io"
	time "time"
)

const EscapeDedupeWindow = escapeDedupeWindow

const GateNotesRef = gateNotesRef

const IssueFingerprintKey = issueFingerprintKey

func AppendEscape(p0 EscapeRecord) error { return appendEscape(p0) }

func CommitCarriesGreenGate(p0 string, p1 string) bool { return commitCarriesGreenGate(p0, p1) }

func Contains(p0 []string, p1 string) bool { return contains(p0, p1) }

func EscapeFingerprint(p0 string, p1 EscapeOptions) string { return escapeFingerprint(p0, p1) }

func EscapeIssueBody(p0 EscapeRecord) string { return escapeIssueBody(p0) }

func FormatFloat(p0 float64) string { return formatFloat(p0) }

func GateGreenNote(p0 string) string { return gateGreenNote(p0) }

func GreenSuiteStampFile(p0 string) string { return greenSuiteStampFile(p0) }

func IsUnacceptedSurvivorRejection(p0 string) bool { return isUnacceptedSurvivorRejection(p0) }

func MaybeWeeklyDigest(p0 time.Time) string { return maybeWeeklyDigest(p0) }

func MutantsOutcome(p0 string) (string, string, bool) { return mutantsOutcome(p0) }

func NoteSuiteGreen() { noteSuiteGreen() }

func RecordEscapeOnce(p0 string, p1 EscapeOptions, p2 io.Writer) (EscapeRecord, bool) {
	return recordEscapeOnce(p0, p1, p2)
}

func ResetLabelCache() { resetLabelCache() }

func StampGreenSuite(p0 string) { stampGreenSuite(p0) }

func SyncClosedEscapes(p0 string) int { return syncClosedEscapes(p0) }
