// Code generated by tddsplit. DO NOT EDIT.

package escape

import (
	tddtest "github.com/aphrollo/aphrollo-tools/internal/tdd/internal/tddtest"
	testing "testing"
	time "time"
)

func commitWithGreenGateNote(t *testing.T, root, subject string) {
	t.Helper()
	tddtest.CommitWithGreenGateNote(t, root, subject, stampProvenSuite, PostCommit)
}

func gateLines(ts time.Time, entries ...string) string { return tddtest.GateLines(ts, entries...) }

func ghArgv(t *testing.T, log string) string { t.Helper(); return tddtest.GhArgv(t, log) }

func gitDo(t *testing.T, dir string, args ...string) { t.Helper(); tddtest.GitDo(t, dir, args...) }

func gitValue(t *testing.T, dir string, args ...string) string {
	t.Helper()
	return tddtest.GitValue(t, dir, args...)
}

func makeGitHubRepo(t *testing.T) string { t.Helper(); return tddtest.MakeGitHubRepo(t) }

func makeGoRepo(t *testing.T) string { t.Helper(); return tddtest.MakeGoRepo(t) }

func readEscapes(t *testing.T) []EscapeRecord {
	t.Helper()
	return tddtest.ReadEscapes[EscapeRecord](t, EscapeLogPath())
}

func stubGh(t *testing.T, stdout string) (argvLog string) {
	t.Helper()
	return tddtest.StubGh(t, stdout)
}

func stubGhScript(t *testing.T, responses map[string]string) (argvLog string) {
	t.Helper()
	return tddtest.StubGhScript(t, responses)
}

func write(t *testing.T, dir, rel, content string) { t.Helper(); tddtest.Write(t, dir, rel, content) }
