name = "shell"
extensions = [".sh"]
code_escape = true
view = 2

# `#` opens a comment only at the start of a word.
[comments]
line = ["#"]
line_word_start = true

[string.single]
open = "'"
multiline = true

[string.double]
open = '"'
escape = "backslash"
multiline = true
