// Code generated by tddsplit. DO NOT EDIT.

package install

import (
	lock "github.com/aphrollo/aphrollo-tools/internal/tdd/lock"
)

func cargoWorkspaceRoot(p0 string) string { return lock.CargoWorkspaceRoot(p0) }

func ensureSharedDir(p0 string) error { return lock.EnsureSharedDir(p0) }

func lockDir() string { return lock.LockDir() }
