// Code generated by tddsplit. DO NOT EDIT.

package install

import (
	mutation "github.com/aphrollo/aphrollo-tools/internal/tdd/mutation"
)

func SetFreeSpaceForTest(p0 int, p1 bool) func() { return mutation.SetFreeSpaceForTest(p0, p1) }
