// Code generated by tddsplit. DO NOT EDIT.

package install

import (
	postedit "github.com/aphrollo/aphrollo-tools/internal/tdd/postedit"
)

const DefaultPostEditTimeout = postedit.DefaultPostEditTimeout

const primaryBranch = postedit.PrimaryBranch

func PrimaryCheckoutState(p0 string) (string, string, bool) { return postedit.PrimaryCheckoutState(p0) }

func PrimaryMergeOnly(p0 string) (string, bool) { return postedit.PrimaryMergeOnly(p0) }
