// Code generated by tddsplit. DO NOT EDIT.

package install

import (
	mutation "github.com/aphrollo/aphrollo-tools/internal/tdd/mutation"
)

type DoctorCheck = mutation.DoctorCheck

type DoctorInput = mutation.DoctorInput

type MutantsConfig = mutation.MutantsConfig

func ReadMutantsConfig(p0 string) (MutantsConfig, error) { return mutation.ReadMutantsConfig(p0) }

func doctorDiskSpace(p0 DoctorInput) DoctorCheck { return mutation.DoctorDiskSpace(p0) }
