// Code generated by tddsplit. DO NOT EDIT.

package install

import (
	core "github.com/aphrollo/aphrollo-tools/internal/tdd/core"
)

type Runner = core.Runner

type gateEntry = core.GateEntry

func GateLogPath() string { return core.GateLogPath() }

func parseGateLine(p0 string) (gateEntry, bool) { return core.ParseGateLine(p0) }
