// Code generated by tddsplit. DO NOT EDIT.

package install

import (
	core "github.com/aphrollo/aphrollo-tools/internal/tdd/core"
	time "time"
)

const CmdName = core.CmdName

const LegacyCmdName = core.LegacyCmdName

type sessionState = core.SessionState

var errNoSession = core.ErrNoSession

func AppendGateLog(p0 string, p1 string, p2 string, p3 string, p4 time.Duration) {
	core.AppendGateLog(p0, p1, p2, p3, p4)
}

func claudeConfigDir() string { return core.ClaudeConfigDir() }

func loadSession(p0 string) (*sessionState, string) { return core.LoadSession(p0) }

func samePath(p0 string, p1 string) bool { return core.SamePath(p0, p1) }

func shellPath(p0 string) string { return core.ShellPath(p0) }

func sortStrings(p0 []string) { core.SortStrings(p0) }
