// Code generated by tddsplit. DO NOT EDIT.

package install

import (
	precommit "github.com/aphrollo/aphrollo-tools/internal/tdd/precommit"
)

func SetLinterVersionForTest(p0 func(dir string) string) func() {
	return precommit.SetLinterVersionForTest(p0)
}

func SetLookLinterForTest(p0 func() bool) func() { return precommit.SetLookLinterForTest(p0) }
