// Code generated by tddsplit. DO NOT EDIT.

package install

import (
	suite "github.com/aphrollo/aphrollo-tools/internal/tdd/suite"
)

func cargoAphrolloFlag(p0 string, p1 string) bool { return suite.CargoAphrolloFlag(p0, p1) }

func cargoClippyCleanPackages(p0 string) []string { return suite.CargoClippyCleanPackages(p0) }

func gitRead(p0 string, p1 ...string) (string, error) { return suite.GitRead(p0, p1...) }
