// Code generated by tddsplit. DO NOT EDIT.

package install

import (
	suite "github.com/aphrollo/aphrollo-tools/internal/tdd/suite"
)

const InfraFailed = suite.InfraFailed

const bashSuiteVerdictFreshFor = suite.BashSuiteVerdictFreshFor

const suiteOutputCap = suite.SuiteOutputCap

type SuiteResult = suite.SuiteResult

type SuiteRunner = suite.SuiteRunner

type suiteOutputRecord = suite.SuiteOutputRecord

func RetainedSuiteOutput(p0 string) (string, error) { return suite.RetainedSuiteOutput(p0) }

func narrowToStaged(p0 Runner, p1 string, p2 []string) (Runner, bool) {
	return suite.NarrowToStaged(p0, p1, p2)
}

func retainSuiteOutput(p0 string, p1 string, p2 string, p3 string, p4 SuiteResult) {
	suite.RetainSuiteOutput(p0, p1, p2, p3, p4)
}

func writeSuiteOutputRecord(p0 suiteOutputRecord) error { return suite.WriteSuiteOutputRecord(p0) }
