// Code generated by tddsplit. DO NOT EDIT.

package install

import (
	postedit "github.com/aphrollo/aphrollo-tools/internal/tdd/postedit"
)

const DeferredAbandoned = postedit.DeferredAbandoned

const maxBashSnapshots = postedit.MaxBashSnapshots

type DeferredJob = postedit.DeferredJob

type PhaseOutcome = postedit.PhaseOutcome

func EnableDeferredPhases(p0 bool) { postedit.EnableDeferredPhases(p0) }

func PostBash(p0 []byte, p1 SuiteRunner) string { return postedit.PostBash(p0, p1) }

func PostEdit(p0 []byte, p1 SuiteRunner) string { return postedit.PostEdit(p0, p1) }

func PreBash(p0 []byte) { postedit.PreBash(p0) }

func SetSpawnPhaseForTest(p0 func(j DeferredJob) (DeferredJob, bool)) func() {
	return postedit.SetSpawnPhaseForTest(p0)
}

func denyNarrowedRerunReason(p0 string, p1 gateEntry) string {
	return postedit.DenyNarrowedRerunReason(p0, p1)
}

func loadDeferredJob(p0 string, p1 string) (DeferredJob, bool) {
	return postedit.LoadDeferredJob(p0, p1)
}

func saveDeferredJob(p0 DeferredJob) { postedit.SaveDeferredJob(p0) }

func writePhaseResult(p0 string, p1 PhaseOutcome) { postedit.WritePhaseResult(p0, p1) }
