// Code generated by tddsplit. DO NOT EDIT.

package install

import (
	precommit "github.com/aphrollo/aphrollo-tools/internal/tdd/precommit"
)

const golangciLint = precommit.GolangciLint

func linterVersion(p0 string) string { return precommit.LinterVersion(p0) }

func lookLinter() bool { return precommit.LookLinter() }

func pinnedLinterVersion(p0 string) string { return precommit.PinnedLinterVersion(p0) }
