// Code generated by tddsplit. DO NOT EDIT.

package install

import (
	escape "github.com/aphrollo/aphrollo-tools/internal/tdd/escape"
	io "io"
	time "time"
)

const EscapeKind = escape.EscapeKind

type EscapeOptions = escape.EscapeOptions

type EscapeRecord = escape.EscapeRecord

type IssueOptions = escape.IssueOptions

func EscapeLogPath() string { return escape.EscapeLogPath() }

func IssueLabels(p0 string) []string { return escape.IssueLabels(p0) }

func ListEscapes(p0 io.Writer, p1 bool) { escape.ListEscapes(p0, p1) }

func OpenEscapes() (int, time.Duration) { return escape.OpenEscapes() }

func OpenIssue(p0 IssueOptions) (string, int, error) { return escape.OpenIssue(p0) }

func RecordEscape(p0 EscapeOptions, p1 io.Writer) (EscapeRecord, error) {
	return escape.RecordEscape(p0, p1)
}

func SyncEscapes(p0 string, p1 io.Writer) (int, error) { return escape.SyncEscapes(p0, p1) }

func appendEscape(p0 EscapeRecord) error { return escape.AppendEscape(p0) }

func escapeIssueBody(p0 EscapeRecord) string { return escape.EscapeIssueBody(p0) }

func resetLabelCache() { escape.ResetLabelCache() }

func syncClosedEscapes(p0 string) int { return escape.SyncClosedEscapes(p0) }
