// Code generated by tddsplit. DO NOT EDIT.

package install

var GitGateHooks = gitGateHooks

var PerRepoHooks = perRepoHooks

func BinShim(p0 string, p1 string, p2 string) string { return binShim(p0, p1, p2) }

func EffectiveReplyStyle(p0 *sessionState) string { return effectiveReplyStyle(p0) }

func ReplyStyleFor(p0 string) string { return replyStyleFor(p0) }

func ResolvedTDDSkillPath() (string, bool) { return resolvedTDDSkillPath() }

func SetReplyStyle(p0 string, p1 string) error { return setReplyStyle(p0, p1) }

func Shim(p0 string, p1 string) string { return shim(p0, p1) }
