// Code generated by tddsplit. DO NOT EDIT.

package install

import (
	tddtest "github.com/aphrollo/aphrollo-tools/internal/tdd/internal/tddtest"
	testing "testing"
	time "time"
)

var deferredPhases = tddtest.Phases[DeferredJob, PhaseOutcome]{
	SetSpawn: SetSpawnPhaseForTest,
	Start: func(j DeferredJob, pid int, started time.Time) DeferredJob {
		j.PID = pid
		j.Started = started
		saveDeferredJob(j)
		j, _ = loadDeferredJob(j.Session, j.Project)
		return j
	},
	Files:       func(j DeferredJob) (string, string) { return j.Log, j.Result },
	WriteResult: writePhaseResult,
	Enable:      EnableDeferredPhases,
}

func commitInitial(t *testing.T, repo string) { t.Helper(); tddtest.CommitInitial(t, repo) }

func fakePhases(t *testing.T, outcomes ...*PhaseOutcome) *[]DeferredJob {
	t.Helper()
	return tddtest.FakePhases(t, deferredPhases, outcomes...)
}

func fakeRun(passed bool, output string) SuiteRunner {
	return tddtest.FakeRun[Runner](SuiteResult{Passed: passed, Output: output})
}

func gateLineFields(line string) (stage, verdict string, ok bool) {
	e, ok := parseGateLine(line)
	return e.Stage, e.Verdict, ok
}

func gateLogContent(t *testing.T) string { t.Helper(); return tddtest.GateLogContent(t, GateLogPath()) }

func gitDo(t *testing.T, dir string, args ...string) { t.Helper(); tddtest.GitDo(t, dir, args...) }

func gitInit(t *testing.T, dir string) { t.Helper(); tddtest.GitInit(t, dir) }

func makeGoRepo(t *testing.T) string { t.Helper(); return tddtest.MakeGoRepo(t) }

func mkProject(t *testing.T, markers ...string) string {
	t.Helper()
	return tddtest.MkProject(t, markers...)
}

func mustWrite(t *testing.T, path, content string) { t.Helper(); tddtest.MustWrite(t, path, content) }

func postPayload(tool, file string) []byte { return tddtest.PostPayload(tool, file) }

func primaryRepo(t *testing.T) (primary, linked string) { t.Helper(); return tddtest.PrimaryRepo(t) }

func requireLoggedVerdict(t *testing.T, cfg, verdict string) {
	t.Helper()
	tddtest.RequireLoggedVerdict(t, cfg, verdict, gateLineFields)
}

func runsAt(seen *[]Runner, root string) SuiteRunner {
	return tddtest.RecordRunner(seen, root, nil, SuiteResult{Passed: true})
}

func withFreeSpace(t *testing.T, gb int) {
	t.Helper()
	t.Cleanup(SetFreeSpaceForTest(gb, true))
}

func withLinter(t *testing.T, present bool) {
	t.Helper()
	t.Cleanup(SetLookLinterForTest(func() bool { return present }))
}

func withLinterVersion(t *testing.T, version string) {
	t.Helper()
	t.Cleanup(SetLinterVersionForTest(func(string) string { return version }))
}

func write(t *testing.T, dir, rel, content string) { t.Helper(); tddtest.Write(t, dir, rel, content) }
