// Code generated by tddsplit. DO NOT EDIT.

package gc

import (
	gitx "github.com/aphrollo/aphrollo-tools/internal/tdd/gitx"
)

func RepoRoot(p0 string) string { return gitx.RepoRoot(p0) }

func cleanGitEnv() []string { return gitx.CleanGitEnv() }

func git(p0 string, p1 ...string) (string, error) { return gitx.Git(p0, p1...) }
