// Code generated by tddsplit. DO NOT EDIT.

package gc

import (
	postedit "github.com/aphrollo/aphrollo-tools/internal/tdd/postedit"
	syscall "syscall"
	time "time"
)

const deferredJobMaxAge = postedit.DeferredJobMaxAge

func deferredDirPath() string { return postedit.DeferredDirPath() }

func detachedAttrs() *syscall.SysProcAttr { return postedit.DetachedAttrs() }

func gcDeferredJobFiles(p0 string, p1 time.Duration, p2 time.Time) []GCCandidate {
	return postedit.GcDeferredJobFiles(p0, p1, p2)
}
