// Code generated by tddsplit. DO NOT EDIT.

package gc

import (
	mutation "github.com/aphrollo/aphrollo-tools/internal/tdd/mutation"
)

func SetTargetDirOwnerForTest(p0 func(path string) (int, bool)) func() {
	return mutation.SetTargetDirOwnerForTest(p0)
}
