// Code generated by tddsplit. DO NOT EDIT.

package gc

import (
	lock "github.com/aphrollo/aphrollo-tools/internal/tdd/lock"
	time "time"
)

const buildSlotsEnv = lock.BuildSlotsEnv

type BuildSlot = lock.BuildSlot

func ReadBuildSlotOwnerPath(p0 string) string { return lock.ReadBuildSlotOwnerPath(p0) }

func SetLockDirForTest(p0 string) func() { return lock.SetLockDirForTest(p0) }

func SetPostEditLockWaitForTest(p0 time.Duration) func() { return lock.SetPostEditLockWaitForTest(p0) }

func SetPrecommitLockWait(p0 time.Duration) func() { return lock.SetPrecommitLockWait(p0) }

func TryAcquireBuildSlot(p0 string, p1 string, p2 string) (BuildSlot, func(), bool) {
	return lock.TryAcquireBuildSlot(p0, p1, p2)
}

func litterDirsFor(p0 string, p1 bool, p2 string) []string { return lock.LitterDirsFor(p0, p1, p2) }

func setBuildLockPathOverride(p0 string) func() { return lock.SetBuildLockPathOverride(p0) }

func sharedLockCandidates() []string { return lock.SharedLockCandidates() }

func sharedTargetLockPath(p0 string) string { return lock.SharedTargetLockPath(p0) }
