// Code generated by tddsplit. DO NOT EDIT.

package gc

import (
	mutation "github.com/aphrollo/aphrollo-tools/internal/tdd/mutation"
	time "time"
)

const CoverCacheMaxAge = mutation.CoverCacheMaxAge

const GCKindDepsMember = mutation.GCKindDepsMember

const GCKindDepsThirdParty = mutation.GCKindDepsThirdParty

const GCKindGateDir = mutation.GCKindGateDir

const GCKindGatePRMerge = mutation.GCKindGatePRMerge

const GCKindGoTmp = mutation.GCKindGoTmp

const GCKindIncremental = mutation.GCKindIncremental

const GCKindMutants = mutation.GCKindMutants

const GCKindMutantsTarget = mutation.GCKindMutantsTarget

const GCKindMutantsTemp = mutation.GCKindMutantsTemp

const GCKindOrphanWorktree = mutation.GCKindOrphanWorktree

const GCKindStrayTarget = mutation.GCKindStrayTarget

const GCKindTempLitter = mutation.GCKindTempLitter

const mutantsCopyActiveWindow = mutation.MutantsCopyActiveWindow

type GCCandidate = mutation.GCCandidate

type GCKind = mutation.GCKind

func CoverCacheDir(p0 string) string { return mutation.CoverCacheDir(p0) }

func dirNewestAndSize(p0 string) (time.Time, int64) { return mutation.DirNewestAndSize(p0) }

func gcTempTargetDirs(p0 []string, p1 time.Time) []GCCandidate {
	return mutation.GcTempTargetDirs(p0, p1)
}

func measureTempDir(p0 string) string { return mutation.MeasureTempDir(p0) }

func mutantsRunHeld() bool { return mutation.MutantsRunHeld() }

func pathKey(p0 string) string { return mutation.PathKey(p0) }

func proveAreaHeld(p0 string) bool { return mutation.ProveAreaHeld(p0) }

func targetDirOwnerFn(p0 string) (int, bool) { return mutation.TargetDirOwnerFn(p0) }
