// Code generated by tddsplit. DO NOT EDIT.

package gc

import (
	postedit "github.com/aphrollo/aphrollo-tools/internal/tdd/postedit"
	time "time"
)

type DeferredJob = postedit.DeferredJob

func SetKillDeferredForTest(p0 func(j DeferredJob)) func() {
	return postedit.SetKillDeferredForTest(p0)
}

func SetProcessStartTimeForTest(p0 func(pid int) (time.Time, bool)) func() {
	return postedit.SetProcessStartTimeForTest(p0)
}

func deferredJobPath(p0 string, p1 string) string { return postedit.DeferredJobPath(p0, p1) }

func killLivePID(p0 string) { postedit.KillLivePID(p0) }

func loadDeferredJob(p0 string, p1 string) (DeferredJob, bool) {
	return postedit.LoadDeferredJob(p0, p1)
}

func resetDeferredSweepForTest() { postedit.ResetDeferredSweepForTest() }

func saveDeferredJob(p0 DeferredJob) { postedit.SaveDeferredJob(p0) }

func sweepDeferredJobs(p0 time.Time) int { return postedit.SweepDeferredJobs(p0) }
