// Code generated by tddsplit. DO NOT EDIT.

package gc

import (
	core "github.com/aphrollo/aphrollo-tools/internal/tdd/core"
	exec "os/exec"
	time "time"
)

const CmdName = core.CmdName

func StateDir() string { return core.StateDir() }

func TryAcquireFileLock(p0 string) (func(), bool) { return core.TryAcquireFileLock(p0) }

func formatBytes(p0 int64) string { return core.FormatBytes(p0) }

func formatDays(p0 time.Duration) string { return core.FormatDays(p0) }

func pidRunningFn(p0 int) bool { return core.PidRunningFn(p0) }

func silentStdio(p0 *exec.Cmd) func() { return core.SilentStdio(p0) }

func sortStrings(p0 []string) { core.SortStrings(p0) }

func writeFileAtomic(p0 string, p1 []byte) error { return core.WriteFileAtomic(p0, p1) }
