// Code generated by tddsplit. DO NOT EDIT.

package gc

import (
	lock "github.com/aphrollo/aphrollo-tools/internal/tdd/lock"
)

type BuildLockOwner = lock.BuildLockOwner

func GoTmpRootDir(p0 string) string { return lock.GoTmpRootDir(p0) }

func ReadBuildSlotOwner(p0 string) (BuildLockOwner, bool) { return lock.ReadBuildSlotOwner(p0) }

func ResolveCargoTargetDir(p0 string) string { return lock.ResolveCargoTargetDir(p0) }

func csvPids(p0 string) []int { return lock.CsvPids(p0) }

func lockLitterDirs() []string { return lock.LockLitterDirs() }

func targetLockPath(p0 string) string { return lock.TargetLockPath(p0) }
