// Code generated by tddsplit. DO NOT EDIT.

package gc

import (
	suite "github.com/aphrollo/aphrollo-tools/internal/tdd/suite"
)

func gcStatePath(p0 string) string { return suite.GcStatePath(p0) }

func insideDir(p0 string, p1 string) bool { return suite.InsideDir(p0, p1) }
