// Code generated by tddsplit. DO NOT EDIT.

package gc

import (
	time "time"
)

func GcDue(p0 time.Time) bool { return gcDue(p0) }

func GcReportLine() string { return gcReportLine() }

func GcStaleGateDirs(p0 string) []GCCandidate { return gcStaleGateDirs(p0) }

func MaybeStartBackgroundGC(p0 string) { maybeStartBackgroundGC(p0) }

func StampGC(p0 time.Time) { stampGC(p0) }

func WriteGCReport(p0 int64, p1 int) { writeGCReport(p0, p1) }
