package undercover

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"testing"
)

// fakeGitHub answers GETs from a path->JSON map and records every PATCH.
type fakeGitHub struct {
	get     map[string]string
	patches map[string]string
}

func (f *fakeGitHub) Get(_ context.Context, path string) ([]byte, error) {
	if body, ok := f.get[path]; ok {
		return []byte(body), nil
	}
	if strings.Contains(path, "/comments?") || strings.Contains(path, "/commits?") {
		return []byte("[]"), nil
	}
	return nil, fmt.Errorf("unexpected GET %s", path)
}

func (f *fakeGitHub) Patch(_ context.Context, path string, fields map[string]string) error {
	if f.patches == nil {
		f.patches = map[string]string{}
	}
	f.patches[path] = fields["body"]
	return nil
}

func prJSON(title, body string) string {
	b, _ := json.Marshal(map[string]string{"title": title, "body": body})
	return string(b)
}

func commentsJSON(bodies map[int]string) string {
	var list []map[string]any
	for id, body := range bodies {
		list = append(list, map[string]any{"id": id, "body": body})
	}
	b, _ := json.Marshal(list)
	return string(b)
}

const (
	prPath       = "/repos/o/r/pulls/7"
	issueComPath = "/repos/o/r/issues/7/comments?per_page=100&page=1"
	reviewPath   = "/repos/o/r/pulls/7/comments?per_page=100&page=1"
	footer       = "\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)\n\nhttps://claude.ai/code/session_01"
)

var triggers = map[string]string{
	"pull_request":                `{"action":"edited","repository":{"full_name":"o/r"},"pull_request":{"number":7}}`,
	"issue_comment":               `{"action":"created","repository":{"full_name":"o/r"},"issue":{"number":7,"pull_request":{"url":"x"}},"comment":{"id":11}}`,
	"pull_request_review_comment": `{"action":"created","repository":{"full_name":"o/r"},"pull_request":{"number":7},"comment":{"id":21}}`,
}

// Every trigger reads the same three places on the PR: title and body, the
// issue comments and the review comments.
func TestCheckEvent_EveryTriggerStripsATrailingFooterEverywhereOnThePR(t *testing.T) {
	t.Parallel()
	for name, event := range triggers {
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			gh := &fakeGitHub{get: map[string]string{
				prPath:       prJSON("Fix the timer", "Fixes the retry timer."+footer),
				issueComPath: commentsJSON(map[int]string{11: "Looks right." + footer, 12: "Plain comment."}),
				reviewPath:   commentsJSON(map[int]string{21: "Nit: rename this.\n\n_Generated by [Claude Code](https://x.example)_"}),
			}}
			res, err := CheckEvent(context.Background(), []byte(event), New(nil), gh)
			if err != nil {
				t.Fatal(err)
			}
			if len(res.Failures) != 0 {
				t.Fatalf("a strippable footer failed the check: %q", res.Failures)
			}
			want := map[string]string{
				prPath:                          "Fixes the retry timer.",
				"/repos/o/r/issues/comments/11": "Looks right.",
				"/repos/o/r/pulls/comments/21":  "Nit: rename this.",
			}
			if len(gh.patches) != len(want) {
				t.Errorf("patches = %q, want %q", gh.patches, want)
			}
			for path, body := range want {
				if gh.patches[path] != body {
					t.Errorf("PATCH %s body = %q, want %q", path, gh.patches[path], body)
				}
			}
			if len(res.Stripped) != 3 {
				t.Errorf("stripped = %q, want one line per edited text", res.Stripped)
			}
		})
	}
}

func TestCheckEvent_AMidProseHitFailsWithoutAnEdit(t *testing.T) {
	t.Parallel()
	gh := &fakeGitHub{get: map[string]string{
		prPath:       prJSON("Fix the timer", "Claude wrote most of this.\n\nFixes the timer."+footer),
		issueComPath: commentsJSON(map[int]string{11: "ran under opus-5, looks fine"}),
	}}
	res, err := CheckEvent(context.Background(), []byte(triggers["pull_request"]), New(nil), gh)
	if err != nil {
		t.Fatal(err)
	}
	if len(gh.patches) != 0 {
		t.Errorf("a mid-prose hit was edited: %q", gh.patches)
	}
	joined := strings.Join(res.Failures, "\n")
	for _, want := range []string{"PR body", "Claude wrote most of this.", "issue comment 11", "ran under opus-5, looks fine"} {
		if !strings.Contains(joined, want) {
			t.Errorf("failures %q lack %q", joined, want)
		}
	}
}

func TestCheckEvent_ATitleHitFails(t *testing.T) {
	t.Parallel()
	gh := &fakeGitHub{get: map[string]string{prPath: prJSON("Claude's timer fix", "Fixes it.")}}
	res, err := CheckEvent(context.Background(), []byte(triggers["pull_request"]), New(nil), gh)
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Failures) != 1 || !strings.Contains(res.Failures[0], "PR title") {
		t.Errorf("failures = %q, want one naming the PR title", res.Failures)
	}
}

func TestCheckEvent_PassesOrdinaryTextWithoutAnEdit(t *testing.T) {
	t.Parallel()
	gh := &fakeGitHub{get: map[string]string{
		prPath:       prJSON("Fix cursor pagination", "The AIR filter and Cairo cases.\n\nSigned-off-by: Jane <j@example.com>"),
		issueComPath: commentsJSON(map[int]string{11: "a fable about the tortoise"}),
	}}
	res, err := CheckEvent(context.Background(), []byte(triggers["issue_comment"]), New(nil), gh)
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Failures) != 0 || len(gh.patches) != 0 || len(res.Stripped) != 0 {
		t.Errorf("ordinary text was judged: %+v, patches %q", res, gh.patches)
	}
}

// A comment on a plain issue has no PR title, body or review comments; its
// comments are still read.
func TestCheckEvent_ACommentOnAPlainIssueReadsOnlyItsComments(t *testing.T) {
	t.Parallel()
	gh := &fakeGitHub{get: map[string]string{
		"/repos/o/r/issues/9/comments?per_page=100&page=1": commentsJSON(map[int]string{31: "Filed." + footer}),
	}}
	event := `{"action":"created","repository":{"full_name":"o/r"},"issue":{"number":9},"comment":{"id":31}}`
	res, err := CheckEvent(context.Background(), []byte(event), New(nil), gh)
	if err != nil {
		t.Fatal(err)
	}
	if gh.patches["/repos/o/r/issues/comments/31"] != "Filed." || len(res.Failures) != 0 {
		t.Errorf("patches %q failures %q", gh.patches, res.Failures)
	}
}

func TestCheckEvent_FollowsCommentPages(t *testing.T) {
	t.Parallel()
	full := map[int]string{}
	for id := 1; id <= 100; id++ {
		full[id] = "ok"
	}
	gh := &fakeGitHub{get: map[string]string{
		prPath:       prJSON("t", "b"),
		issueComPath: commentsJSON(full),
		"/repos/o/r/issues/7/comments?per_page=100&page=2": commentsJSON(map[int]string{101: "Claude says hi"}),
	}}
	res, err := CheckEvent(context.Background(), []byte(triggers["pull_request"]), New(nil), gh)
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Failures) != 1 || !strings.Contains(res.Failures[0], "issue comment 101") {
		t.Errorf("failures = %q, want the comment on page 2", res.Failures)
	}
}

func TestCheckEvent_RefusesAnEventWithNoIssueOrPR(t *testing.T) {
	t.Parallel()
	if _, err := CheckEvent(context.Background(), []byte(`{"repository":{"full_name":"o/r"}}`), New(nil), &fakeGitHub{}); err == nil {
		t.Error("an event naming no issue or PR must be an error, not a pass")
	}
	if _, err := CheckEvent(context.Background(), []byte(`{"issue":{"number":3}}`), New(nil), &fakeGitHub{}); err == nil {
		t.Error("an event naming no repository must be an error, not a pass")
	}
}

// endlessGitHub answers every comment page full, the shape of a thread that
// never ends; the check still stops.
type endlessGitHub struct{ commentGets int }

func (e *endlessGitHub) Get(_ context.Context, path string) ([]byte, error) {
	if strings.HasPrefix(path, "/repos/o/r/issues/9/comments?") {
		e.commentGets++
		full := map[int]string{}
		for id := 1; id <= 100; id++ {
			full[id] = "ok"
		}
		return []byte(commentsJSON(full)), nil
	}
	return nil, fmt.Errorf("unexpected GET %s", path)
}

func (e *endlessGitHub) Patch(context.Context, string, map[string]string) error { return nil }

func TestCheckEvent_StopsAfterThePageCap(t *testing.T) {
	t.Parallel()
	gh := &endlessGitHub{}
	event := `{"repository":{"full_name":"o/r"},"issue":{"number":9},"comment":{"id":1}}`
	if _, err := CheckEvent(context.Background(), []byte(event), New(nil), gh); err != nil {
		t.Fatal(err)
	}
	if gh.commentGets != 30 {
		t.Errorf("read %d comment pages, want the cap of 30", gh.commentGets)
	}
}

func commitsJSON(commits ...[4]string) string {
	var list []map[string]any
	for _, c := range commits {
		an, ae, _ := strings.Cut(c[1], "|")
		cn, ce, _ := strings.Cut(c[2], "|")
		list = append(list, map[string]any{"sha": c[0], "commit": map[string]any{
			"author":    map[string]string{"name": an, "email": ae},
			"committer": map[string]string{"name": cn, "email": ce},
			"message":   c[3],
		}})
	}
	b, _ := json.Marshal(list)
	return string(b)
}

const prCommitsPath = "/repos/o/r/pulls/7/commits?per_page=100&page=1"

// A squash merge lists every commit author as a co-author, so a PR whose
// commits carry a tell leaks it into main however clean its text is.
func TestCheckEvent_FailsAPRCommitWhoseIdentityOrTrailerCarriesATell(t *testing.T) {
	t.Parallel()
	person, web := "Jane Doe|jane@example.com", "GitHub|noreply@github.com"
	for _, c := range []struct {
		commit [4]string
		field  string
	}{
		{[4]string{"aaaaaaaaaaaaaaaa", "Claude|noreply@anthropic.com", web, "Fix it"}, "author"},
		{[4]string{"bbbbbbbbbbbbbbbb", person, "Claude|noreply@anthropic.com", "Fix it"}, "committer"},
		{[4]string{"cccccccccccccccc", person, web, "Fix it\n\nCo-authored-by: Claude <noreply@anthropic.com>"}, "Co-authored-by trailer"},
	} {
		gh := &fakeGitHub{get: map[string]string{
			prPath:        prJSON("Fix the timer", "Fixes it."),
			prCommitsPath: commitsJSON([4]string{"0000000000000000", person, web, "Earlier work"}, c.commit),
		}}
		res, err := CheckEvent(context.Background(), []byte(triggers["pull_request"]), New(nil), gh)
		if err != nil {
			t.Fatal(err)
		}
		joined := strings.Join(res.Failures, "\n")
		for _, want := range []string{c.commit[0][:12], c.field, "noreply@anthropic.com"} {
			if !strings.Contains(joined, want) {
				t.Errorf("%s: failures %q lack %q", c.field, joined, want)
			}
		}
		if len(gh.patches) != 0 {
			t.Errorf("%s: a commit finding edited text: %q", c.field, gh.patches)
		}
	}
}

func TestCheckEvent_PassesPeoplesPRCommits(t *testing.T) {
	t.Parallel()
	gh := &fakeGitHub{get: map[string]string{
		prPath:        prJSON("Fix the timer", "Fixes it."),
		prCommitsPath: commitsJSON([4]string{"dddddddddddddddd", "Jane Doe|jane@example.com", "GitHub|noreply@github.com", "Fix it\n\nCo-authored-by: Claudia Airey <claudia@example.com>"}),
	}}
	res, err := CheckEvent(context.Background(), []byte(triggers["pull_request"]), New(nil), gh)
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Failures) != 0 {
		t.Errorf("people's commits failed: %q", res.Failures)
	}
}

// failingGitHub answers every GET from get and fails the one path in fail.
type failingGitHub struct {
	fakeGitHub
	fail string
}

func (f *failingGitHub) Get(ctx context.Context, path string) ([]byte, error) {
	if path == f.fail {
		return nil, fmt.Errorf("GET %s: 502 Bad Gateway", path)
	}
	return f.fakeGitHub.Get(ctx, path)
}

// A read that fails is not a thread that is clean: every one of the four
// reads surfaces its error rather than passing what it never saw.
func TestCheckEvent_AFailedReadIsAnErrorNotAPass(t *testing.T) {
	t.Parallel()
	for _, path := range []string{prPath, prCommitsPath, issueComPath, reviewPath} {
		gh := &failingGitHub{fakeGitHub: fakeGitHub{get: map[string]string{prPath: prJSON("t", "b")}}, fail: path}
		if _, err := CheckEvent(context.Background(), []byte(triggers["pull_request"]), New(nil), gh); err == nil || !strings.Contains(err.Error(), "502") {
			t.Errorf("GET %s failing: err = %v, want it surfaced", path, err)
		}
	}
}

// The CI check reads the guidance file and config paths as the names they are.
func TestCheckEvent_PassesTheGuidanceFileAndConfigPaths(t *testing.T) {
	t.Parallel()
	body := "Note lane file overlap in CLAUDE.md.\n\nThe skill is .claude/skills/x/SKILL.md; the brief is ~/.claude/agents/builder.md."
	gh := &fakeGitHub{get: map[string]string{
		prPath:        prJSON("Note lane file overlap and the green-PR freeze in CLAUDE.md (#891)", body),
		prCommitsPath: commitsJSON([4]string{"eeeeeeeeeeeeeeee", "Jane Doe|jane@example.com", "GitHub|noreply@github.com", "Edit CLAUDE.md\n\nSee .claude/skills/x/SKILL.md"}),
		issueComPath:  commentsJSON(map[int]string{11: "Updated ~/.claude/agents/builder.md to match CLAUDE.md"}),
	}}
	res, err := CheckEvent(context.Background(), []byte(triggers["pull_request"]), New(nil), gh)
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Failures) != 0 || len(gh.patches) != 0 {
		t.Errorf("ordinary names were judged: failures %q, patches %q", res.Failures, gh.patches)
	}
}
