package undercover

import (
	"reflect"
	"testing"
)

func TestStripFooter_RemovesATrailingToolFooterAndItsBlankLines(t *testing.T) {
	t.Parallel()
	body := "Fixes the retry timer.\n\nThe cursor case is covered.\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)\n\nhttps://claude.ai/code/session_01\n"
	kept, stripped := StripFooter(body, New(nil))
	if want := "Fixes the retry timer.\n\nThe cursor case is covered."; kept != want {
		t.Errorf("kept = %q, want %q", kept, want)
	}
	want := []string{"🤖 Generated with [Claude Code](https://claude.com/claude-code)", "https://claude.ai/code/session_01"}
	if !reflect.DeepEqual(stripped, want) {
		t.Errorf("stripped = %q, want %q", stripped, want)
	}
}

func TestStripFooter_RemovesToolTrailersAndAnItalicFooter(t *testing.T) {
	t.Parallel()
	for body, want := range map[string]string{
		"Looks right to me.\r\n\r\n_Generated by [Claude Code](https://x.example/claude)_":               "Looks right to me.",
		"Fix it.\n\nSigned-off-by: Jane <j@example.com>\nCo-Authored-By: Claude <noreply@anthropic.com>": "Fix it.\n\nSigned-off-by: Jane <j@example.com>",
		"Fix it.\n\n---\n\nClaude-Session: https://claude.ai/code/session_02":                            "Fix it.",
	} {
		if kept, stripped := StripFooter(body, New(nil)); kept != want || len(stripped) == 0 {
			t.Errorf("StripFooter(%q) = %q (stripped %q), want %q", body, kept, stripped, want)
		}
	}
}

// Only a footer line that is BOTH footer-shaped and a tell goes: an ordinary
// trailer stays, and a tell in prose is the caller's failure, never an edit.
func TestStripFooter_LeavesProseAndOrdinaryTrailersAlone(t *testing.T) {
	t.Parallel()
	for _, body := range []string{
		"Fix it.\n\nSigned-off-by: Jane <j@example.com>",
		"Fix it.\n\nClaude wrote most of this.",
		"Fix it.\n\nsee https://example.com/docs",
		"Generated with protoc.\n",
		"Fix it.\n\nNote: this also fixes the Claude Code compatibility shim",
		"Fix it.\n\nSee: https://example.com/claude",
		"",
	} {
		if kept, stripped := StripFooter(body, New(nil)); kept != body || len(stripped) != 0 {
			t.Errorf("StripFooter(%q) = %q (stripped %q), want it untouched", body, kept, stripped)
		}
	}
}

// The strip stops at the first line from the bottom that is not a stripped
// footer, so a tell above ordinary prose stays for the caller to refuse.
func TestStripFooter_StopsAtTheFirstLineItCannotStrip(t *testing.T) {
	t.Parallel()
	body := "Fix it.\n\nCo-Authored-By: Claude <noreply@anthropic.com>\nThanks for the review.\n"
	if kept, stripped := StripFooter(body, New(nil)); kept != body || len(stripped) != 0 {
		t.Errorf("kept %q stripped %q, want the body untouched", kept, stripped)
	}
}

// A body that is nothing but a tool footer strips to nothing.
func TestStripFooter_ABodyThatIsOnlyAFooterStripsToNothing(t *testing.T) {
	t.Parallel()
	kept, stripped := StripFooter("Co-Authored-By: Claude <noreply@anthropic.com>\n", New(nil))
	if kept != "" || len(stripped) != 1 {
		t.Errorf("kept %q stripped %q, want nothing kept and the trailer stripped", kept, stripped)
	}
}
