// Package undercover holds the one list of tells every undercover check reads:
// the commit-msg gate, the identity check, the ref-name walls (git shim,
// pre-push hook, workspace verbs), the pre-post check on PR and issue text,
// and the CI job that reads what actually landed on GitHub.
//
// A repo opts in with `undercover = true`. Every check has zero false
// positives: a refusal of ordinary text or an ordinary name is a bug in the
// entry, not a cost of it, so each entry carries the ordinary strings it must
// pass beside the tells it must hit, and a test proves the whole table against
// them.
package undercover

import "regexp"

// Tell is one entry of the list.
type Tell struct {
	// Name is the label a refusal quotes and the gate log records.
	Name string
	// Line matches one line of prose; nil for a tell that only names carry.
	Line *regexp.Regexp
	// Scrubbed tells see the line after scrub has replaced the file names,
	// refs and paths that merely contain the word.
	Scrubbed bool
	// Tokens are the whole lowercase name tokens that carry the tell in a
	// ref name; empty for a prose-only tell.
	Tokens []string
	// Versioned makes a token count only when the NEXT token starts with a
	// digit: `opus-4` is a model, `opus` alone is a word.
	Versioned bool
	// Trailer entries alone judge a Co-authored-by line, and judge it by the
	// co-author's address: a person named like a product is ordinary.
	Trailer bool
	// Ident matches a git identity (`Name <address>`); nil for a tell no
	// identity carries. A name alone is never an identity tell.
	Ident *regexp.Regexp
	// Hit and Pass are the lines the entry must refuse and must let through;
	// RefHit and RefPass the same for ref names, IdentHit and IdentPass for
	// identities.
	Hit, Pass           []string
	RefHit, RefPass     []string
	IdentHit, IdentPass []string
}

// vendorAddressExpr is a tool vendor's mail address: any address at
// anthropic.com, and the noreply addresses the other tools commit with.
const vendorAddressExpr = `(?:(?:^|[<\s])[\w.+-]+@(?:[\w-]+\.)*anthropic\.com\b|\bnoreply@openai\.com\b|\bcursoragent@cursor\.com\b|\b\d+\+copilot@users\.noreply\.github\.com\b)`

// generatedWith is a footer line naming a tool as the author.
const generatedWith = `(?i)^[\W_]*generated\s+(?:with|by)\s+[\W_]*(?:claude|copilot|chatgpt|(?:an?\s+)?(?:ai|code|coding)\s+assistant|an?\s+ai\b|ai\b)`

// vendorAddress matches one, case-insensitively.
const vendorAddress = `(?i)` + vendorAddressExpr

// Tells is the list, most specific entry first, so a trailer line is
// reported as a trailer rather than as the bare word it also contains.
//
// Audited out of the list that preceded it, each for a false positive its
// own fixtures could not avoid: `fable` (a fable about ...), `go/<x>` (the
// go/ directory, tools/go/analysis), the codenames Capybara (a Ruby test
// library, an animal) and Tengu (folklore), `AI assistant|generated|written`
// (a product that ships an AI assistant says so in its commits), a bare
// `Co-Authored-By:` (a human co-author is ordinary) and a bare `Generated
// with` (Generated with protoc). `claude-code` and `#claude-` are the claude
// entry's own hits.
var Tells = []Tell{
	{
		Name:    "co-author-trailer",
		Line:    regexp.MustCompile(`(?i)^\s*co-authored-by:.*` + vendorAddressExpr),
		Trailer: true,
		Hit: []string{
			"Co-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>",
			"Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>",
			"co-authored-by: Cursor Agent <cursoragent@cursor.com>",
		},
		Pass: []string{
			"Co-Authored-By: Jane Doe <jane@example.com>",
			"Co-authored-by: Cursor Smith <cursor.smith@example.com>",
			"Co-authored-by: Claude Monet <cm@example.com>",
			"Co-authored-by: Claude Shannon <cs@bell-labs.com>",
			"Explain the co-authored-by convention in the guide",
		},
	},
	{
		Name: "generated-with",
		Line: regexp.MustCompile(generatedWith),
		Hit: []string{
			"🤖 Generated with [Claude Code](https://claude.com/claude-code)",
			"_Generated by [Claude Code](https://example.com)_",
			"Generated with Copilot",
			"Generated with a code assistant",
			"Generated by AI",
		},
		Pass: []string{
			"Generated with protoc from api.proto",
			"Regenerated with cargo hakari after the rename",
			"Generated by a script in tools/",
			"Images generated by AI are labelled in the gallery",
			"Generated with the setup assistant's defaults",
			"Generated by airflow's scheduler",
		},
	},
	{
		Name:  "vendor-address",
		Line:  regexp.MustCompile(vendorAddress),
		Ident: regexp.MustCompile(vendorAddress),
		Hit: []string{
			"Reply-To: noreply@openai.com",
			"from cursoragent@cursor.com",
			"175728472+Copilot@users.noreply.github.com",
		},
		Pass: []string{
			"merge commits come from noreply@github.com",
			"send it to noreply@example.com",
			"12345+jane@users.noreply.github.com signed it",
		},
		IdentHit: []string{
			"Claude <noreply@anthropic.com> 1790373617 +0000",
			"Jane Doe <jane@anthropic.com>",
			"Copilot <175728472+Copilot@users.noreply.github.com> 1 +0000",
			"Cursor Agent <cursoragent@cursor.com>",
		},
		IdentPass: []string{
			"Claude Monet <claude.monet@example.com>",
			"Claude Shannon <cs@bell-labs.com> 1790373617 +0000",
			"Anthropic Fan <fan@anthropic.community.example>",
			"Opus Four <opus4@example.com>",
		},
	},
	{
		Name:     "claude",
		Line:     regexp.MustCompile(`(?i)\bclaude\b`),
		Scrubbed: true,
		Tokens:   []string{"claude"},
		Hit: []string{
			"Written with Claude's help",
			"Claude-Session: https://claude.ai/code/session_01",
			"see https://claude.ai/code/session_01",
			"claude-code ran the gate",
			"asked for #claude-review on this",
			"Merge lane/claude-md as Claude suggested",
		},
		Pass: []string{
			"Add the operating block to CLAUDE.md",
			"Note lane file overlap and the green-PR freeze in CLAUDE.md (#891)",
			"Move the code-quality skill under .claude/skills",
			"The rule lives in .claude/skills/x/SKILL.md",
			"See ~/.claude/agents/builder.md for the brief",
			"Merge lane/claude-md: project guide as tagged laws",
			"Merge lane/claudemd-lanes: lane rules in the guide",
			"Rename claudication_test to intermittent_test",
		},
		// A ref is judged token by token: claudemd is one file-derived token,
		// not the vendor word, and passes; claude-md splits into the bare
		// word, which the remote ref, the PR head and the merge subject would
		// then carry.
		RefHit:  []string{"claude/x", "lane/claude-fix", "Claude_x", "lane/fix.claude", "lane/claude-md"},
		RefPass: []string{"lane/cairo", "lane/claudication", "lane/air-fix", "lane/claudemd-lanes"},
	},
	{
		Name:   "anthropic",
		Line:   regexp.MustCompile(`(?i)\banthropics?\b`),
		Tokens: []string{"anthropic", "anthropics"},
		Hit: []string{
			"Anthropic tooling made this easier",
			"see anthropics/claude-code#12",
		},
		Pass: []string{
			"anthropomorphic naming in the fixtures",
			"anthropology dataset loader",
			"philanthropic donations table",
		},
		RefHit:  []string{"anthropic/x", "lane/anthropics-sync"},
		RefPass: []string{"lane/anthropology", "lane/philanthropic-fix"},
	},
	{
		Name: "model-name",
		// The spaced form counts only with a dotted version: "Sonnet 4.5" is
		// a model, "Sonnet 18" and "Opus 131" are literature and music.
		Line:      regexp.MustCompile(`(?i)\b(?:opus|sonnet|haiku|gpt)-\d|\b(?:opus|sonnet|haiku)\s\d+\.\d+`),
		Tokens:    []string{"opus", "sonnet", "haiku", "gpt"},
		Versioned: true,
		Hit: []string{
			"ran under opus-5",
			"sonnet-4 wrote the test",
			"haiku-3 drafted it",
			"compared against gpt-4o",
			"Sonnet 4.5 drafted the fixture",
			"ran under Opus 4.1",
		},
		Pass: []string{
			"Beethoven's Opus 27 in the fixture",
			"a haiku about rain",
			"Shakespeare's sonnet 18",
			"Shakespeare's Sonnet 18 in the reader",
			"Beethoven's Opus 131 quartet",
			"haiku 3 lines long",
			"GPT partition table support",
			"chatgptish naming",
			"rename opus-magnum",
		},
		RefHit:  []string{"lane/opus-4-fix", "sonnet-5", "lane/gpt-4-eval"},
		RefPass: []string{"lane/haiku-parser", "lane/gpt-partition", "lane/opus-magnum"},
	},
}
