// Code generated by tddsplit. DO NOT EDIT.

package suite

import (
	shell "github.com/aphrollo/aphrollo-tools/internal/tdd/shell"
)

func cdTarget(p0 []string) (string, bool) { return shell.CdTarget(p0) }

func resolveAgainst(p0 string, p1 string) string { return shell.ResolveAgainst(p0, p1) }

func shellSegments(p0 string) [][]string { return shell.ShellSegments(p0) }

func stripHeredocBodies(p0 string) string { return shell.StripHeredocBodies(p0) }
