// Code generated by tddsplit. DO NOT EDIT.

package suite

import (
	core "github.com/aphrollo/aphrollo-tools/internal/tdd/core"
	time "time"
)

const Source = core.Source

const StateSchema = core.StateSchema

const Test = core.Test

type GateResult = core.GateResult

type Kind = core.Kind

type Outcome = core.Outcome

type Runner = core.Runner

type gateEntry = core.GateEntry

func AppendGateLog(p0 string, p1 string, p2 string, p3 string, p4 time.Duration) {
	core.AppendGateLog(p0, p1, p2, p3, p4)
}

func ClassifyFile(p0 string) Kind { return core.ClassifyFile(p0) }

func LogToken(p0 string) string { return core.LogToken(p0) }

func StateDir() string { return core.StateDir() }

func cargoPackageName(p0 string) string { return core.CargoPackageName(p0) }

func dedupeSorted(p0 []string) []string { return core.DedupeSorted(p0) }

func fitRunes(p0 string, p1 int) string { return core.FitRunes(p0, p1) }

func pidRunningFn(p0 int) bool { return core.PidRunningFn(p0) }

func readStateJSON(p0 string, p1 any) (bool, bool) { return core.ReadStateJSON(p0, p1) }

func repoStateKey(p0 string) string { return core.RepoStateKey(p0) }

func sameProject(p0 string, p1 string) bool { return core.SameProject(p0, p1) }

func tomlBoolIn(p0 string, p1 string, p2 string) bool { return core.TomlBoolIn(p0, p1, p2) }

func tomlStringIn(p0 string, p1 string, p2 string) (string, bool) {
	return core.TomlStringIn(p0, p1, p2)
}

func tomlStringsIn(p0 string, p1 string, p2 string) []string { return core.TomlStringsIn(p0, p1, p2) }

func writeFileAtomic(p0 string, p1 []byte) error { return core.WriteFileAtomic(p0, p1) }
