// Code generated by tddsplit. DO NOT EDIT.

package suite

import (
	lock "github.com/aphrollo/aphrollo-tools/internal/tdd/lock"
	time "time"
)

const BuildLockHeldEnv = lock.BuildLockHeldEnv

const CapSlot = lock.CapSlot

const suiteFloorMargin = lock.SuiteFloorMargin

type BuildLockOwner = lock.BuildLockOwner

type BuildSlot = lock.BuildSlot

type CapKind = lock.CapKind

type CapResult = lock.CapResult

type CapRun = lock.CapRun

type MemCap = lock.MemCap

func MemCapFor(p0 string, p1 CapKind) MemCap { return lock.MemCapFor(p0, p1) }

func NewCapRun(p0 MemCap) *CapRun { return lock.NewCapRun(p0) }

func ReadBuildSlotOwner(p0 string) (BuildLockOwner, bool) { return lock.ReadBuildSlotOwner(p0) }

func ResolveCargoTargetDir(p0 string) string { return lock.ResolveCargoTargetDir(p0) }

func WaitForHeadroom(p0 string, p1 time.Duration) string { return lock.WaitForHeadroom(p0, p1) }

func acquireBuildSlot(p0 string, p1 time.Duration, p2 string, p3 string) (BuildSlot, func(), bool) {
	return lock.AcquireBuildSlot(p0, p1, p2, p3)
}

func buildSlotCount() int { return lock.BuildSlotCount() }

func cappedFloor(p0 time.Duration, p1 time.Duration) time.Duration { return lock.CappedFloor(p0, p1) }

func cargoTmpEnv(p0 string) []string { return lock.CargoTmpEnv(p0) }

func cargoTomlHasWorkspaceTable(p0 string) bool { return lock.CargoTomlHasWorkspaceTable(p0) }

func cargoWorkspaceRoot(p0 string) string { return lock.CargoWorkspaceRoot(p0) }

func foreignLoadReport(p0 int) string { return lock.ForeignLoadReport(p0) }

func goRaceLockKey() string { return lock.GoRaceLockKey() }

func goTmpEnv(p0 string) []string { return lock.GoTmpEnv(p0) }

func invalidateFutureStampedArtifacts(p0 string) { lock.InvalidateFutureStampedArtifacts(p0) }

func lockWaitLogAfter() time.Duration { return lock.LockWaitLogAfter() }

func runnerTargetDir(p0 Runner, p1 string) string { return lock.RunnerTargetDir(p0, p1) }

func runnerWithBuildJobs(p0 Runner, p1 int) Runner { return lock.RunnerWithBuildJobs(p0, p1) }
