// Code generated by tddsplit. DO NOT EDIT.

package suite

import (
	core "github.com/aphrollo/aphrollo-tools/internal/tdd/core"
)

func parseGateLine(p0 string) (gateEntry, bool) { return core.ParseGateLine(p0) }
