// Code generated by tddsplit. DO NOT EDIT.

package suite

import (
	lock "github.com/aphrollo/aphrollo-tools/internal/tdd/lock"
	time "time"
)

const buildSlotsEnv = lock.BuildSlotsEnv

var futureMtimeChecked = lock.FutureMtimeChecked

func EnvWithBuildJobs(p0 []string, p1 int) []string { return lock.EnvWithBuildJobs(p0, p1) }

func GoTmpRootDir(p0 string) string { return lock.GoTmpRootDir(p0) }

func SetBuildLockPathForTest(p0 string) func() { return lock.SetBuildLockPathForTest(p0) }

func SetLockWaitLogThresholdForTest(p0 time.Duration) func() {
	return lock.SetLockWaitLogThresholdForTest(p0)
}

func SetPostEditLockWaitForTest(p0 time.Duration) func() { return lock.SetPostEditLockWaitForTest(p0) }

func SetPrecommitLockWait(p0 time.Duration) func() { return lock.SetPrecommitLockWait(p0) }

func TryAcquireBuildSlot(p0 string, p1 string, p2 string) (BuildSlot, func(), bool) {
	return lock.TryAcquireBuildSlot(p0, p1, p2)
}

func TryAcquireLongVerbSlot(p0 string, p1 string, p2 string) (BuildSlot, func(), func(), bool) {
	return lock.TryAcquireLongVerbSlot(p0, p1, p2)
}

func buildSlotCount() int { return lock.BuildSlotCount() }

func buildSlotHolderDescription(p0 string) string { return lock.BuildSlotHolderDescription(p0) }

func cargoConfigJobs(p0 string) (int, bool) { return lock.CargoConfigJobs(p0) }

func effectiveBuildLockPath() string { return lock.EffectiveBuildLockPath() }

func goTmpDir(p0 string) string { return lock.GoTmpDir(p0) }

func postEditLockWait() time.Duration { return lock.PostEditLockWait() }

func precommitLockWait() time.Duration { return lock.PrecommitLockWait() }

func resolveTargetDir(p0 func(string) string, p1 string) string { return lock.ResolveTargetDir(p0, p1) }

func setBuildLockPathOverride(p0 string) func() { return lock.SetBuildLockPathOverride(p0) }

func slotJobs(p0 int, p1 int) int { return lock.SlotJobs(p0, p1) }

func storeFutureMtimeMarker(p0 string, p1 time.Time) { lock.StoreFutureMtimeMarker(p0, p1) }

func targetLockPath(p0 string) string { return lock.TargetLockPath(p0) }

func totalCargoJobs() int { return lock.TotalCargoJobs() }
