// Code generated by tddsplit. DO NOT EDIT.

package suite

import (
	shell "github.com/aphrollo/aphrollo-tools/internal/tdd/shell"
)

type shellWord = shell.ShellWord

func cdTargetTilde(p0 []shellWord) (string, bool) { return shell.CdTargetTilde(p0) }

func resolveAgainst(p0 string, p1 string) string { return shell.ResolveAgainst(p0, p1) }

func shellSegments(p0 string) [][]string { return shell.ShellSegments(p0) }

func shellSegmentsTokens(p0 string) [][]shellWord { return shell.ShellSegmentsTokens(p0) }

func stripHeredocBodies(p0 string) string { return shell.StripHeredocBodies(p0) }

func wordTexts(p0 []shellWord) []string { return shell.WordTexts(p0) }
