// Code generated by tddsplit. DO NOT EDIT.

package suite

import (
	syscall "syscall"
	time "time"
)

const AmbiguousTest = ambiguousTest

const BashSuiteVerdictFreshFor = bashSuiteVerdictFreshFor

const NarrowedSuiteInvocation = narrowedSuiteInvocation

const NotSuiteInvocation = notSuiteInvocation

const OutcomeCheckError = outcomeCheckError

const OutcomeContention = outcomeContention

const OutcomeFail = outcomeFail

const OutcomePass = outcomePass

const OutcomeSkipped = outcomeSkipped

const OutcomeTimeout = outcomeTimeout

const OutcomeVacuous = outcomeVacuous

const RedGoesStaleAfter = redGoesStaleAfter

const SuiteOutputCap = suiteOutputCap

type GoReachGraph = goReachGraph

type GoTestEvent = goTestEvent

type MechCacheFile = mechCacheFile

type MutantsConfigTable = mutantsConfigTable

type RunScope = runScope

type RustSplit = rustSplit

type StageOutcome = stageOutcome

type StageOutcomeKind = stageOutcomeKind

type SuiteOutputRecord = suiteOutputRecord

type SuiteProofLedger = suiteProofLedger

type SuiteShape = suiteShape

var CargoNarrowingBareFlags = cargoNarrowingBareFlags

var CargoNarrowingValueFlags = cargoNarrowingValueFlags

var CargoScopeValueFlags = cargoScopeValueFlags

var CargoTestResultRe = cargoTestResultRe

var GhAvailable = ghAvailable

var NoTestsToRunRe = noTestsToRunRe

var PytestSummaryCategoryRe = pytestSummaryCategoryRe

var RegisteredStages = registeredStages

var SuiteRanGreen = &suiteRanGreen

var TestDeclRes = testDeclRes

func ApplyEdit(p0 string, p1 string, p2 string, p3 bool) string { return applyEdit(p0, p1, p2, p3) }

func AttemptedScope(p0 string) runScope { return attemptedScope(p0) }

func BuildOnlyRunner(p0 Runner) bool { return buildOnlyRunner(p0) }

func BuildOnlyTerminal(p0 Runner, p1 string, p2 SuiteResult) string {
	return buildOnlyTerminal(p0, p1, p2)
}

func CargoAlwaysRunPackages(p0 string) []string { return cargoAlwaysRunPackages(p0) }

func CargoAphrolloFlag(p0 string, p1 string) bool { return cargoAphrolloFlag(p0, p1) }

func CargoAphrolloPackages(p0 string, p1 string) []string { return cargoAphrolloPackages(p0, p1) }

func CargoAphrolloString(p0 string, p1 string) (string, bool) { return cargoAphrolloString(p0, p1) }

func CargoClippyCleanPackages(p0 string) []string { return cargoClippyCleanPackages(p0) }

func CargoIntegrationTargetsNotRun(p0 Runner, p1 string) []string {
	return cargoIntegrationTargetsNotRun(p0, p1)
}

func CargoModuleFilterPath(p0 string, p1 string) string { return cargoModuleFilterPath(p0, p1) }

func CargoNestedTestFileReachable(p0 string, p1 string) bool {
	return cargoNestedTestFileReachable(p0, p1)
}

func CargoPackageFor(p0 string, p1 string) string { return cargoPackageFor(p0, p1) }

func CargoPackagesOwning(p0 string, p1 []string) []string { return cargoPackagesOwning(p0, p1) }

func CargoRunArgs(p0 Runner) []string { return cargoRunArgs(p0) }

func CargoRunnerAt(p0 string, p1 ...string) (Runner, bool) { return cargoRunnerAt(p0, p1...) }

func CargoTargetNamer(p0 string) func(pos int) string { return cargoTargetNamer(p0) }

func CargoVacuousTargets(p0 string) []string { return cargoVacuousTargets(p0) }

func CargoVerbArgs(p0 string) []string { return cargoVerbArgs(p0) }

func CargoWorkspaceDepsFn(p0 string) (map[string][]string, error) { return cargoWorkspaceDepsFn(p0) }

func ClassificationOutput(p0 string, p1 string) string { return classificationOutput(p0, p1) }

func ClassifyRunOutcome(p0 Runner, p1 string, p2 SuiteResult, p3 []string) Outcome {
	return classifyRunOutcome(p0, p1, p2, p3)
}

func ClassifySuiteSegment(p0 []string) suiteShape { return classifySuiteSegment(p0) }

func ClippyScope(p0 string, p1 string, p2 string, p3 []string) []string {
	return clippyScope(p0, p1, p2, p3)
}

func CmdString(p0 Runner) string { return cmdString(p0) }

func ConsumeProvenSuiteStamp(p0 string) string { return consumeProvenSuiteStamp(p0) }

func DeclaresTest(p0 string, p1 string) (bool, bool) { return declaresTest(p0, p1) }

func DependentsOf(p0 map[string][]string, p1 []string) []string { return dependentsOf(p0, p1) }

func DiffHeaderPath(p0 string) (string, bool) { return diffHeaderPath(p0) }

func DirHasGoFiles(p0 string) bool { return dirHasGoFiles(p0) }

func DoctestRunners(p0 string, p1 []string) []Runner { return doctestRunners(p0, p1) }

func DropLeadingEnvAssignments(p0 []string) []string { return dropLeadingEnvAssignments(p0) }

func EffectiveRunRoot(p0 string, p1 string) string { return effectiveRunRoot(p0, p1) }

func FilesUnderRoot(p0 string, p1 string, p2 []string) []string { return filesUnderRoot(p0, p1, p2) }

func FindRootFrom(p0 string) string { return findRootFrom(p0) }

func FirstDeclaredList(p0 []mutantsConfigTable, p1 string) []string { return firstDeclaredList(p0, p1) }

func FixtureLawFromPath(p0 string) (string, bool) { return fixtureLawFromPath(p0) }

func FlagName(p0 string) string { return flagName(p0) }

func ForeignBuildAdvisory(p0 string, p1 string, p2 string, p3 SuiteResult) string {
	return foreignBuildAdvisory(p0, p1, p2, p3)
}

func GateSuiteProof() *suiteProofLedger { return gateSuiteProof() }

func GcStatePath(p0 string) string { return gcStatePath(p0) }

func GitRead(p0 string, p1 ...string) (string, error) { return gitRead(p0, p1...) }

func GoPackageDir(p0 string, p1 string) string { return goPackageDir(p0, p1) }

func GoPassedCount(p0 string) (int, bool) { return goPassedCount(p0) }

func GoReachGraphFn(p0 string) (goReachGraph, error) { return goReachGraphFn(p0) }

func GoRunFilter(p0 []string) string { return goRunFilter(p0) }

func GoRunRanATest(p0 SuiteResult) (bool, bool) { return goRunRanATest(p0) }

func GoTestReachFn(p0 string, p1 string) ([]string, error) { return goTestReachFn(p0, p1) }

func HasGateProfile(p0 string) bool { return hasGateProfile(p0) }

func HasGitHubRemote(p0 string) bool { return hasGitHubRemote(p0) }

func HasNextestProfile(p0 string, p1 string) bool { return hasNextestProfile(p0, p1) }

func HasNoRunFlag(p0 []string) bool { return hasNoRunFlag(p0) }

func HashNonEmpty(p0 string) string { return hashNonEmpty(p0) }

func IndexTree(p0 string) string { return indexTree(p0) }

func InsideDir(p0 string, p1 string) bool { return insideDir(p0, p1) }

func IsEnvAssignment(p0 string) bool { return isEnvAssignment(p0) }

func IsGoTestInvocation(p0 string, p1 []string) bool { return isGoTestInvocation(p0, p1) }

func LaneBaseSHA(p0 string) string { return laneBaseSHA(p0) }

func LoadGoReachGraph(p0 string) (goReachGraph, error) { return loadGoReachGraph(p0) }

func LoadMechCache(p0 string) *mechCacheFile { return loadMechCache(p0) }

func LogLockWait(p0 string, p1 string, p2 Runner, p3 time.Duration) { logLockWait(p0, p1, p2, p3) }

func LogSuiteVerdict(p0 string, p1 string, p2 string, p3 string, p4 SuiteResult) {
	logSuiteVerdict(p0, p1, p2, p3, p4)
}

func MechCacheAdd(p0 string) { mechCacheAdd(p0) }

func MechCacheAddUnmoved(p0 string, p1 string, p2 Runner) { mechCacheAddUnmoved(p0, p1, p2) }

func MechCacheHit(p0 string) bool { return mechCacheHit(p0) }

func MechCachePath() string { return mechCachePath() }

func MechKey(p0 string, p1 string, p2 Runner) string { return mechKey(p0, p1, p2) }

func MechKeyPrefix(p0 string, p1 string) string { return mechKeyPrefix(p0, p1) }

func MutantsConfigTables(p0 string) []mutantsConfigTable { return mutantsConfigTables(p0) }

func NarrowFailFirstTests(p0 Runner, p1 string, p2 []string) Runner {
	return narrowFailFirstTests(p0, p1, p2)
}

func NarrowToStaged(p0 Runner, p1 string, p2 []string) (Runner, bool) {
	return narrowToStaged(p0, p1, p2)
}

func NextestInstalled() bool { return nextestInstalled() }

func NotCompiledTerminal(p0 Runner, p1 string, p2 string, p3 SuiteResult) string {
	return notCompiledTerminal(p0, p1, p2, p3)
}

func NotRunClause(p0 []string, p1 string) string { return notRunClause(p0, p1) }

func PackageHasDoctests(p0 string) bool { return packageHasDoctests(p0) }

func ParseWorkspaceDeps(p0 []byte) (map[string][]string, error) { return parseWorkspaceDeps(p0) }

func RenderGoTestJSON(p0 string) (string, string, bool) { return renderGoTestJSON(p0) }

func ReportSuitesNotRun(p0 string, p1 string, p2 string, p3 Runner, p4 []string) {
	reportSuitesNotRun(p0, p1, p2, p3, p4)
}

func ResetSuiteProof() { resetSuiteProof() }

func RetainSuiteOutput(p0 string, p1 string, p2 string, p3 string, p4 SuiteResult) {
	retainSuiteOutput(p0, p1, p2, p3, p4)
}

func RunCargoLocked(p0 SuiteRunner, p1 Runner, p2 string, p3 time.Duration, p4 time.Duration, p5 time.Duration) (SuiteResult, time.Duration, bool) {
	return runCargoLocked(p0, p1, p2, p3, p4, p5)
}

func RunGh(p0 string, p1 ...string) (string, error) { return runGh(p0, p1...) }

func RunGhTimeout(p0 string, p1 time.Duration, p2 ...string) (string, error) {
	return runGhTimeout(p0, p1, p2...)
}

func RunnerDir(p0 Runner, p1 string) string { return runnerDir(p0, p1) }

func RustFileIsTestModule(p0 string, p1 string, p2 string) bool {
	return rustFileIsTestModule(p0, p1, p2)
}

func SelectedZeroTests(p0 Runner, p1 SuiteResult) bool { return selectedZeroTests(p0, p1) }

func SplitFlagValue(p0 string) (string, string, bool) { return splitFlagValue(p0) }

func SplitRustTests(p0 string, p1 bool) (rustSplit, bool) { return splitRustTests(p0, p1) }

func StagedProjectRoots(p0 string, p1 []string) []string { return stagedProjectRoots(p0, p1) }

func StaleArtifactHint(p0 string, p1 string) string { return staleArtifactHint(p0, p1) }

func StampProvenSuite(p0 string) { stampProvenSuite(p0) }

func StampTree(p0 string, p1 string) { stampTree(p0, p1) }

func SuiteAttrs() *syscall.SysProcAttr { return suiteAttrs() }

func SuiteEnv(p0 Runner, p1 string) []string { return suiteEnv(p0, p1) }

func SuiteNoun(p0 string) string { return suiteNoun(p0) }

func SuiteTouchedNames(p0 Runner) []string { return suiteTouchedNames(p0) }

func ToRootRelative(p0 string, p1 string, p2 []string) []string { return toRootRelative(p0, p1, p2) }

func UntestedVerdict(p0 Runner, p1 SuiteResult) string { return untestedVerdict(p0, p1) }

func VacuousGoPackages(p0 string) ([]string, error) { return vacuousGoPackages(p0) }

func VacuousNames(p0 Runner, p1 SuiteResult) ([]string, error) { return vacuousNames(p0, p1) }

func VerdictCoversRun(p0 gateEntry, p1 runScope) bool { return verdictCoversRun(p0, p1) }

func VerdictFor(p0 string, p1 string, p2 string, p3 string, p4 stageOutcome) GateResult {
	return verdictFor(p0, p1, p2, p3, p4)
}

func WholeRunScope() runScope { return wholeRunScope() }

func WithGateProfile(p0 Runner, p1 string) Runner { return withGateProfile(p0, p1) }

func WorktreeStateHash(p0 string) string { return worktreeStateHash(p0) }

func WriteSuiteOutputRecord(p0 suiteOutputRecord) error { return writeSuiteOutputRecord(p0) }

func ZigTestLines(p0 string) map[int]bool { return zigTestLines(p0) }
