"""The trellis session flow, top to bottom: the spec the workbench diagram is drawn from."""
from engine import B, D, F, H, HO, Layout, P, S, SE

LOOP = 'loop'

spec = [
    P('Session starts', sub='startup, resume, fork, clear, compact; /reload-plugins after trellis is enabled or updated', tone='good', id='start'),
    H('SessionStart / Setup', sub="Claude's first response waits; under 200 ms when idle",
      side=[SE('Setup', '--init-only, -p --init, --maintenance')]),
    F('TRELLIS SETUP', [
        D('clear or compact, and trellis ready?', main='no', side=S('yes: no checks', to='on-here-start')),
        F('GETTING THE BINARY', [
            B('Work out the version wanted', ['the plugin pin, or the pin override in the user layer;',
                                              'trellis update: --to, or the repo\'s requires'], id='want'),
            D('Wanted version on the box?', main='no', side=S('yes', to='newer')),
            B('Fetch the release', ['GitHub Releases, time-limited; sha256 checked;',
                                    'a mismatch is deleted and named a security error']),
            D('Downloaded and verified?', main='no',
              side=S('yes', [B('Keep it', ['temp file, renamed in under a lock; the last 3 stay'])], to='newer')),
            D('A kept binary on the box?', main='yes',
              side=S('no', [B('trellis not ready', ['what failed and the fix, to you and Claude;',
                                                    'commits read as ungated; every hook silent',
                                                    'until trellis update repairs it'])],
                     to='after-setup')),
            B('Use the newest kept, warn once', ['1.4 pinned, the fetch failed; running 1.3'], to='binary-ready'),
            D('Newer than the binary in use?', main='yes', side=S('no', to='binary-ready'), id='newer'),
            D('Comparison on record?', main='yes',
              side=S('no', [B('Compare in the background', ['the binary in use stays;',
                                                            'the result applies at the next start'])],
                     to='binary-ready')),
            D('Same verdicts?', main='yes',
              note='a repo\'s unchanged tree, both binaries read-only; no repo counts as same',
              side=S('no', [B('Update staged', ['the binary in use stays; the difference named'])],
                     to='binary-ready')),
            B('Use the new binary'),
            HO('Binary ready', id='binary-ready'),
            D('Started by trellis update?', main='no',
              side=S('yes', [B('Update result in the tool output', ['version in use, staged, or what failed'])],
                     to='tool-ok')),
        ]),
        B('Check the box', ['Claude Code version, changelog hits named;',
                            'a git identity the commit gate would refuse, named;',
                            'shims on PATH through CLAUDE_ENV_FILE, calling the launcher;',
                            'an old aphrollo install found: First start asks;',
                            'a stopped merge queue named;',
                            'a due cleanup starts in the background']),
        D('Setup record present?', main='no', side=S('yes', to='check-settings')),
        D('Anyone to answer?', main='yes',
          side=S('no', [B('TRELLIS_CONFIG or the defaults', ['-p, routine, CI, Setup: never pending;',
                                                             'an ask means not here'])],
                 to='check-settings')),
        B('Defaults now, setup pending', ['the questions come at the first prompt']),
        B('Check the settings', ['built-in and user layers schema-checked; a bad',
                                 'layer is named, its keys fall back to built-in'], id='check-settings'),
        D('trellis on here?', main='yes', side=S('no', to='trellis-ready'), id='on-here-start',
          note='a recorded yes, or trellis everywhere'),
        B('Inject the gate rules', ['additionalContext: the rules as tdd words them,',
                                    'this lane\'s open red, what Check the box found']),
        HO('trellis ready', id='trellis-ready',
           note=['Change a setting: trellis config set, in conversation or typed;',
                 '--local for this repo, --session for this session']),
    ]),
    D('--init-only?', main='no', side=S('yes', [P('Claude Code exits')]), id='after-setup'),
    D('Mid-turn compact?', main='no', side=S('yes: the turn goes on', to='call')),
    F('EACH TURN', tone='turn', items=[
        H('UserPromptSubmit', id='ups', side=[SE('UserPromptExpansion', 'slash commands'),
                                              SE('CwdChanged', 'a new repo: Repo start runs'), SE('DirectoryAdded', 'the same')]),
        F('FIRST START', [
            D('Setup pending?', main='yes', side=S('no', to='settings-ready')),
            D('Questions already asked?', main='no', side=S('yes: Repo start waits', to='call')),
            B('Ask the setup questions', ['the setup skill as additionalContext; Claude',
                                          'asks before your prompt; trellis config set saves;',
                                          'an old aphrollo install: removed on a yes, backed up;',
                                          'Repo start waits for the answers'], to='call'),
            HO('Settings ready', id='settings-ready'),
        ]),
        F('REPO START', [
            D('Repo declined?', main='no', note='the user layer, keyed by repo',
              side=S('yes', [B('trellis off here', ['every hook silent, under 50 ms'])], to='call')),
            D('Repo set up?', main='no', side=S('yes', to='requires'), note='the record Set up the repo leaves, user layer'),
            D('trellis here?', main='yes', note='trellis everywhere, or a yes recorded',
              side=S('not asked', [B('Ask: trellis here?', ['Claude asks; a no is recorded;',
                                                          'Repo start runs at the next prompt'])], to='call')),
            D('Git repo?', main='yes',
              side=S('no', [B('git init, or ask', ['Setup says git init: run now, no remote;',
                                                   'else Claude asks; a yes runs it, a no is recorded'])],
                     to='call')),
            D('requires met?', main='yes', id='requires', note='by the binary in use or a kept one',
              side=S('no', [B('trellis too old here', ['needs 1.5: run trellis update;',
                                                       'commits read as ungated'])], to='call')),
            B('Set up the repo', ['trellis.toml and trellis.local.toml schema-checked;',
                                  'languages, test runners, law presets;',
                                  'the git gate as repo hooks; merge.ff=false;',
                                  'ci = github: offers branch protection;',
                                  'baselines and trellis.toml migrated, own commit;',
                                  '[skip] for what is current; recorded, user layer']),
            D('Git gate runs here?', main='yes', note='no foreign hook; core.hooksPath ours or unset',
              side=S('no', [B('Name the conflict and the fix', ['commits read as ungated until fixed'])],
                     to='inject-repo')),
            B('Inject the gate rules', ['silent when this session has them'], id='inject-repo'),
            HO('Repo ready'),
            B('Tell Claude what finished', ['since its last hook: deferred verdicts, an open red,',
                                            'a lane closed; silent when nothing'], id='tell'),
        ]),
        F('AGENTIC LOOP', tone='loop', items=[
            D('Claude calls a tool?', main='yes', id='call', side=S('no', to='stop', left=True)),
            H('PreToolUse', tone='step'),
            F('GUARDRAIL AND LANE', [
                D('trellis on here?', main='yes', side=S('no: silent', to='perm', left=True)),
                D('Guardrail hit?', main='no', note='secrets, attribution, destructive or outward-facing',
                  side=S('yes', [B('Call denied', ['the rule and the safe command named'])], to=LOOP)),
                D('Writes into the repo?', main='yes', note='Edit, Write, NotebookEdit, a Bash or PowerShell write',
                  side=S('no', to='guidance', left=True)),
                D('On main, with isolation = true?', main='no', note='where each target lands, not the cwd',
                  side=S('yes', [B('Edit denied, worktree made', ['under .claude/worktrees/, from main; the deny',
                                                                 'names its path; Claude passes it to EnterWorktree'])],
                         to=LOOP)),
                HO('Lane ready', note='isolation = false: no lane, the work stays on main'),
            ]),
            F('RED TO GREEN', [
                D('tdd = off?', main='no', side=S('yes', to='deny-law', left=True)),
                D('Code edit?', main='yes', note='code, not a test, doc or config',
                  side=S('no', to='test-q', left=True)),
                D('Code edits open here?', main='no', note="a new test's real red in this package",
                  side=S('yes', to='deny-law')),
                D('Tested code?', main='no', side=S('yes: refactor', to='deny-law')),
                D('tdd = enforce?', main='yes',
                  side=S('no: warn', [B('Next step as additionalContext', ['the failing test to write'])],
                         to='deny-law')),
                B('Edit denied', ['names the failing test to write, and its file;',
                                  'a wrong deny: trellis feedback records it'], to=LOOP),
                D('Test of an open red, before its green?', main='no', id='test-q',
                  side=S('yes', [B('Code edits close', ['a new red is needed'])], to='deny-law')),
                D('Breaks a deny law?', main='no', id='deny-law', note='the content Edit or Write would write',
                  side=S('yes', [B('Edit denied: law named', ['the law, its line, its escape comment'])], to=LOOP)),
                B('Guidance as additionalContext', ['long waits, noisy output, warn laws; silent when none'],
                  id='guidance'),
            ]),
            H('PermissionRequest', tone='step', id='perm', side=[SE('PermissionDenied', 'auto-mode deny')]),
            H('[tool executes]', tone='tool', side=[SE('Elicitation', 'MCP input'), SE('ElicitationResult', 'MCP input')]),
            F('WHAT THE CALL RUNS', [
                F('SUBAGENT', [
                    D('Agent tool?', main='yes', side=S('no', to='task-q', left=True)),
                    H('SubagentStart', tone='step', side=[SE('WorktreeCreate', 'only with isolation: "worktree"')]),
                    B('Brief the subagent', ['the gate brief as additionalContext;',
                                             'it runs this same loop']),
                    H('SubagentStop', tone='step', side=[SE('WorktreeRemove', 'the worktree; the branch lives on')]),
                    D('Unseen red to block?', main='no',
                      side=S('yes', [B('Subagent stop blocked once', ['decision: block; it works on'])], to=LOOP)),
                    B('The Agent result', to='tool-ok'),
                ]),
                F('TASKS', [
                    D('Task marked done?', main='yes', id='task-q', side=S('no', to='commit-q', left=True)),
                    H('TaskCompleted', tone='step', side=[SE('TaskCreated', 'trellis takes no action')]),
                    D("Its tests red, tdd = enforce?", main='no',
                      side=S('yes', [B('Task kept open', ['exit 2, the failing test as reason'])], to='tool-ok')),
                    B('Task closed', to='tool-ok'),
                ]),
                F('GIT GATES', [
                    D('git commit?', main='yes', id='commit-q', side=S('no', to='push-q', left=True)),
                    B('Commit gate: pre-commit, commit-msg', ['staged-baseline guard, laws, docs, suppressions,',
                                                              'linters, the red-green proof (unproven: re-run',
                                                              'at HEAD), mutation on added lines; no attribution']),
                    D('Gate passes?', main='yes',
                      side=S('no', [B('Commit refused', ['the stage named'])], to='tool-ok')),
                    B('post-commit', ['a git note marks the commit gated'], to='tool-ok'),
                    D('git push?', main='yes', id='push-q', side=S('no', to='pr-q', left=True)),
                    B('Push gate: pre-push', ['no attribution in a pushed commit or ref name']),
                    D('Gate passes?', main='yes',
                      side=S('no', [B('Push refused', ['the commit or ref named'])], to='tool-ok')),
                    B('Pushed', to='tool-ok'),
                    D('Open-a-PR verb?', main='yes', id='pr-q', side=S('no', to='merge-q', left=True)),
                    B('PR opened', ['GitHub CI starts on a ready PR; a draft starts none'], to='tool-ok'),
                ]),
                F('CI', [
                    D('Merge verb?', main='yes', id='merge-q', side=S('no', to='bare-q', left=True)),
                    D('ci = local?', main='no', note='or --ci local; auto: local without a GitHub remote',
                      side=S('yes', to='local-ci')),
                    B('GitHub CI', ['the run the PR started, outside Claude Code'], outside=True, id='gh-ci'),
                    D('Run concluded?', main='no', id='concluded', side=S('yes', to='verdict')),
                    D('Pending under 90 min?', main='no',
                      side=S('yes', [B('Wait for the run')], to='concluded')),
                    D('Run started?', main='no',
                      side=S('yes', [B('Merge refused: CI still pending', ['retry later'])], to='tool-ok')),
                    D('A ready PR?', main='yes',
                      side=S('no', [B('Merge refused: open a ready PR')], to='tool-ok')),
                    D('ci = auto?', main='yes',
                      side=S('no', [B('Merge refused: ci unavailable', ['not failed, no escape;',
                                                                         'retry, or --ci local'])], to='tool-ok')),
                    B('Local CI', ['the same binary, in this merge'], id='local-ci'),
                    B('Record the CI verdict', ['per lane head, and which CI judged it'], id='verdict'),
                    D('CI green?', main='no', side=S('yes', to='merge-gate')),
                    D('Green locally on this head?', main='yes', note='the git note from post-commit',
                      side=S('no', [B('Merge refused', ['the red named'])], to='tool-ok')),
                    B('Escape recorded', ['no merge; code edits close until a test',
                                          'reproduces it; gate stats counts it'], to='tool-ok', id='escape-ci'),
                ]),
                F('MERGE GATE', [
                    D('A bare git merge?', main='yes', id='bare-q', side=S('no', to='upd-q', left=True)),
                    B('Merge gate: pre-merge-commit', ['refused without a recorded CI verdict; suites',
                                                       'and laws on the merged tree; the CI mutation',
                                                       'verdict green; an escape fix changes a check;',
                                                       'a conflicted merge: the same gate at its commit'],
                      id='merge-gate'),
                    D('Gate passes?', main='no', side=S('yes', to='post-merge')),
                    D('A red after a local green?', main='yes',
                      side=S('no', [B('Merge refused', ['the cause named'])], to='tool-ok')),
                    B('Escape recorded', ['no merge; code edits close until a test',
                                          'reproduces it'], to='tool-ok'),
                    B('post-merge', ['records the merge, a manual one too; the retro',
                                     'reads the events; merged lanes no session is',
                                     'in are removed; the next hook says lane closed'],
                      id='post-merge', to='tool-ok'),
                ]),
                D('trellis update?', main='no', id='upd-q', side=S('yes', to='want')),
            ]),
            D('Tool succeeded?', main='yes', id='tool-ok', note='every call returns here, a refusal inside it too',
              side=S('no', [dict(k='hook', text='PostToolUseFailure', sub=['nothing recorded'])], to='batch')),
            H('PostToolUse', tone='step'),
            D('trellis on here?', main='yes', side=S('no', to='batch')),
            B('Record the edit', ['formats the file and names it; the ledger entry;',
                                  'laws and lint on the edited lines; silent when',
                                  'nothing was written']),
            H('PostToolBatch', tone='step', id='batch'),
            F('TESTS, ONCE PER BATCH', [
                D('Anything edited this batch?', main='yes', note='trellis on here; denied calls count as unedited',
                  side=S('no', to=LOOP)),
                B('Mark unproven packages', ['a write no parser saw; silent when none']),
                B("Run the edited packages' tests"),
                D('Done within the budget?', main='yes',
                  side=S('no', [B('Deferred run', ['runs on in the background; its verdict',
                                                   'reaches Claude at the next hook'])], to=LOOP)),
                B('The verdict to Claude', ['additionalContext']),
                D('Tested?', main='yes',
                  side=S('no', [B('Not tested', ['timed out, skipped, no build slot:',
                                                 'the last real verdict stands'])], to=LOOP)),
                D('Green?', main='no',
                  side=S('yes', [B('Code edits close', ['the next code edit needs a new red'])], to=LOOP)),
                D("A new test's real red?", main='yes',
                  side=S('no', [B('No code edits open', ["broken setup or another test's red, named"])], to=LOOP)),
                B('Code edits open', ['in this package, until that test is green'], to=LOOP),
            ]),
            H('Stop', tone='bad', id='stop', side=[SE('StopFailure', 'an API error; output ignored')]),
            F('STOP CHECK', [
                D('Unseen red to block?', main='no',
                  note='trellis on, tdd = enforce, not stop_hook_active; a run that finished red after Claude\'s last hook',
                  side=S('yes', [B('Stop blocked once', ['decision: block, the red as reason'])], to=LOOP)),
            ]),
        ]),
        P('Turn ends'),
    ]),
    D('Next prompt?', main='no', side=S('yes', to='ups')),
    D('/compact?', main='yes', side=S('no', to='session-end')),
    H('PreCompact', sub='also auto-compact, mid-turn', side=[SE(n, free=True) for n in ('Notification', 'TeammateIdle', 'ConfigChange', 'Pre/PostModelSwitch', 'FileChanged', 'InstructionsLoaded', 'MessageDisplay')]),
    H('PostCompact', sub='then SessionStart with source compact', to='start', stop=True,
      ),
    H('SessionEnd', id='session-end'),
    B("Stop this session's deferred runs, drop its state", ['nothing that blocks; a 1.5 s budget']),
    D('/clear?', main='no', side=S('yes: source clear', to='start')),
    P('Session ends', sub='a later --resume starts at Session starts'),
]

TITLE = "Claude Code's hook lifecycle with trellis on top: one session"
LEGEND = 'each trellis flow at the hook that runs it; trellis is the plugin and its trellis command'
