// Code generated by tddsplit. DO NOT EDIT.

package core

import (
	gitx "github.com/aphrollo/aphrollo-tools/internal/tdd/gitx"
)

func git(p0 string, p1 ...string) (string, error) { return gitx.Git(p0, p1...) }
