// Code generated by tddsplit. DO NOT EDIT.

package core

import (
	io "io"
	os "os"
	exec "os/exec"
	time "time"
)

const PremergeDisplayName = premergeDisplayName

const PremergeLogToken = premergeLogToken

const SessionCodeEnv = sessionCodeEnv

const SessionEnv = sessionEnv

const SharedLockFileMode = sharedLockFileMode

type BashSnapshot = bashSnapshot

type Fingerprint = fingerprint

type GateEntry = gateEntry

type ProjectState = projectState

type SessionState = sessionState

type WaiverEntry = waiverEntry

var ErrNoSession = errNoSession

var IgnoredDirs = ignoredDirs

var SourceExts = sourceExts

func AcquirePathLock(p0 string) func() { return acquirePathLock(p0) }

func AphrolloTomlString(p0 string, p1 string) (string, bool) { return aphrolloTomlString(p0, p1) }

func CargoPackageName(p0 string) string { return cargoPackageName(p0) }

func ClaudeConfigDir() string { return claudeConfigDir() }

func CommonGitDir(p0 string) string { return commonGitDir(p0) }

func ComputeFingerprint(p0 string) *fingerprint { return computeFingerprint(p0) }

func DedupeSorted(p0 []string) []string { return dedupeSorted(p0) }

func EnsureSharedSubdir(p0 string) error { return ensureSharedSubdir(p0) }

func EverySessionID() []string { return everySessionID() }

func FileExists(p0 string) bool { return fileExists(p0) }

func FirstLine(p0 string) string { return firstLine(p0) }

func FitRunes(p0 string, p1 int) string { return fitRunes(p0, p1) }

func FormatBytes(p0 int64) string { return formatBytes(p0) }

func FormatDays(p0 time.Duration) string { return formatDays(p0) }

func FormatElapsedSecs(p0 time.Duration) string { return formatElapsedSecs(p0) }

func GateLogStageToken(p0 string) string { return gateLogStageToken(p0) }

func GoEmbedsFile(p0 string) bool { return goEmbedsFile(p0) }

func IsCodeFile(p0 string) bool { return isCodeFile(p0) }

func LoadSession(p0 string) (*sessionState, string) { return loadSession(p0) }

func Logf(p0 io.Writer, p1 string, p2 ...any) { logf(p0, p1, p2...) }

func MarkWorktreeWarned(p0 string) bool { return markWorktreeWarned(p0) }

func Mask(p0 string) string { return mask(p0) }

func MaskTokens(p0 string, p1 bool, p2 bool, p3 bool) string { return maskTokens(p0, p1, p2, p3) }

func MutantsLogDir(p0 string) string { return mutantsLogDir(p0) }

func NormalizeProjectPath(p0 string) string { return normalizeProjectPath(p0) }

func NormalizeRepoSpelling(p0 string) string { return normalizeRepoSpelling(p0) }

func OpenLockFile(p0 string) (*os.File, error) { return openLockFile(p0) }

func ParseGateLine(p0 string) (gateEntry, bool) { return parseGateLine(p0) }

func PidRunning(p0 int) bool { return pidRunning(p0) }

func PidRunningFn(p0 int) bool { return pidRunningFn(p0) }

func Plural(p0 int) string { return plural(p0) }

func PrimaryCheckoutRoot(p0 string) string { return primaryCheckoutRoot(p0) }

func ProjectKey(p0 string) string { return projectKey(p0) }

func QuotedWords(p0 string) []string { return quotedWords(p0) }

func ReadStateJSON(p0 string, p1 any) (bool, bool) { return readStateJSON(p0, p1) }

func RepoStateKey(p0 string) string { return repoStateKey(p0) }

func SamePath(p0 string, p1 string) bool { return samePath(p0, p1) }

func SameProject(p0 string, p1 string) bool { return sameProject(p0, p1) }

func SetOff(p0 string, p1 bool) error { return setOff(p0, p1) }

func SetWaiver(p0 string, p1 string, p2 bool) error { return setWaiver(p0, p1, p2) }

func ShellPath(p0 string) string { return shellPath(p0) }

func Short(p0 string) string { return short(p0) }

func SilentStdio(p0 *exec.Cmd) func() { return silentStdio(p0) }

func SortStrings(p0 []string) { sortStrings(p0) }

func StripQuoted(p0 string) string { return stripQuoted(p0) }

func TomlArrayCommaError(p0 string, p1 string, p2 string) error {
	return tomlArrayCommaError(p0, p1, p2)
}

func TomlBoolIn(p0 string, p1 string, p2 string) bool { return tomlBoolIn(p0, p1, p2) }

func TomlBoolSetIn(p0 string, p1 string, p2 string) (bool, bool) { return tomlBoolSetIn(p0, p1, p2) }

func TomlStringIn(p0 string, p1 string, p2 string) (string, bool) { return tomlStringIn(p0, p1, p2) }

func TomlStringsIn(p0 string, p1 string, p2 string) []string { return tomlStringsIn(p0, p1, p2) }

func TryLockExclusive(p0 *os.File) bool { return tryLockExclusive(p0) }

func WaivedForSession(p0 string, p1 string) bool { return waivedForSession(p0, p1) }

func WarnGateLogUnwritable(p0 string) { warnGateLogUnwritable(p0) }

func WriteFileAtomic(p0 string, p1 []byte) error { return writeFileAtomic(p0, p1) }
