// Code generated by tddsplit. DO NOT EDIT.

package tdd

import (
	lawgate "github.com/aphrollo/aphrollo-tools/internal/tdd/lawgate"
)

func ratchetFixtureStage(p0 string, p1 string) GateResult { return lawgate.RatchetFixtureStage(p0, p1) }

func stagedTouchesLaws(p0 string) bool { return lawgate.StagedTouchesLaws(p0) }
