// Code generated by tddsplit. DO NOT EDIT.

package tdd

import (
	shadow "github.com/aphrollo/aphrollo-tools/internal/shadow"
	postedit "github.com/aphrollo/aphrollo-tools/internal/tdd/postedit"
	tddarm "github.com/aphrollo/aphrollo-tools/internal/tddarm"
	time "time"
)

const DefaultPostEditTimeout = postedit.DefaultPostEditTimeout

const StopHookStop = postedit.StopHookStop

const StopHookSubagentStop = postedit.StopHookSubagentStop

const StopHookTaskCompleted = postedit.StopHookTaskCompleted

const WallDiscard = postedit.WallDiscard

type DeferredJob = postedit.DeferredJob

type PhaseOutcome = postedit.PhaseOutcome

type PrimaryJudgement = postedit.PrimaryJudgement

type StopEvent = postedit.StopEvent

type StopVerdict = postedit.StopVerdict

type Waiver = postedit.Waiver

func ActiveDeferredJobs() []DeferredJob { return postedit.ActiveDeferredJobs() }

func AllowWall(p0 string) (string, error) { return postedit.AllowWall(p0) }

func AllowWallForSession(p0 string, p1 string, p2 string) (string, error) {
	return postedit.AllowWallForSession(p0, p1, p2)
}

func ConsumeDiscardBashSpent(p0 []string) bool { return postedit.ConsumeDiscardBashSpent(p0) }

func ConsumeOneShot(p0 string) bool { return postedit.ConsumeOneShot(p0) }

func ConsumePrimaryBashSpent(p0 []string) bool { return postedit.ConsumePrimaryBashSpent(p0) }

func DecideBashSuite(p0 []byte) (Decision, bool) { return postedit.DecideBashSuite(p0) }

func DecidePreEdit(p0 []byte) (Decision, error) { return postedit.DecidePreEdit(p0) }

func DecideStop(p0 StopEvent, p1 []byte) StopVerdict { return postedit.DecideStop(p0, p1) }

func DeferredPhasesEnabled() bool { return postedit.DeferredPhasesEnabled() }

func DirectPROpenDecision(p0 []byte) Decision { return postedit.DirectPROpenDecision(p0) }

func DiscardBashDecision(p0 []byte) Decision { return postedit.DiscardBashDecision(p0) }

func EffectiveTDD(p0 string) tddarm.Mode { return postedit.EffectiveTDD(p0) }

func EnableDeferredPhases(p0 bool) { postedit.EnableDeferredPhases(p0) }

func FoldBashRun(p0 []byte) { postedit.FoldBashRun(p0) }

func IsBashHook(p0 []byte) bool { return postedit.IsBashHook(p0) }

func JudgePrimary(p0 []byte) PrimaryJudgement { return postedit.JudgePrimary(p0) }

func KnownWall(p0 string) bool { return postedit.KnownWall(p0) }

func ListWaivers() []Waiver { return postedit.ListWaivers() }

func LogBashSuiteDecision(p0 []byte, p1 Decision) { postedit.LogBashSuiteDecision(p0, p1) }

func LogEditDecision(p0 []byte, p1 Decision) { postedit.LogEditDecision(p0, p1) }

func LogLawGuides(p0 []byte, p1 Decision, p2 []LawFinding) { postedit.LogLawGuides(p0, p1, p2) }

func LogOverride(p0 string, p1 string, p2 string) { postedit.LogOverride(p0, p1, p2) }

func PostBash(p0 []byte, p1 SuiteRunner) string { return postedit.PostBash(p0, p1) }

func PostEdit(p0 []byte, p1 SuiteRunner) string { return postedit.PostEdit(p0, p1) }

func PostEditBudget() time.Duration { return postedit.PostEditBudget() }

func PreBash(p0 []byte) { postedit.PreBash(p0) }

func PrimaryCheckoutDecision(p0 []byte) Decision { return postedit.PrimaryCheckoutDecision(p0) }

func PrimaryEditsAllowed(p0 string) bool { return postedit.PrimaryEditsAllowed(p0) }

func PrimaryMergeOnly(p0 string) (string, bool) { return postedit.PrimaryMergeOnly(p0) }

func PrimaryMergeOnlyReason(p0 string) string { return postedit.PrimaryMergeOnlyReason(p0) }

func RecordFinishedDeferredJobForTest(p0 string, p1 string) {
	postedit.RecordFinishedDeferredJobForTest(p0, p1)
}

func RecordFinishedRedDeferredJobForTest(p0 string, p1 string, p2 string, p3 string) {
	postedit.RecordFinishedRedDeferredJobForTest(p0, p1, p2, p3)
}

func RenderPostToolUse(p0 string) ([]byte, int) { return postedit.RenderPostToolUse(p0) }

func RenderPreToolUse(p0 Decision) ([]byte, int) { return postedit.RenderPreToolUse(p0) }

func RenderStopVerdict(p0 StopEvent, p1 StopVerdict) ([]byte, []byte, int) {
	return postedit.RenderStopVerdict(p0, p1)
}

func Revoke(p0 string) (string, error) { return postedit.Revoke(p0) }

func RevokeForSession(p0 string, p1 string, p2 string) (string, error) {
	return postedit.RevokeForSession(p0, p1, p2)
}

func RunPhase(p0 string) int { return postedit.RunPhase(p0) }

func SetDiscardClockForTest(p0 func() time.Time) func() { return postedit.SetDiscardClockForTest(p0) }

func ShadowWorld() shadow.World { return postedit.ShadowWorld() }

func UndercoverBashDecision(p0 []byte) Decision { return postedit.UndercoverBashDecision(p0) }

func WaitDeferredEditJob(p0 string) (string, bool) { return postedit.WaitDeferredEditJob(p0) }

func Waived(p0 string) bool { return postedit.Waived(p0) }

func WallNames() string { return postedit.WallNames() }

func WorktreeAdvisory(p0 []byte) Decision { return postedit.WorktreeAdvisory(p0) }

func deferredExpired(p0 DeferredJob, p1 time.Time) bool { return postedit.DeferredExpired(p0, p1) }

func deferredResult(p0 DeferredJob) (PhaseOutcome, bool) { return postedit.DeferredResult(p0) }

func loadDeferredJob(p0 string, p1 string) (DeferredJob, bool) {
	return postedit.LoadDeferredJob(p0, p1)
}

func promptHarvest(p0 string) string { return postedit.PromptHarvest(p0) }

func reapSessionDeferredJobs(p0 string) int { return postedit.ReapSessionDeferredJobs(p0) }

func setPrimaryEdits(p0 string, p1 bool) error { return postedit.SetPrimaryEdits(p0, p1) }
