// Code generated by tddsplit. DO NOT EDIT.

package tdd

import (
	core "github.com/aphrollo/aphrollo-tools/internal/tdd/core"
	io "io"
	exec "os/exec"
	time "time"
)

const Allow = core.Allow

const Block = core.Block

const CmdName = core.CmdName

const Ignore = core.Ignore

const LegacyCmdName = core.LegacyCmdName

const Source = core.Source

const StateSchema = core.StateSchema

const Test = core.Test

const WallPrimary = core.WallPrimary

const Warn = core.Warn

const premergeDisplayName = core.PremergeDisplayName

const sharedLockFileMode = core.SharedLockFileMode

type Action = core.Action

type Decision = core.Decision

type GateResult = core.GateResult

type Kind = core.Kind

type Outcome = core.Outcome

type Runner = core.Runner

type bashSnapshot = core.BashSnapshot

type fingerprint = core.Fingerprint

type gateEntry = core.GateEntry

type projectState = core.ProjectState

type sessionState = core.SessionState

type waiverEntry = core.WaiverEntry

var errNoSession = core.ErrNoSession

var ignoredDirs = core.IgnoredDirs

var sourceExts = core.SourceExts

func AppendGateLog(p0 string, p1 string, p2 string, p3 string, p4 time.Duration) {
	core.AppendGateLog(p0, p1, p2, p3, p4)
}

func ClassifyFile(p0 string) Kind { return core.ClassifyFile(p0) }

func GateLogNewerSchema() (int, bool) { return core.GateLogNewerSchema() }

func GateLogPath() string { return core.GateLogPath() }

func LogToken(p0 string) string { return core.LogToken(p0) }

func MergeRejectedMarkerPath(p0 string) string { return core.MergeRejectedMarkerPath(p0) }

func SessionID() string { return core.SessionID() }

func StateDir() string { return core.StateDir() }

func TryAcquireFileLock(p0 string) (func(), bool) { return core.TryAcquireFileLock(p0) }

func WriteMergeRejectedMarker(p0 string, p1 string) { core.WriteMergeRejectedMarker(p0, p1) }

func acquirePathLock(p0 string) func() { return core.AcquirePathLock(p0) }

func aphrolloTomlFlag(p0 string, p1 string) bool { return core.AphrolloTomlFlag(p0, p1) }

func aphrolloTomlString(p0 string, p1 string) (string, bool) { return core.AphrolloTomlString(p0, p1) }

func cargoPackageName(p0 string) string { return core.CargoPackageName(p0) }

func claudeConfigDir() string { return core.ClaudeConfigDir() }

func commonGitDir(p0 string) string { return core.CommonGitDir(p0) }

func computeFingerprint(p0 string) *fingerprint { return core.ComputeFingerprint(p0) }

func dedupeSorted(p0 []string) []string { return core.DedupeSorted(p0) }

func ensureSharedSubdir(p0 string) error { return core.EnsureSharedSubdir(p0) }

func everySessionID() []string { return core.EverySessionID() }

func fileExists(p0 string) bool { return core.FileExists(p0) }

func firstLine(p0 string) string { return core.FirstLine(p0) }

func fitRunes(p0 string, p1 int) string { return core.FitRunes(p0, p1) }

func formatBytes(p0 int64) string { return core.FormatBytes(p0) }

func formatDays(p0 time.Duration) string { return core.FormatDays(p0) }

func formatElapsedSecs(p0 time.Duration) string { return core.FormatElapsedSecs(p0) }

func gateLogStageToken(p0 string) string { return core.GateLogStageToken(p0) }

func goEmbedsFile(p0 string) bool { return core.GoEmbedsFile(p0) }

func loadSession(p0 string) (*sessionState, string) { return core.LoadSession(p0) }

func logf(p0 io.Writer, p1 string, p2 ...any) { core.Logf(p0, p1, p2...) }

func markWorktreeWarned(p0 string) bool { return core.MarkWorktreeWarned(p0) }

func mask(p0 string) string { return core.Mask(p0) }

func maskTokens(p0 string, p1 bool, p2 bool, p3 bool) string { return core.MaskTokens(p0, p1, p2, p3) }

func mutantsLogDir(p0 string) string { return core.MutantsLogDir(p0) }

func normalizeProjectPath(p0 string) string { return core.NormalizeProjectPath(p0) }

func normalizeRepoSpelling(p0 string) string { return core.NormalizeRepoSpelling(p0) }

func parseGateLine(p0 string) (gateEntry, bool) { return core.ParseGateLine(p0) }

func pidRunningFn(p0 int) bool { return core.PidRunningFn(p0) }

func plural(p0 int) string { return core.Plural(p0) }

func primaryCheckoutRoot(p0 string) string { return core.PrimaryCheckoutRoot(p0) }

func projectKey(p0 string) string { return core.ProjectKey(p0) }

func quotedWords(p0 string) []string { return core.QuotedWords(p0) }

func readStateJSON(p0 string, p1 any) (bool, bool) { return core.ReadStateJSON(p0, p1) }

func repoStateKey(p0 string) string { return core.RepoStateKey(p0) }

func samePath(p0 string, p1 string) bool { return core.SamePath(p0, p1) }

func sameProject(p0 string, p1 string) bool { return core.SameProject(p0, p1) }

func setOff(p0 string, p1 bool) error { return core.SetOff(p0, p1) }

func setWaiver(p0 string, p1 string, p2 bool) error { return core.SetWaiver(p0, p1, p2) }

func shellPath(p0 string) string { return core.ShellPath(p0) }

func silentStdio(p0 *exec.Cmd) func() { return core.SilentStdio(p0) }

func sortStrings(p0 []string) { core.SortStrings(p0) }

func stripQuoted(p0 string) string { return core.StripQuoted(p0) }

func tomlArrayCommaError(p0 string, p1 string, p2 string) error {
	return core.TomlArrayCommaError(p0, p1, p2)
}

func tomlBoolIn(p0 string, p1 string, p2 string) bool { return core.TomlBoolIn(p0, p1, p2) }

func tomlBoolSetIn(p0 string, p1 string, p2 string) (bool, bool) {
	return core.TomlBoolSetIn(p0, p1, p2)
}

func tomlStringIn(p0 string, p1 string, p2 string) (string, bool) {
	return core.TomlStringIn(p0, p1, p2)
}

func tomlStringsIn(p0 string, p1 string, p2 string) []string { return core.TomlStringsIn(p0, p1, p2) }

func waivedForSession(p0 string, p1 string) bool { return core.WaivedForSession(p0, p1) }

func warnGateLogUnwritable(p0 string) { core.WarnGateLogUnwritable(p0) }

func writeFileAtomic(p0 string, p1 []byte) error { return core.WriteFileAtomic(p0, p1) }
