// Code generated by tddsplit. DO NOT EDIT.

package tdd

import (
	core "github.com/aphrollo/aphrollo-tools/internal/tdd/core"
)

const premergeLogToken = core.PremergeLogToken

const sessionCodeEnv = core.SessionCodeEnv

const sessionEnv = core.SessionEnv

type Action = core.Action
