// Code generated by tddsplit. DO NOT EDIT.

package tdd

import (
	lock "github.com/aphrollo/aphrollo-tools/internal/tdd/lock"
	time "time"
)

const BuildLockHeldEnv = lock.BuildLockHeldEnv

type BuildLockOwner = lock.BuildLockOwner

type BuildSlot = lock.BuildSlot

type BuildSlotStatus = lock.BuildSlotStatus

type QueueWaiter = lock.QueueWaiter

func AcquireLintLock(p0 string, p1 string, p2 time.Duration) (func(), time.Duration, bool, bool) {
	return lock.AcquireLintLock(p0, p1, p2)
}

func EnvWithBuildJobs(p0 []string, p1 int) []string { return lock.EnvWithBuildJobs(p0, p1) }

func LintLockHolderDescription() string { return lock.LintLockHolderDescription() }

func QueueWaitersForRoot(p0 string) []QueueWaiter { return lock.QueueWaitersForRoot(p0) }

func ReadBuildSlotOwner(p0 string) (BuildLockOwner, bool) { return lock.ReadBuildSlotOwner(p0) }

func ReadFileLockOwner(p0 string) (BuildLockOwner, bool) { return lock.ReadFileLockOwner(p0) }

func RemoveFileLockOwner(p0 string) { lock.RemoveFileLockOwner(p0) }

func ResolveCargoTargetDir(p0 string) string { return lock.ResolveCargoTargetDir(p0) }

func SetBuildLockPathForTest(p0 string) func() { return lock.SetBuildLockPathForTest(p0) }

func SetLockDirForTest(p0 string) func() { return lock.SetLockDirForTest(p0) }

func SetPrecommitLockWait(p0 time.Duration) func() { return lock.SetPrecommitLockWait(p0) }

func SlotTokenEnvEntry(p0 BuildSlot) string { return lock.SlotTokenEnvEntry(p0) }

func SlotTokenEnvName() string { return lock.SlotTokenEnvName() }

func SnapshotBuildSlots() []BuildSlotStatus { return lock.SnapshotBuildSlots() }

func TryAcquireBuildSlot(p0 string, p1 string, p2 string) (BuildSlot, func(), bool) {
	return lock.TryAcquireBuildSlot(p0, p1, p2)
}

func TryAcquireLintLock(p0 string, p1 string) (func(), bool) { return lock.TryAcquireLintLock(p0, p1) }

func TryAcquireLongVerbSlot(p0 string, p1 string, p2 string) (BuildSlot, func(), func(), bool) {
	return lock.TryAcquireLongVerbSlot(p0, p1, p2)
}

func WriteFileLockOwner(p0 string, p1 string, p2 string) { lock.WriteFileLockOwner(p0, p1, p2) }

func WriteQueueWaiter(p0 string, p1 string, p2 string) func() {
	return lock.WriteQueueWaiter(p0, p1, p2)
}

func buildSlotHolderDescription(p0 string) string { return lock.BuildSlotHolderDescription(p0) }

func describeOwner(p0 BuildLockOwner) string { return lock.DescribeOwner(p0) }

func readBuildLockOwnerAt(p0 string) (BuildLockOwner, bool) { return lock.ReadBuildLockOwnerAt(p0) }
