// Code generated by tddsplit. DO NOT EDIT.

//go:build !windows

package tdd

import (
	gitx "github.com/aphrollo/aphrollo-tools/internal/tdd/gitx"
)

func cleanGitEnv() []string { return gitx.CleanGitEnv() }

func gitOut(p0 string, p1 ...string) string { return gitx.GitOut(p0, p1...) }
