// Code generated by tddsplit. DO NOT EDIT.

package tdd

import (
	lawgate "github.com/aphrollo/aphrollo-tools/internal/tdd/lawgate"
)

func existingAncestorDir(p0 string) string { return lawgate.ExistingAncestorDir(p0) }

func stagedTouchesLaws(p0 string) bool { return lawgate.StagedTouchesLaws(p0) }
