// Code generated by tddsplit. DO NOT EDIT.

package tdd

import (
	gitx "github.com/aphrollo/aphrollo-tools/internal/tdd/gitx"
)

const GitQueuedEnv = gitx.GitQueuedEnv

var MergeInProgressRefs = gitx.MergeInProgressRefs

func GitBinaryOnPath() (string, bool) { return gitx.GitBinaryOnPath() }

func RepoRoot(p0 string) string { return gitx.RepoRoot(p0) }

func TrunkBranch(p0 string) string { return gitx.TrunkBranch(p0) }

func cleanGitEnv() []string { return gitx.CleanGitEnv() }

func git(p0 string, p1 ...string) (string, error) { return gitx.Git(p0, p1...) }

func gitBinary() string { return gitx.GitBinary() }

func gitOut(p0 string, p1 ...string) string { return gitx.GitOut(p0, p1...) }

func revTree(p0 string, p1 string) (string, bool) { return gitx.RevTree(p0, p1) }
