// Code generated by tddsplit. DO NOT EDIT.

package tdd

import (
	install "github.com/aphrollo/aphrollo-tools/internal/tdd/install"
)

var gitGateHooks = install.GitGateHooks

var perRepoHooks = install.PerRepoHooks

func PatchSettings(p0 []byte, p1 string) ([]byte, bool, error) { return install.PatchSettings(p0, p1) }

func binShim(p0 string, p1 string, p2 string) string { return install.BinShim(p0, p1, p2) }

func shim(p0 string, p1 string) string { return install.Shim(p0, p1) }
