// Code generated by tddsplit. DO NOT EDIT.

package tdd

import (
	install "github.com/aphrollo/aphrollo-tools/internal/tdd/install"
)

const HooksDirUnsafeEnv = install.HooksDirUnsafeEnv

type InstallPlan = install.InstallPlan

type ShimExeResult = install.ShimExeResult

var ErrManagedBlockInPrimary = install.ErrManagedBlockInPrimary

func BinIsRunnable(p0 string) error { return install.BinIsRunnable(p0) }

func BuildInstallPlan(p0 string, p1 string) (InstallPlan, error) {
	return install.BuildInstallPlan(p0, p1)
}

func ClaudeMDBlock(p0 string, p1 bool, p2 bool) string { return install.ClaudeMDBlock(p0, p1, p2) }

func Doctor(p0 DoctorInput) []DoctorCheck { return install.Doctor(p0) }

func GlobalHooksPath() string { return install.GlobalHooksPath() }

func InitGitGate(p0 string, p1 string, p2 bool) (bool, error) { return install.InitGitGate(p0, p1, p2) }

func InitSettings(p0 string, p1 string, p2 bool) (bool, error) {
	return install.InitSettings(p0, p1, p2)
}

func InstallCargoShim(p0 string, p1 string) (bool, error) { return install.InstallCargoShim(p0, p1) }

func InstallGitShim(p0 string, p1 string) (bool, error) { return install.InstallGitShim(p0, p1) }

func InstallShimExes(p0 string, p1 string) (ShimExeResult, error) {
	return install.InstallShimExes(p0, p1)
}

func ManagedAgent(p0 string) (string, bool) { return install.ManagedAgent(p0) }

func PruneRetiredHooks(p0 string) ([]string, error) { return install.PruneRetiredHooks(p0) }

func RemoveAgents(p0 string) ([]string, error) { return install.RemoveAgents(p0) }

func RemoveCmdShims(p0 string) ([]string, error) { return install.RemoveCmdShims(p0) }

func RemoveSDDSkill(p0 string) (bool, error) { return install.RemoveSDDSkill(p0) }

func RemoveTDDSkill(p0 string) (bool, error) { return install.RemoveTDDSkill(p0) }

func RenderDoctor(p0 []DoctorCheck) (string, int) { return install.RenderDoctor(p0) }

func SDDSkill() string { return install.SDDSkill() }

func StyleBlock() string { return install.StyleBlock() }

func TDDSkill() string { return install.TDDSkill() }

func WriteAgents(p0 string) ([]string, error) { return install.WriteAgents(p0) }

func WriteClaudeMD(p0 string, p1 string, p2 bool) (bool, error) {
	return install.WriteClaudeMD(p0, p1, p2)
}

func WriteManagedHookForTest(p0 string, p1 string, p2 string, p3 string) error {
	return install.WriteManagedHookForTest(p0, p1, p2, p3)
}

func WriteSDDSkill(p0 string) (bool, error) { return install.WriteSDDSkill(p0) }

func WriteTDDSkill(p0 string) (bool, error) { return install.WriteTDDSkill(p0) }

func effectiveReplyStyle(p0 *sessionState) string { return install.EffectiveReplyStyle(p0) }

func replyStyleFor(p0 string) string { return install.ReplyStyleFor(p0) }

func resolvedTDDSkillPath() (string, bool) { return install.ResolvedTDDSkillPath() }

func setReplyStyle(p0 string, p1 string) error { return install.SetReplyStyle(p0, p1) }
