// Code generated by tddsplit. DO NOT EDIT.

package tdd

import (
	suite "github.com/aphrollo/aphrollo-tools/internal/tdd/suite"
)

const InfraFailed = suite.InfraFailed

const NoDelta = suite.NoDelta

const Red = suite.Red

const RedMissingImpl = suite.RedMissingImpl

func stampProvenSuite(p0 string) { suite.StampProvenSuite(p0) }
