// Code generated by tddsplit. DO NOT EDIT.

package tdd

import (
	gc "github.com/aphrollo/aphrollo-tools/internal/tdd/gc"
	time "time"
)

type GCScope = gc.GCScope

func AllGCScopes() GCScope { return gc.AllGCScopes() }

func ApplyGCFor(p0 string, p1 []GCCandidate) (int64, []string, int) { return gc.ApplyGCFor(p0, p1) }

func GCAfterWorktreeChange(p0 string, p1 string) int64 { return gc.GCAfterWorktreeChange(p0, p1) }

func MutantsCopiesInUse(p0 []string) []string { return gc.MutantsCopiesInUse(p0) }

func MutantsTempDirs() []string { return gc.MutantsTempDirs() }

func ParseGCAge(p0 string) (time.Duration, error) { return gc.ParseGCAge(p0) }

func RecordGCSweep(p0 int64, p1 int) { gc.RecordGCSweep(p0, p1) }

func RenderGC(p0 []GCCandidate, p1 bool, p2 int64) string { return gc.RenderGC(p0, p1, p2) }

func ScanGC(p0 string, p1 time.Duration, p2 GCScope) []GCCandidate { return gc.ScanGC(p0, p1, p2) }

func gcReportLine() string { return gc.GcReportLine() }

func maybeStartBackgroundGC(p0 string) { gc.MaybeStartBackgroundGC(p0) }
