// Code generated by tddsplit. DO NOT EDIT.

package tdd

import (
	postedit "github.com/aphrollo/aphrollo-tools/internal/tdd/postedit"
	time "time"
)

const DefaultPostEditTimeout = postedit.DefaultPostEditTimeout

const WallDiscard = postedit.WallDiscard

type DeferredJob = postedit.DeferredJob

type PhaseOutcome = postedit.PhaseOutcome

type Waiver = postedit.Waiver

func ActiveDeferredJobs() []DeferredJob { return postedit.ActiveDeferredJobs() }

func AllowWall(p0 string) (string, error) { return postedit.AllowWall(p0) }

func ConsumeDiscardBashSpent(p0 []string) bool { return postedit.ConsumeDiscardBashSpent(p0) }

func ConsumeOneShot(p0 string) bool { return postedit.ConsumeOneShot(p0) }

func DecideBashSuite(p0 []byte) (Decision, bool) { return postedit.DecideBashSuite(p0) }

func DecidePreEdit(p0 []byte) (Decision, error) { return postedit.DecidePreEdit(p0) }

func DeferredPhasesEnabled() bool { return postedit.DeferredPhasesEnabled() }

func DirectPROpenDecision(p0 []byte) Decision { return postedit.DirectPROpenDecision(p0) }

func DiscardBashDecision(p0 []byte) Decision { return postedit.DiscardBashDecision(p0) }

func EnableDeferredPhases(p0 bool) { postedit.EnableDeferredPhases(p0) }

func IsBashHook(p0 []byte) bool { return postedit.IsBashHook(p0) }

func ListWaivers() []Waiver { return postedit.ListWaivers() }

func LogBashSuiteDecision(p0 []byte, p1 Decision) { postedit.LogBashSuiteDecision(p0, p1) }

func LogEditDecision(p0 []byte, p1 Decision) { postedit.LogEditDecision(p0, p1) }

func LogOverride(p0 string, p1 string, p2 string) { postedit.LogOverride(p0, p1, p2) }

func PostBash(p0 []byte, p1 SuiteRunner) string { return postedit.PostBash(p0, p1) }

func PostEdit(p0 []byte, p1 SuiteRunner) string { return postedit.PostEdit(p0, p1) }

func PostEditBudget() time.Duration { return postedit.PostEditBudget() }

func PreBash(p0 []byte) { postedit.PreBash(p0) }

func PrimaryCheckoutDecision(p0 []byte) Decision { return postedit.PrimaryCheckoutDecision(p0) }

func PrimaryEditsAllowed(p0 string) bool { return postedit.PrimaryEditsAllowed(p0) }

func PrimaryMergeOnly(p0 string) (string, bool) { return postedit.PrimaryMergeOnly(p0) }

func PrimaryMergeOnlyReason(p0 string) string { return postedit.PrimaryMergeOnlyReason(p0) }

func RecordFinishedDeferredJobForTest(p0 string, p1 string) {
	postedit.RecordFinishedDeferredJobForTest(p0, p1)
}

func RenderPostToolUse(p0 string) ([]byte, int) { return postedit.RenderPostToolUse(p0) }

func RenderPreToolUse(p0 Decision) ([]byte, int) { return postedit.RenderPreToolUse(p0) }

func Revoke(p0 string) (string, error) { return postedit.Revoke(p0) }

func RunPhase(p0 string) int { return postedit.RunPhase(p0) }

func SetDiscardClockForTest(p0 func() time.Time) func() { return postedit.SetDiscardClockForTest(p0) }

func WaitDeferredEditJob(p0 string) (string, bool) { return postedit.WaitDeferredEditJob(p0) }

func Waived(p0 string) bool { return postedit.Waived(p0) }

func WorktreeAdvisory(p0 []byte) Decision { return postedit.WorktreeAdvisory(p0) }

func deferredExpired(p0 DeferredJob, p1 time.Time) bool { return postedit.DeferredExpired(p0, p1) }

func deferredResult(p0 DeferredJob) (PhaseOutcome, bool) { return postedit.DeferredResult(p0) }

func loadDeferredJob(p0 string, p1 string) (DeferredJob, bool) {
	return postedit.LoadDeferredJob(p0, p1)
}

func promptHarvest(p0 string) string { return postedit.PromptHarvest(p0) }

func reapSessionDeferredJobs(p0 string) int { return postedit.ReapSessionDeferredJobs(p0) }

func setPrimaryEdits(p0 string, p1 bool) error { return postedit.SetPrimaryEdits(p0, p1) }

func waiverAllowedMessage(p0 string) string { return postedit.WaiverAllowedMessage(p0) }

func waiverRevokedMessage(p0 string) string { return postedit.WaiverRevokedMessage(p0) }
