// Code generated by tddsplit. DO NOT EDIT.

package tdd

import (
	gitx "github.com/aphrollo/aphrollo-tools/internal/tdd/gitx"
)

const reflogActionEnv = gitx.ReflogActionEnv

func git(p0 string, p1 ...string) (string, error) { return gitx.Git(p0, p1...) }

func stagedFiles(p0 string) []string { return gitx.StagedFiles(p0) }
