// Code generated by tddsplit. DO NOT EDIT.

package tdd

import (
	core "github.com/aphrollo/aphrollo-tools/internal/tdd/core"
	time "time"
)

const Allow = core.Allow

const Block = core.Block

const CmdName = core.CmdName

const LegacyCmdName = core.LegacyCmdName

const StateSchema = core.StateSchema

const WallPrimary = core.WallPrimary

const Warn = core.Warn

type Decision = core.Decision

type GateResult = core.GateResult

type Outcome = core.Outcome

type Runner = core.Runner

type gateEntry = core.GateEntry

type sessionState = core.SessionState

func AppendGateLog(p0 string, p1 string, p2 string, p3 string, p4 time.Duration) {
	core.AppendGateLog(p0, p1, p2, p3, p4)
}

func GateLogNewerSchema() (int, bool) { return core.GateLogNewerSchema() }

func GateLogPath() string { return core.GateLogPath() }

func LogToken(p0 string) string { return core.LogToken(p0) }

func MergeRejectedMarkerPath(p0 string) string { return core.MergeRejectedMarkerPath(p0) }

func SessionID() string { return core.SessionID() }

func StateDir() string { return core.StateDir() }

func TryAcquireFileLock(p0 string) (func(), bool) { return core.TryAcquireFileLock(p0) }

func WriteMergeRejectedMarker(p0 string, p1 string) { core.WriteMergeRejectedMarker(p0, p1) }

func formatElapsedSecs(p0 time.Duration) string { return core.FormatElapsedSecs(p0) }

func loadSession(p0 string) (*sessionState, string) { return core.LoadSession(p0) }

func parseGateLine(p0 string) (gateEntry, bool) { return core.ParseGateLine(p0) }

func plural(p0 int) string { return core.Plural(p0) }

func repoStateKey(p0 string) string { return core.RepoStateKey(p0) }

func sameProject(p0 string, p1 string) bool { return core.SameProject(p0, p1) }

func setOff(p0 string, p1 bool) error { return core.SetOff(p0, p1) }

func setWaiver(p0 string, p1 string, p2 bool) error { return core.SetWaiver(p0, p1, p2) }

func writeFileAtomic(p0 string, p1 []byte) error { return core.WriteFileAtomic(p0, p1) }
