// Code generated by tddsplit. DO NOT EDIT.

package tdd

import (
	gitx "github.com/aphrollo/aphrollo-tools/internal/tdd/gitx"
)

const realGitEnv = gitx.RealGitEnv

const reflogActionEnv = gitx.ReflogActionEnv

func stagedFiles(p0 string) []string { return gitx.StagedFiles(p0) }
