// Code generated by tddsplit. DO NOT EDIT.

package tdd

import (
	core "github.com/aphrollo/aphrollo-tools/internal/tdd/core"
)

type fingerprint = core.Fingerprint

type projectState = core.ProjectState

func computeFingerprint(p0 string) *fingerprint { return core.ComputeFingerprint(p0) }
