// Code generated by tddsplit. DO NOT EDIT.

package tdd

import (
	lock "github.com/aphrollo/aphrollo-tools/internal/tdd/lock"
	time "time"
)

func SetPostEditLockWaitForTest(p0 time.Duration) func() { return lock.SetPostEditLockWaitForTest(p0) }

func SetSharedLockDirForTest(p0 func() string) func() { return lock.SetSharedLockDirForTest(p0) }

func setBuildLockPathOverride(p0 string) func() { return lock.SetBuildLockPathOverride(p0) }
