// Code generated by tddsplit. DO NOT EDIT.

package tdd

import (
	precommit "github.com/aphrollo/aphrollo-tools/internal/tdd/precommit"
	time "time"
)

const DiffCode = precommit.DiffCode

const DiffCommentOnly = precommit.DiffCommentOnly

const DiffDocsOnly = precommit.DiffDocsOnly

const DiffWorkflowOnly = precommit.DiffWorkflowOnly

type DiffClass = precommit.DiffClass

func ClassifyDiff(p0 string, p1 string, p2 string) (DiffClass, error) {
	return precommit.ClassifyDiff(p0, p1, p2)
}

func Mechanical(p0 string, p1 SuiteRunner) GateResult { return precommit.Mechanical(p0, p1) }

func Precommit(p0 string, p1 SuiteRunner) GateResult { return precommit.Precommit(p0, p1) }

func PrecommitRanSince(p0 string, p1 time.Time) bool { return precommit.PrecommitRanSince(p0, p1) }

func StagedFastPath(p0 string) DiffClass { return precommit.StagedFastPath(p0) }
