// Code generated by tddsplit. DO NOT EDIT.

package tdd

import (
	gitx "github.com/aphrollo/aphrollo-tools/internal/tdd/gitx"
)

const GitQueuedEnv = gitx.GitQueuedEnv

var MergeInProgressRefs = gitx.MergeInProgressRefs

func GitBinaryOnPath() (string, bool) { return gitx.GitBinaryOnPath() }

func RepoRoot(p0 string) string { return gitx.RepoRoot(p0) }

func TrunkBranch(p0 string) string { return gitx.TrunkBranch(p0) }

func gitBinary() string { return gitx.GitBinary() }
