// Code generated by tddsplit. DO NOT EDIT.

package tdd

import (
	lock "github.com/aphrollo/aphrollo-tools/internal/tdd/lock"
	time "time"
)

const BuildLockHeldEnv = lock.BuildLockHeldEnv

type BuildLockOwner = lock.BuildLockOwner

type BuildSlot = lock.BuildSlot

type BuildSlotStatus = lock.BuildSlotStatus

type QueueWaiter = lock.QueueWaiter

type suiteFloor = lock.SuiteFloor

var lintLockDeadline = lock.LintLockDeadline

func AcquireLintLock(p0 string, p1 string, p2 time.Duration) (func(), time.Duration, bool, bool) {
	return lock.AcquireLintLock(p0, p1, p2)
}

func EnvWithBuildJobs(p0 []string, p1 int) []string { return lock.EnvWithBuildJobs(p0, p1) }

func GoTmpRootDir(p0 string) string { return lock.GoTmpRootDir(p0) }

func LintLockHolderDescription() string { return lock.LintLockHolderDescription() }

func QueueWaitersForRoot(p0 string) []QueueWaiter { return lock.QueueWaitersForRoot(p0) }

func ReadBuildSlotOwner(p0 string) (BuildLockOwner, bool) { return lock.ReadBuildSlotOwner(p0) }

func ReadFileLockOwner(p0 string) (BuildLockOwner, bool) { return lock.ReadFileLockOwner(p0) }

func RemoveFileLockOwner(p0 string) { lock.RemoveFileLockOwner(p0) }

func ResolveCargoTargetDir(p0 string) string { return lock.ResolveCargoTargetDir(p0) }

func SetBuildLockPathForTest(p0 string) func() { return lock.SetBuildLockPathForTest(p0) }

func SetLockDirForTest(p0 string) func() { return lock.SetLockDirForTest(p0) }

func SetPrecommitLockWait(p0 time.Duration) func() { return lock.SetPrecommitLockWait(p0) }

func SlotTokenEnvEntry(p0 BuildSlot) string { return lock.SlotTokenEnvEntry(p0) }

func SlotTokenEnvName() string { return lock.SlotTokenEnvName() }

func SnapshotBuildSlots() []BuildSlotStatus { return lock.SnapshotBuildSlots() }

func TryAcquireBuildSlot(p0 string, p1 string, p2 string) (BuildSlot, func(), bool) {
	return lock.TryAcquireBuildSlot(p0, p1, p2)
}

func TryAcquireLintLock(p0 string, p1 string) (func(), bool) { return lock.TryAcquireLintLock(p0, p1) }

func TryAcquireLongVerbSlot(p0 string, p1 string, p2 string) (BuildSlot, func(), func(), bool) {
	return lock.TryAcquireLongVerbSlot(p0, p1, p2)
}

func WriteFileLockOwner(p0 string, p1 string, p2 string) { lock.WriteFileLockOwner(p0, p1, p2) }

func WriteQueueWaiter(p0 string, p1 string, p2 string) func() {
	return lock.WriteQueueWaiter(p0, p1, p2)
}

func acquireBuildSlot(p0 string, p1 time.Duration, p2 string, p3 string) (BuildSlot, func(), bool) {
	return lock.AcquireBuildSlot(p0, p1, p2, p3)
}

func acquireGlobalSlot(p0 time.Duration, p1 string, p2 string) (BuildSlot, func(), bool) {
	return lock.AcquireGlobalSlot(p0, p1, p2)
}

func buildSlotHolderDescription(p0 string) string { return lock.BuildSlotHolderDescription(p0) }

func buildToolPids() ([]int, bool) { return lock.BuildToolPids() }

func cappedFloor(p0 time.Duration, p1 time.Duration) time.Duration { return lock.CappedFloor(p0, p1) }

func cargoWorkspaceRoot(p0 string) string { return lock.CargoWorkspaceRoot(p0) }

func csvPids(p0 string) []int { return lock.CsvPids(p0) }

func describeOwner(p0 BuildLockOwner) string { return lock.DescribeOwner(p0) }

func ensureSharedDir(p0 string) error { return lock.EnsureSharedDir(p0) }

func foreignLoadReport(p0 int) string { return lock.ForeignLoadReport(p0) }

func freeSpaceGB(p0 string) (int, bool) { return lock.FreeSpaceGB(p0) }

func globalCapacityHolderDescription() string { return lock.GlobalCapacityHolderDescription() }

func goRaceLockKey() string { return lock.GoRaceLockKey() }

func goTmpEnv(p0 string) []string { return lock.GoTmpEnv(p0) }

func invalidateFutureStampedArtifacts(p0 string) { lock.InvalidateFutureStampedArtifacts(p0) }

func isSettledVerdict(p0 string) bool { return lock.IsSettledVerdict(p0) }

func lockDir() string { return lock.LockDir() }

func lockLitterDirs() []string { return lock.LockLitterDirs() }

func lockWaitLogAfter() time.Duration { return lock.LockWaitLogAfter() }

func machineAvailGB() int { return lock.MachineAvailGB() }

func machineRAMGB() int { return lock.MachineRAMGB() }

func mutantsMemoryTerm(p0 int, p1 int, p2 int, p3 string) (int, string, string, bool) {
	return lock.MutantsMemoryTerm(p0, p1, p2, p3)
}

func postEditLockWait() time.Duration { return lock.PostEditLockWait() }

func precommitLockWait() time.Duration { return lock.PrecommitLockWait() }

func processExePath(p0 int) (string, bool) { return lock.ProcessExePath(p0) }

func readBuildLockOwnerAt(p0 string) (BuildLockOwner, bool) { return lock.ReadBuildLockOwnerAt(p0) }

func recordedSuiteFloor(p0 string, p1 string) suiteFloor { return lock.RecordedSuiteFloor(p0, p1) }

func removeBuildLockOwnerAt(p0 string) { lock.RemoveBuildLockOwnerAt(p0) }

func runnerTargetDir(p0 Runner, p1 string) string { return lock.RunnerTargetDir(p0, p1) }

func setBuildJobs(p0 int) func() { return lock.SetBuildJobs(p0) }

func targetLockPath(p0 string) string { return lock.TargetLockPath(p0) }

func writeBuildLockOwnerAt(p0 string, p1 string, p2 string) { lock.WriteBuildLockOwnerAt(p0, p1, p2) }

func writeSharedRecord(p0 string, p1 []byte) error { return lock.WriteSharedRecord(p0, p1) }
