// Code generated by tddsplit. DO NOT EDIT.

package tdd

import (
	postedit "github.com/aphrollo/aphrollo-tools/internal/tdd/postedit"
	time "time"
)

const PrimaryEditsEnv = postedit.PrimaryEditsEnv

const deferredMaxEnv = postedit.DeferredMaxEnv

type deferredEditOutcome = postedit.DeferredEditOutcome

func SetKillDeferredForTest(p0 func(j DeferredJob)) func() {
	return postedit.SetKillDeferredForTest(p0)
}

func SetProcessStartTimeForTest(p0 func(pid int) (time.Time, bool)) func() {
	return postedit.SetProcessStartTimeForTest(p0)
}

func SetSpawnPhaseForTest(p0 func(j DeferredJob) (DeferredJob, bool)) func() {
	return postedit.SetSpawnPhaseForTest(p0)
}

func buildingLine(p0 string, p1 string, p2 time.Duration) string {
	return postedit.BuildingLine(p0, p1, p2)
}

func clearDeferredJob(p0 string, p1 string) { postedit.ClearDeferredJob(p0, p1) }

func editResultAdvisory(p0 DeferredJob, p1 PhaseOutcome, p2 string, p3 *sessionState, p4 string, p5 string) string {
	return postedit.EditResultAdvisory(p0, p1, p2, p3, p4, p5)
}

func fileContentHash(p0 string) string { return postedit.FileContentHash(p0) }

func finishedEditOutcome(p0 DeferredJob, p1 PhaseOutcome) deferredEditOutcome {
	return postedit.FinishedEditOutcome(p0, p1)
}

func pidStillOurs(p0 DeferredJob) bool { return postedit.PidStillOurs(p0) }

func saveDeferredJob(p0 DeferredJob) { postedit.SaveDeferredJob(p0) }

func sourceIdentity(p0 string, p1 string) string { return postedit.SourceIdentity(p0, p1) }

func writePhaseResult(p0 string, p1 PhaseOutcome) { postedit.WritePhaseResult(p0, p1) }
