// Code generated by tddsplit. DO NOT EDIT.

package tdd

import (
	merge "github.com/aphrollo/aphrollo-tools/internal/tdd/merge"
	io "io"
)

type PrunedLane = merge.PrunedLane

func CommitMsg(p0 string, p1 string) GateResult { return merge.CommitMsg(p0, p1) }

func GatePRMerge(p0 string, p1 SuiteRunner, p2 io.Writer) error { return merge.GatePRMerge(p0, p1, p2) }

func PostCommitMergeSweep(p0 string, p1 io.Writer, p2 io.Writer) []PrunedLane {
	return merge.PostCommitMergeSweep(p0, p1, p2)
}

func PostMergeSweep(p0 string, p1 io.Writer, p2 io.Writer) []PrunedLane {
	return merge.PostMergeSweep(p0, p1, p2)
}

func PruneMergedLanesAfterMerge(p0 string, p1 string, p2 io.Writer, p3 io.Writer) []PrunedLane {
	return merge.PruneMergedLanesAfterMerge(p0, p1, p2, p3)
}
