// Code generated by tddsplit. DO NOT EDIT.

package tdd

import (
	escape "github.com/aphrollo/aphrollo-tools/internal/tdd/escape"
	io "io"
	time "time"
)

const EscapeKind = escape.EscapeKind

const FalsePositiveKind = escape.FalsePositiveKind

const GateNotesRefFull = escape.GateNotesRefFull

type CIEscapeOptions = escape.CIEscapeOptions

type DemoteCandidate = escape.DemoteCandidate

type EscapeOptions = escape.EscapeOptions

type EscapeRecord = escape.EscapeRecord

type IssueOptions = escape.IssueOptions

type OverrideCandidate = escape.OverrideCandidate

type Stats = escape.Stats

var ErrNoIssueTarget = escape.ErrNoIssueTarget

func CheckIssueLabels(p0 string, p1 []string, p2 bool) error {
	return escape.CheckIssueLabels(p0, p1, p2)
}

func CheckPRCloses(p0 string, p1 string, p2 io.Writer) (bool, error) {
	return escape.CheckPRCloses(p0, p1, p2)
}

func DemoteCandidateLines(p0 []DemoteCandidate) string { return escape.DemoteCandidateLines(p0) }

func DemoteCandidates(p0 io.Reader, p1 time.Time) []DemoteCandidate {
	return escape.DemoteCandidates(p0, p1)
}

func EscapeLogPath() string { return escape.EscapeLogPath() }

func FeedbackBody(p0 string, p1 string) string { return escape.FeedbackBody(p0, p1) }

func GateStats(p0 io.Reader, p1 time.Time) Stats { return escape.GateStats(p0, p1) }

func IssueLabels(p0 string) []string { return escape.IssueLabels(p0) }

func ListEscapes(p0 io.Writer, p1 bool) { escape.ListEscapes(p0, p1) }

func NoteMergeGateEscape(p0 string, p1 string, p2 io.Writer) { escape.NoteMergeGateEscape(p0, p1, p2) }

func OpenEscapes() (int, time.Duration) { return escape.OpenEscapes() }

func OpenIssue(p0 IssueOptions) (string, int, error) { return escape.OpenIssue(p0) }

func OverrideCandidates(p0 io.Reader, p1 time.Time) []OverrideCandidate {
	return escape.OverrideCandidates(p0, p1)
}

func PostCommit(p0 string) { escape.PostCommit(p0) }

func RecordCIEscape(p0 CIEscapeOptions, p1 io.Writer) (EscapeRecord, bool) {
	return escape.RecordCIEscape(p0, p1)
}

func RecordDemoteCandidates(p0 string, p1 []DemoteCandidate, p2 io.Writer) int {
	return escape.RecordDemoteCandidates(p0, p1, p2)
}

func RecordEscape(p0 EscapeOptions, p1 io.Writer) (EscapeRecord, error) {
	return escape.RecordEscape(p0, p1)
}

func RecordOverrideCandidates(p0 string, p1 []OverrideCandidate, p2 io.Writer) int {
	return escape.RecordOverrideCandidates(p0, p1, p2)
}

func RenderGateStats(p0 Stats) string { return escape.RenderGateStats(p0) }

func StampGreenSuiteIfProven(p0 string) { escape.StampGreenSuiteIfProven(p0) }

func SyncEscapes(p0 string, p1 io.Writer) (int, error) { return escape.SyncEscapes(p0, p1) }

func UpstreamRepo(p0 string) string { return escape.UpstreamRepo(p0) }

func VerifyClosure(p0 string, p1 string, p2 io.Writer) (bool, error) {
	return escape.VerifyClosure(p0, p1, p2)
}

func maybeWeeklyDigest(p0 time.Time) string { return escape.MaybeWeeklyDigest(p0) }

func syncClosedEscapes(p0 string) int { return escape.SyncClosedEscapes(p0) }
