// Code generated by tddsplit. DO NOT EDIT.

package tdd

import (
	mutation "github.com/aphrollo/aphrollo-tools/internal/tdd/mutation"
)

const GCKindIncremental = mutation.GCKindIncremental

const GCKindOrphanWorktree = mutation.GCKindOrphanWorktree

type MutantOutcome = mutation.MutantOutcome

func judgeMutants(p0 MutantsConfig, p1 []MutantOutcome) Verdict { return mutation.JudgeMutants(p0, p1) }

func measureLogVerdict(p0 Verdict) string { return mutation.MeasureLogVerdict(p0) }
