// Code generated by tddsplit. DO NOT EDIT.

package tdd

import (
	suite "github.com/aphrollo/aphrollo-tools/internal/tdd/suite"
)

const BuildOnly = suite.BuildOnly

const NotCompiled = suite.NotCompiled

const suiteOutputCap = suite.SuiteOutputCap

type stageOutcomeKind = suite.StageOutcomeKind

type suiteOutputRecord = suite.SuiteOutputRecord

var registeredStages = suite.RegisteredStages

func SetCargoTestTargetsForTest(p0 func(root string) map[string]map[string]bool) func() {
	return suite.SetCargoTestTargetsForTest(p0)
}

func SetCargoWorkspaceDepsForTest(p0 func(root string) (map[string][]string, error)) func() {
	return suite.SetCargoWorkspaceDepsForTest(p0)
}

func SetGoReachGraphForTest(p0 func(root string) (goReachGraph, error)) func() {
	return suite.SetGoReachGraphForTest(p0)
}

func SetGoTestReachForTest(p0 func(root string, dir string) ([]string, error)) func() {
	return suite.SetGoTestReachForTest(p0)
}

func cargoNestedTestFileReachable(p0 string, p1 string) bool {
	return suite.CargoNestedTestFileReachable(p0, p1)
}

func cargoRunnerAt(p0 string, p1 ...string) (Runner, bool) { return suite.CargoRunnerAt(p0, p1...) }

func cargoVacuousTargets(p0 string) []string { return suite.CargoVacuousTargets(p0) }

func classificationOutput(p0 string, p1 string) string { return suite.ClassificationOutput(p0, p1) }

func goRunFilter(p0 []string) string { return suite.GoRunFilter(p0) }

func hasGateProfile(p0 string) bool { return suite.HasGateProfile(p0) }

func loadGoReachGraph(p0 string) (goReachGraph, error) { return suite.LoadGoReachGraph(p0) }

func nextestInstalled() bool { return suite.NextestInstalled() }

func packageHasDoctests(p0 string) bool { return suite.PackageHasDoctests(p0) }

func parseWorkspaceDeps(p0 []byte) (map[string][]string, error) { return suite.ParseWorkspaceDeps(p0) }

func renderGoTestJSON(p0 string) (string, string, bool) { return suite.RenderGoTestJSON(p0) }

func retainSuiteOutput(p0 string, p1 string, p2 string, p3 string, p4 SuiteResult) {
	suite.RetainSuiteOutput(p0, p1, p2, p3, p4)
}

func vacuousGoPackages(p0 string) ([]string, error) { return suite.VacuousGoPackages(p0) }

func writeSuiteOutputRecord(p0 suiteOutputRecord) error { return suite.WriteSuiteOutputRecord(p0) }
