// Code generated by tddsplit. DO NOT EDIT.

package tdd

import (
	smell "github.com/aphrollo/aphrollo-tools/internal/tdd/smell"
)

const commitPhase = smell.CommitPhase

const editPhase = smell.EditPhase

type lang = smell.Lang

type phase = smell.Phase

type policy = smell.Policy

type preToolUseInput = smell.PreToolUseInput

type view = smell.View

var oracleSmells = smell.OracleSmells

var sourcePolicies = smell.SourcePolicies

var suppressionPolicies = smell.SuppressionPolicies

var testOracleWarnings = smell.TestOracleWarnings

var testPolicies = smell.TestPolicies

func addedLines(p0 string, p1 string) map[int]bool { return smell.AddedLines(p0, p1) }

func concatPolicies(p0 ...[]policy) []policy { return smell.ConcatPolicies(p0...) }

func editImages(p0 preToolUseInput, p1 string) (string, string) { return smell.EditImages(p0, p1) }

func evaluateAdded(p0 string, p1 map[int]bool, p2 lang, p3 []policy, p4 phase) Decision {
	return smell.EvaluateAdded(p0, p1, p2, p3, p4)
}

func intersectLines(p0 map[int]bool, p1 map[int]bool) map[int]bool {
	return smell.IntersectLines(p0, p1)
}

func langOf(p0 string) lang { return smell.LangOf(p0) }

func newView(p0 string, p1 lang) view { return smell.NewView(p0, p1) }

func qualityNotesOn(p0 string, p1 string, p2 map[int]bool) []string {
	return smell.QualityNotesOn(p0, p1, p2)
}
