// Code generated by tddsplit. DO NOT EDIT.

package tdd

import (
	host "github.com/aphrollo/aphrollo-tools/internal/integrate/host"
	suite "github.com/aphrollo/aphrollo-tools/internal/tdd/suite"
	time "time"
)

const Green = suite.Green

const redGoesStaleAfter = suite.RedGoesStaleAfter

type SuiteResult = suite.SuiteResult

type SuiteRunner = suite.SuiteRunner

var ghAvailable = suite.GhAvailable

func CargoBuildOnlyArgv(p0 []string) []string { return suite.CargoBuildOnlyArgv(p0) }

func DetectRunner(p0 string) (Runner, bool) { return suite.DetectRunner(p0) }

func FindProjectRoot(p0 string) string { return suite.FindProjectRoot(p0) }

func RetainedSuiteOutput(p0 string) (string, error) { return suite.RetainedSuiteOutput(p0) }

func RunSuite(p0 time.Duration) SuiteRunner { return suite.RunSuite(p0) }

func findRootFrom(p0 string) string { return suite.FindRootFrom(p0) }

func gcStatePath(p0 string) string { return suite.GcStatePath(p0) }

func gitHubHost(p0 string, p1 time.Duration) host.Host { return suite.GitHubHost(p0, p1) }

func hasGitHubRemote(p0 string) bool { return suite.HasGitHubRemote(p0) }
