// Code generated by tddsplit. DO NOT EDIT.

//go:build !windows

package tdd

import (
	lock "github.com/aphrollo/aphrollo-tools/internal/tdd/lock"
)

func globalSlotOwnerPath(p0 int) string { return lock.GlobalSlotOwnerPath(p0) }

func queueWaiterPath(p0 string, p1 int) string { return lock.QueueWaiterPath(p0, p1) }

func queueWaitersDir() string { return lock.QueueWaitersDir() }
