// Code generated by tddsplit. DO NOT EDIT.

package tdd

import (
	context "context"
	mutation "github.com/aphrollo/aphrollo-tools/internal/tdd/mutation"
	io "io"
	time "time"
)

const ExitMutantsProveUsage = mutation.ExitMutantsProveUsage

const MutantsCISkipLine = mutation.MutantsCISkipLine

const MutationGateEnv = mutation.MutationGateEnv

const MutationGateMarked = mutation.MutationGateMarked

const MutationHoldTTL = mutation.MutationHoldTTL

type DoctorCheck = mutation.DoctorCheck

type DoctorInput = mutation.DoctorInput

type GCCandidate = mutation.GCCandidate

type MeasureOpts = mutation.MeasureOpts

type MutantsConfig = mutation.MutantsConfig

type MutantsProveOptions = mutation.MutantsProveOptions

type MutantsRunStatus = mutation.MutantsRunStatus

type MutationHold = mutation.MutationHold

type Verdict = mutation.Verdict

func ApplyMergeLevel(p0 MutantsConfig, p1 Verdict) Verdict { return mutation.ApplyMergeLevel(p0, p1) }

func FormatMutantsRunStatus(p0 MutantsRunStatus, p1 time.Time) string {
	return mutation.FormatMutantsRunStatus(p0, p1)
}

func HoldMutation(p0 string) (MutationHold, error) { return mutation.HoldMutation(p0) }

func JudgeShardReports(p0 string, p1 MutantsConfig, p2 []string, p3 int, p4 string, p5 io.Writer) (Verdict, error) {
	return mutation.JudgeShardReports(p0, p1, p2, p3, p4, p5)
}

func MeasureLane(p0 string, p1 MutantsConfig, p2 MeasureOpts) (Verdict, error) {
	return mutation.MeasureLane(p0, p1, p2)
}

func MutationHoldFor(p0 string) (MutationHold, bool) { return mutation.MutationHoldFor(p0) }

func NoteGitWorldChange(p0 string, p1 string, p2 string, p3 io.Writer) {
	mutation.NoteGitWorldChange(p0, p1, p2, p3)
}

func ParseShardSpec(p0 string) (int, int, error) { return mutation.ParseShardSpec(p0) }

func ReadMutantsConfig(p0 string) (MutantsConfig, error) { return mutation.ReadMutantsConfig(p0) }

func ReplacedBinaryJobsLine(p0 string) string { return mutation.ReplacedBinaryJobsLine(p0) }

func RestoreMutationHold(p0 string) (MutationHold, error) { return mutation.RestoreMutationHold(p0) }

func RunMutantsCommit(p0 string, p1 io.Writer, p2 io.Writer) int {
	return mutation.RunMutantsCommit(p0, p1, p2)
}

func RunMutantsProve(p0 MutantsProveOptions, p1 SuiteRunner, p2 io.Writer, p3 io.Writer) int {
	return mutation.RunMutantsProve(p0, p1, p2, p3)
}

func SetCIRunnerJobsForTest(p0 func() []int) func() { return mutation.SetCIRunnerJobsForTest(p0) }

func SetFreeSpaceForTest(p0 int, p1 bool) func() { return mutation.SetFreeSpaceForTest(p0, p1) }

func SetGitWorldRecorder(p0 func(root string, runner string, evidence string, log io.Writer)) func() {
	return mutation.SetGitWorldRecorder(p0)
}

func SetMutantsExecForTest(p0 func(ctx context.Context, dir string, env []string, argv []string, log io.Writer) (int, error)) func() {
	return mutation.SetMutantsExecForTest(p0)
}

func SetMutantsGOOSForTest(p0 string) func() { return mutation.SetMutantsGOOSForTest(p0) }

func SetMutantsShardsForTest(p0 int) func() { return mutation.SetMutantsShardsForTest(p0) }

func SetMutationHoldClockForTest(p0 func() time.Time) func() {
	return mutation.SetMutationHoldClockForTest(p0)
}

func SnapshotMutantsRun() MutantsRunStatus { return mutation.SnapshotMutantsRun() }

func TempTargetsInUse(p0 []string) []string { return mutation.TempTargetsInUse(p0) }

func mutantsRunLockOwnerPath() string { return mutation.MutantsRunLockOwnerPath() }
