// Code generated by tddsplit. DO NOT EDIT.

package tdd

import (
	gc "github.com/aphrollo/aphrollo-tools/internal/tdd/gc"
	time "time"
)

func SetGCSpawnForTest(p0 func(cwd string)) func() { return gc.SetGCSpawnForTest(p0) }

func gcDue(p0 time.Time) bool { return gc.GcDue(p0) }

func gcStaleGateDirs(p0 string) []GCCandidate { return gc.GcStaleGateDirs(p0) }

func stampGC(p0 time.Time) { gc.StampGC(p0) }

func writeGCReport(p0 int64, p1 int) { gc.WriteGCReport(p0, p1) }
