// Code generated by tddsplit. DO NOT EDIT.

package tdd

import (
	failfirst "github.com/aphrollo/aphrollo-tools/internal/tdd/failfirst"
)

const DefaultPrecommitTimeout = failfirst.DefaultPrecommitTimeout

const gcOriginFile = failfirst.GcOriginFile
