// Code generated by tddsplit. DO NOT EDIT.

package tdd

import (
	tddtest "github.com/aphrollo/aphrollo-tools/internal/tdd/internal/tddtest"
	testing "testing"
	time "time"
)

var tempEnvKeys = tddtest.TempEnvKeys

func bashPayload(t *testing.T, session, cwd, command string) []byte {
	t.Helper()
	return tddtest.BashPayload(t, session, cwd, command)
}

func commitInitial(t *testing.T, repo string) { t.Helper(); tddtest.CommitInitial(t, repo) }

func decide(t *testing.T, payload string) Decision {
	t.Helper()
	return tddtest.Decide(t, payload, DecidePreEdit)
}

func fakeGitShim(t *testing.T) (dir, marker string) { t.Helper(); return tddtest.FakeGitShim(t) }

func fakeRun(passed bool, output string) SuiteRunner {
	return tddtest.FakeRun[Runner](SuiteResult{Passed: passed, Output: output})
}

func ghArgv(t *testing.T, log string) string { t.Helper(); return tddtest.GhArgv(t, log) }

func gitDo(t *testing.T, dir string, args ...string) { t.Helper(); tddtest.GitDo(t, dir, args...) }

func gitInit(t *testing.T, dir string) { t.Helper(); tddtest.GitInit(t, dir) }

func gitValue(t *testing.T, dir string, args ...string) string {
	t.Helper()
	return tddtest.GitValue(t, dir, args...)
}

func goPrimaryWithLane(t *testing.T) (primary, lane string) {
	t.Helper()
	return tddtest.GoPrimaryWithLane(t)
}

func lawTree(t *testing.T, severity string) string { t.Helper(); return tddtest.LawTree(t, severity) }

func makeCargoRepo(t *testing.T) string { t.Helper(); return tddtest.MakeCargoRepo(t) }

func makeGitHubRepo(t *testing.T) string { t.Helper(); return tddtest.MakeGitHubRepo(t) }

func makeGoMeasureRepo(t *testing.T) (root, base string) {
	t.Helper()
	return tddtest.MakeGoMeasureRepo(t)
}

func makeGoRepo(t *testing.T) string { t.Helper(); return tddtest.MakeGoRepo(t) }

func mkFile(t *testing.T, path, content string, age time.Duration) {
	t.Helper()
	tddtest.MkFile(t, path, content, age)
}

func mkProject(t *testing.T, markers ...string) string {
	t.Helper()
	return tddtest.MkProject(t, markers...)
}

func msgFile(t *testing.T, body string) string { t.Helper(); return tddtest.MsgFile(t, body) }

func mustWrite(t *testing.T, path, content string) { t.Helper(); tddtest.MustWrite(t, path, content) }

func postPayload(tool, file string) []byte { return tddtest.PostPayload(tool, file) }

func ratchetPayload(t *testing.T, tool, path string, fields map[string]any) []byte {
	t.Helper()
	return tddtest.RatchetPayload(t, tool, path, fields)
}

func readEscapes(t *testing.T) []EscapeRecord {
	t.Helper()
	return tddtest.ReadEscapes[EscapeRecord](t, EscapeLogPath())
}

func skillPath(dir string) string { return tddtest.SkillPath(dir) }

func stamp(at time.Time, stage, root, cmd, verdict string, secs float64) string {
	return tddtest.Stamp(at, stage, root, cmd, verdict, secs, formatFloat)
}

func stubGh(t *testing.T, stdout string) (argvLog string) {
	t.Helper()
	return tddtest.StubGh(t, stdout)
}

func stubGhScript(t *testing.T, responses map[string]string) (argvLog string) {
	t.Helper()
	return tddtest.StubGhScript(t, responses)
}

func undercoverRepo(t *testing.T, on bool) string { t.Helper(); return tddtest.UndercoverRepo(t, on) }

func withIsolatedBuildLock(t *testing.T) {
	t.Helper()
	tddtest.IsolateBuildLock(t, setBuildLockPathOverride, SetPostEditLockWaitForTest, SetPrecommitLockWait)
}

func write(t *testing.T, dir, rel, content string) { t.Helper(); tddtest.Write(t, dir, rel, content) }
