// Code generated by tddsplit. DO NOT EDIT.

package postedit

import (
	failfirst "github.com/aphrollo/aphrollo-tools/internal/tdd/failfirst"
)

func headSHAFor(p0 string) string { return failfirst.HeadSHAFor(p0) }

func pytestExecRunner(p0 string, p1 Runner) (Runner, string) {
	return failfirst.PytestExecRunner(p0, p1)
}

func pytestRemedyRoot(p0 string) string { return failfirst.PytestRemedyRoot(p0) }

func readFailFirstEnv(p0 string) []string { return failfirst.ReadFailFirstEnv(p0) }

func recordEdit(p0 string, p1 string) string { return failfirst.RecordEdit(p0, p1) }

func recordEditVerdict(p0 string, p1 string, p2 string, p3 Outcome, p4 string) {
	failfirst.RecordEditVerdict(p0, p1, p2, p3, p4)
}

func recordEdits(p0 string, p1 []string) string { return failfirst.RecordEdits(p0, p1) }
