// Code generated by tddsplit. DO NOT EDIT.

package postedit

import (
	core "github.com/aphrollo/aphrollo-tools/internal/tdd/core"
	exec "os/exec"
	time "time"
)

const Allow = core.Allow

const Block = core.Block

const CmdName = core.CmdName

const Ignore = core.Ignore

const Source = core.Source

const StateSchema = core.StateSchema

const Test = core.Test

const WallPrimary = core.WallPrimary

const Warn = core.Warn

type Decision = core.Decision

type Kind = core.Kind

type Outcome = core.Outcome

type Runner = core.Runner

type bashSnapshot = core.BashSnapshot

type fingerprint = core.Fingerprint

type gateEntry = core.GateEntry

type projectState = core.ProjectState

type sessionState = core.SessionState

type waiverEntry = core.WaiverEntry

var errNoSession = core.ErrNoSession

func AppendGateLog(p0 string, p1 string, p2 string, p3 string, p4 time.Duration) {
	core.AppendGateLog(p0, p1, p2, p3, p4)
}

func ClassifyFile(p0 string) Kind { return core.ClassifyFile(p0) }

func LogToken(p0 string) string { return core.LogToken(p0) }

func SessionID() string { return core.SessionID() }

func StateDir() string { return core.StateDir() }

func acquirePathLock(p0 string) func() { return core.AcquirePathLock(p0) }

func commonGitDir(p0 string) string { return core.CommonGitDir(p0) }

func computeFingerprint(p0 string) *fingerprint { return core.ComputeFingerprint(p0) }

func dedupeSorted(p0 []string) []string { return core.DedupeSorted(p0) }

func everySessionID() []string { return core.EverySessionID() }

func firstLine(p0 string) string { return core.FirstLine(p0) }

func formatDays(p0 time.Duration) string { return core.FormatDays(p0) }

func loadSession(p0 string) (*sessionState, string) { return core.LoadSession(p0) }

func markWorktreeWarned(p0 string) bool { return core.MarkWorktreeWarned(p0) }

func mask(p0 string) string { return core.Mask(p0) }

func normalizeProjectPath(p0 string) string { return core.NormalizeProjectPath(p0) }

func parseGateLine(p0 string) (gateEntry, bool) { return core.ParseGateLine(p0) }

func projectKey(p0 string) string { return core.ProjectKey(p0) }

func readStateJSON(p0 string, p1 any) (bool, bool) { return core.ReadStateJSON(p0, p1) }

func samePath(p0 string, p1 string) bool { return core.SamePath(p0, p1) }

func sameProject(p0 string, p1 string) bool { return core.SameProject(p0, p1) }

func setWaiver(p0 string, p1 string, p2 bool) error { return core.SetWaiver(p0, p1, p2) }

func shellPath(p0 string) string { return core.ShellPath(p0) }

func silentStdio(p0 *exec.Cmd) func() { return core.SilentStdio(p0) }

func waivedForSession(p0 string, p1 string) bool { return core.WaivedForSession(p0, p1) }

func writeFileAtomic(p0 string, p1 []byte) error { return core.WriteFileAtomic(p0, p1) }
