// Code generated by tddsplit. DO NOT EDIT.

package postedit

import (
	suite "github.com/aphrollo/aphrollo-tools/internal/tdd/suite"
	time "time"
)

const Green = suite.Green

const GreenUnconstrained = suite.GreenUnconstrained

const InfraFailed = suite.InfraFailed

const NoDelta = suite.NoDelta

const NoTestsSelected = suite.NoTestsSelected

const RedBogus = suite.RedBogus

const RedMissingImpl = suite.RedMissingImpl

const WritingTest = suite.WritingTest

const bashSuiteVerdictFreshFor = suite.BashSuiteVerdictFreshFor

const narrowedSuiteInvocation = suite.NarrowedSuiteInvocation

const notSuiteInvocation = suite.NotSuiteInvocation

type SuiteResult = suite.SuiteResult

type SuiteRunner = suite.SuiteRunner

type runScope = suite.RunScope

type suiteShape = suite.SuiteShape

var noTestsToRunRe = suite.NoTestsToRunRe

func ClassifyOutcome(p0 bool, p1 string, p2 []string) Outcome {
	return suite.ClassifyOutcome(p0, p1, p2)
}

func DetectRunner(p0 string) (Runner, bool) { return suite.DetectRunner(p0) }

func ExtractFailingTests(p0 string) []string { return suite.ExtractFailingTests(p0) }

func FindProjectRoot(p0 string) string { return suite.FindProjectRoot(p0) }

func IsToolMissing(p0 string) bool { return suite.IsToolMissing(p0) }

func NarrowToRelatedTests(p0 Runner, p1 string, p2 string) Runner {
	return suite.NarrowToRelatedTests(p0, p1, p2)
}

func StartFailure(p0 error, p1 string, p2 func() string, p3 string) string {
	return suite.StartFailure(p0, p1, p2, p3)
}

func attemptedScope(p0 string) runScope { return suite.AttemptedScope(p0) }

func buildOnlyTerminal(p0 Runner, p1 string, p2 SuiteResult) string {
	return suite.BuildOnlyTerminal(p0, p1, p2)
}

func cacheableAsOne(p0 Runner) bool { return suite.CacheableAsOne(p0) }

func cachedGoPackages(p0 string) int { return suite.CachedGoPackages(p0) }

func cargoIntegrationTargetsNotRun(p0 Runner, p1 string) []string {
	return suite.CargoIntegrationTargetsNotRun(p0, p1)
}

func classifyRunOutcome(p0 Runner, p1 string, p2 SuiteResult, p3 []string) Outcome {
	return suite.ClassifyRunOutcome(p0, p1, p2, p3)
}

func classifySuiteSegment(p0 []string) suiteShape { return suite.ClassifySuiteSegment(p0) }

func cmdString(p0 Runner) string { return suite.CmdString(p0) }

func dropLeadingEnvAssignmentWords(p0 []shellWord) []shellWord {
	return suite.DropLeadingEnvAssignmentWords(p0)
}

func editSelectMode(p0 string) string { return suite.EditSelectMode(p0) }

func effectiveRunRoot(p0 string, p1 string) string { return suite.EffectiveRunRoot(p0, p1) }

func findRootFrom(p0 string) string { return suite.FindRootFrom(p0) }

func foreignBuildAdvisory(p0 string, p1 string, p2 string, p3 SuiteResult) string {
	return suite.ForeignBuildAdvisory(p0, p1, p2, p3)
}

func gitRead(p0 string, p1 ...string) (string, error) { return suite.GitRead(p0, p1...) }

func goLintRunner(p0 string, p1 []string) Runner { return suite.GoLintRunner(p0, p1) }

func goPassedCount(p0 string) (int, bool) { return suite.GoPassedCount(p0) }

func goTestReachFn(p0 string, p1 string) ([]string, error) { return suite.GoTestReachFn(p0, p1) }

func hasNoRunFlag(p0 []string) bool { return suite.HasNoRunFlag(p0) }

func isEnvAssignment(p0 string) bool { return suite.IsEnvAssignment(p0) }

func isGoTestInvocation(p0 string, p1 []string) bool { return suite.IsGoTestInvocation(p0, p1) }

func logSuiteVerdictWith(p0 string, p1 string, p2 string, p3 string, p4 SuiteResult, p5 map[string]string) {
	suite.LogSuiteVerdictWith(p0, p1, p2, p3, p4, p5)
}

func mechCacheAddUnmoved(p0 string, p1 string, p2 Runner) { suite.MechCacheAddUnmoved(p0, p1, p2) }

func mechCacheHit(p0 string) bool { return suite.MechCacheHit(p0) }

func mechKey(p0 string, p1 string, p2 Runner) string { return suite.MechKey(p0, p1, p2) }

func missingModuleTerminal(p0 Runner, p1 string, p2 func(root string) string, p3 SuiteResult) string {
	return suite.MissingModuleTerminal(p0, p1, p2, p3)
}

func nodeToolRunner(p0 string, p1 Runner) (Runner, string) { return suite.NodeToolRunner(p0, p1) }

func notCompiledTerminal(p0 Runner, p1 string, p2 string, p3 SuiteResult) string {
	return suite.NotCompiledTerminal(p0, p1, p2, p3)
}

func notRunClause(p0 []string, p1 string) string { return suite.NotRunClause(p0, p1) }

func runCargoLocked(p0 SuiteRunner, p1 Runner, p2 string, p3 time.Duration, p4 time.Duration, p5 time.Duration) (SuiteResult, time.Duration, bool) {
	return suite.RunCargoLocked(p0, p1, p2, p3, p4, p5)
}

func runnerDir(p0 Runner, p1 string) string { return suite.RunnerDir(p0, p1) }

func runnerTimeoutsOnly(p0 string) bool { return suite.RunnerTimeoutsOnly(p0) }

func selectedZeroTests(p0 Runner, p1 SuiteResult) bool { return suite.SelectedZeroTests(p0, p1) }

func splitFlagValue(p0 string) (string, string, bool) { return suite.SplitFlagValue(p0) }

func staleArtifactHint(p0 string, p1 string) string { return suite.StaleArtifactHint(p0, p1) }

func suiteEnv(p0 Runner, p1 string) []string { return suite.SuiteEnv(p0, p1) }

func unownedEdit(p0 Runner, p1 string, p2 string) string { return suite.UnownedEdit(p0, p1, p2) }

func verdictCoversRun(p0 gateEntry, p1 runScope) bool { return suite.VerdictCoversRun(p0, p1) }

func wholeRunScope() runScope { return suite.WholeRunScope() }

func withSelectedTests(p0 Runner, p1 []string, p2 int, p3 []string) Runner {
	return suite.WithSelectedTests(p0, p1, p2, p3)
}

func withTestCache(p0 Runner, p1 string, p2 string) Runner { return suite.WithTestCache(p0, p1, p2) }

func worktreeStateHash(p0 string) string { return suite.WorktreeStateHash(p0) }

func worktreeStateHashInBatch(p0 string) string { return suite.WorktreeStateHashInBatch(p0) }

func zigTestLines(p0 string) map[int]bool { return suite.ZigTestLines(p0) }
