// Code generated by tddsplit. DO NOT EDIT.

package postedit

import (
	core "github.com/aphrollo/aphrollo-tools/internal/tdd/core"
)

const sessionCodeEnv = core.SessionCodeEnv

const sessionEnv = core.SessionEnv

type Action = core.Action

func GateLogNewerSchema() (int, bool) { return core.GateLogNewerSchema() }

func GateLogPath() string { return core.GateLogPath() }
