// Code generated by tddsplit. DO NOT EDIT.

package postedit

import (
	gitx "github.com/aphrollo/aphrollo-tools/internal/tdd/gitx"
)

func RepoRoot(p0 string) string { return gitx.RepoRoot(p0) }

func gitOut(p0 string, p1 ...string) string { return gitx.GitOut(p0, p1...) }

func mergeInProgressRef(p0 string) string { return gitx.MergeInProgressRef(p0) }

func stagedFiles(p0 string) []string { return gitx.StagedFiles(p0) }

func trunkSyncTip(p0 string) (string, bool) { return gitx.TrunkSyncTip(p0) }
