// Code generated by tddsplit. DO NOT EDIT.

package postedit

import (
	lawgate "github.com/aphrollo/aphrollo-tools/internal/tdd/lawgate"
)

type LawFinding = lawgate.LawFinding

func editLawRefusalHits(p0 string, p1 []string) ([]string, []LawFinding) {
	return lawgate.EditLawRefusalHits(p0, p1)
}

func existingAncestorDir(p0 string) string { return lawgate.ExistingAncestorDir(p0) }

func repoRootNear(p0 string) string { return lawgate.RepoRootNear(p0) }
