// Code generated by tddsplit. DO NOT EDIT.

package postedit

import (
	smell "github.com/aphrollo/aphrollo-tools/internal/tdd/smell"
)

func QualityNotes(p0 string, p1 string) []string { return smell.QualityNotes(p0, p1) }
