// Code generated by tddsplit. DO NOT EDIT.

package postedit

import (
	suite "github.com/aphrollo/aphrollo-tools/internal/tdd/suite"
	time "time"
)

const BuildOnly = suite.BuildOnly

const NotCompiled = suite.NotCompiled

const Red = suite.Red

func RetainedSuiteOutput(p0 string) (string, error) { return suite.RetainedSuiteOutput(p0) }

func RunSuite(p0 time.Duration) SuiteRunner { return suite.RunSuite(p0) }

func SetGoTestReachForTest(p0 func(root string, dir string) ([]string, error)) func() {
	return suite.SetGoTestReachForTest(p0)
}

func cargoNestedTestFileReachable(p0 string, p1 string) bool {
	return suite.CargoNestedTestFileReachable(p0, p1)
}

func classificationOutput(p0 string, p1 string) string { return suite.ClassificationOutput(p0, p1) }

func mechCacheAdd(p0 string) { suite.MechCacheAdd(p0) }

func mechCachePath() string { return suite.MechCachePath() }

func renderGoTestJSON(p0 string) (string, string, bool) { return suite.RenderGoTestJSON(p0) }

func retainSuiteOutput(p0 string, p1 string, p2 string, p3 string, p4 SuiteResult) {
	suite.RetainSuiteOutput(p0, p1, p2, p3, p4)
}
