// Code generated by tddsplit. DO NOT EDIT.

package postedit

import (
	lock "github.com/aphrollo/aphrollo-tools/internal/tdd/lock"
	time "time"
)

func ResolveCargoTargetDir(p0 string) string { return lock.ResolveCargoTargetDir(p0) }

func SetPostEditLockWaitForTest(p0 time.Duration) func() { return lock.SetPostEditLockWaitForTest(p0) }

func SetPrecommitLockWait(p0 time.Duration) func() { return lock.SetPrecommitLockWait(p0) }

func SetSlotRequestQueuedHookForTest(p0 func(path string)) func() {
	return lock.SetSlotRequestQueuedHookForTest(p0)
}

func TryAcquireBuildSlot(p0 string, p1 string, p2 string) (BuildSlot, func(), bool) {
	return lock.TryAcquireBuildSlot(p0, p1, p2)
}

func buildSlotCount() int { return lock.BuildSlotCount() }

func setBuildLockPathOverride(p0 string) func() { return lock.SetBuildLockPathOverride(p0) }
