// Code generated by tddsplit. DO NOT EDIT.

package postedit

import (
	core "github.com/aphrollo/aphrollo-tools/internal/tdd/core"
)

const sessionCodeEnv = core.SessionCodeEnv

const sessionEnv = core.SessionEnv

type Action = core.Action

func GateLogNewerSchema() (int, bool) { return core.GateLogNewerSchema() }

func GateLogPath() string { return core.GateLogPath() }

func ReadEvents(p0 string) []Event { return core.ReadEvents(p0) }

func parseGateLine(p0 string) (gateEntry, bool) { return core.ParseGateLine(p0) }

func readFileShared(p0 string) ([]byte, error) { return core.ReadFileShared(p0) }
