// Code generated by tddsplit. DO NOT EDIT.

package postedit

import (
	mutation "github.com/aphrollo/aphrollo-tools/internal/tdd/mutation"
)

const GCKindTempLitter = mutation.GCKindTempLitter

type GCCandidate = mutation.GCCandidate

func dropCargoNameFilter(p0 Runner) (Runner, bool) { return mutation.DropCargoNameFilter(p0) }

func goRanNoTests(p0 Runner, p1 SuiteResult) bool { return mutation.GoRanNoTests(p0, p1) }

func goSelectedDirs(p0 Runner) ([]string, bool) { return mutation.GoSelectedDirs(p0) }

func widenCargoRunner(p0 Runner) (Runner, bool) { return mutation.WidenCargoRunner(p0) }
