// Code generated by tddsplit. DO NOT EDIT.

package postedit

import (
	run "github.com/aphrollo/aphrollo-tools/internal/run"
	lock "github.com/aphrollo/aphrollo-tools/internal/tdd/lock"
	time "time"
)

const BuildLockHeldEnv = lock.BuildLockHeldEnv

const SlotHeld = lock.SlotHeld

const SlotSuperseded = lock.SlotSuperseded

type BuildLockOwner = lock.BuildLockOwner

type BuildSlot = lock.BuildSlot

type CapResult = lock.CapResult

type SlotWait = lock.SlotWait

func ReadBuildSlotOwner(p0 string) (BuildLockOwner, bool) { return lock.ReadBuildSlotOwner(p0) }

func RunSlotSpec(p0 run.Spec, p1 string) (CapResult, error) { return lock.RunSlotSpec(p0, p1) }

func TryAcquireLintLock(p0 string, p1 string) (func(), bool) { return lock.TryAcquireLintLock(p0, p1) }

func WaitForHeadroom(p0 string, p1 time.Duration) string { return lock.WaitForHeadroom(p0, p1) }

func acquireGlobalSlot(p0 time.Duration, p1 string, p2 string) (BuildSlot, func(), bool) {
	return lock.AcquireGlobalSlot(p0, p1, p2)
}

func acquireQueuedBuildSlot(p0 string, p1 time.Duration, p2 string, p3 string) (BuildSlot, func(), SlotWait) {
	return lock.AcquireQueuedBuildSlot(p0, p1, p2, p3)
}

func buildSlotHolderDescription(p0 string) string { return lock.BuildSlotHolderDescription(p0) }

func globalCapacityHolderDescription() string { return lock.GlobalCapacityHolderDescription() }

func isSettledVerdict(p0 string) bool { return lock.IsSettledVerdict(p0) }

func postEditLockWait() time.Duration { return lock.PostEditLockWait() }

func runnerTargetDir(p0 Runner, p1 string) string { return lock.RunnerTargetDir(p0, p1) }

func setBuildJobs(p0 int) func() { return lock.SetBuildJobs(p0) }
