// Code generated by tddsplit. DO NOT EDIT.

package postedit

import (
	mutation "github.com/aphrollo/aphrollo-tools/internal/tdd/mutation"
)

const GCKindTempLitter = mutation.GCKindTempLitter

type CoverQuery = mutation.CoverQuery

type FuncDiff = mutation.FuncDiff

type GCCandidate = mutation.GCCandidate

type MutantsConfig = mutation.MutantsConfig

func CoveringTests(p0 string, p1 string, p2 []string) CoverQuery {
	return mutation.CoveringTests(p0, p1, p2)
}

func DiffFuncs(p0 []byte, p1 []byte, p2 bool) FuncDiff { return mutation.DiffFuncs(p0, p1, p2) }

func ReadMutantsConfig(p0 string) (MutantsConfig, error) { return mutation.ReadMutantsConfig(p0) }

func dropCargoNameFilter(p0 Runner) (Runner, bool) { return mutation.DropCargoNameFilter(p0) }

func goRanNoTests(p0 Runner, p1 SuiteResult) bool { return mutation.GoRanNoTests(p0, p1) }

func goSelectedDirs(p0 Runner) ([]string, bool) { return mutation.GoSelectedDirs(p0) }

func widenCargoRunner(p0 Runner) (Runner, bool) { return mutation.WidenCargoRunner(p0) }
