// Code generated by tddsplit. DO NOT EDIT.

package postedit

import (
	failfirst "github.com/aphrollo/aphrollo-tools/internal/tdd/failfirst"
)

const editProduction = failfirst.EditProduction

const editTestOnly = failfirst.EditTestOnly

const editUnknown = failfirst.EditUnknown

func ExtractPassingTests(p0 string) []string { return failfirst.ExtractPassingTests(p0) }
