// Code generated by tddsplit. DO NOT EDIT.

package postedit

import (
	gitx "github.com/aphrollo/aphrollo-tools/internal/tdd/gitx"
)

func cleanGitEnv() []string { return gitx.CleanGitEnv() }

func git(p0 string, p1 ...string) (string, error) { return gitx.Git(p0, p1...) }
