// Code generated by tddsplit. DO NOT EDIT.

package postedit

import (
	shell "github.com/aphrollo/aphrollo-tools/internal/tdd/shell"
)

func baseCommand(p0 string) string { return shell.BaseCommand(p0) }

func bashWriteTargets(p0 string, p1 string) []string { return shell.BashWriteTargets(p0, p1) }

func cdTarget(p0 []string) (string, bool) { return shell.CdTarget(p0) }

func resolveAgainst(p0 string, p1 string) string { return shell.ResolveAgainst(p0, p1) }

func shellSegments(p0 string) [][]string { return shell.ShellSegments(p0) }

func stripHeredocBodies(p0 string) string { return shell.StripHeredocBodies(p0) }
