// Code generated by tddsplit. DO NOT EDIT.

package postedit

import (
	syscall "syscall"
	time "time"
)

const DeferredJobMaxAge = deferredJobMaxAge

const DeferredMaxEnv = deferredMaxEnv

const MaxBashSnapshots = maxBashSnapshots

const PrimaryBranch = primaryBranch

type DeferredEditOutcome = deferredEditOutcome

func BuildLockHolderNote(p0 string) string { return buildLockHolderNote(p0) }

func BuildingLine(p0 string, p1 string, p2 time.Duration) string { return buildingLine(p0, p1, p2) }

func ClearDeferredJob(p0 string, p1 string) { clearDeferredJob(p0, p1) }

func DeferredDirPath() string { return deferredDirPath() }

func DeferredExpired(p0 DeferredJob, p1 time.Time) bool { return deferredExpired(p0, p1) }

func DeferredJobPath(p0 string, p1 string) string { return deferredJobPath(p0, p1) }

func DeferredResult(p0 DeferredJob) (PhaseOutcome, bool) { return deferredResult(p0) }

func DenyNarrowedRerunReason(p0 string, p1 gateEntry) string { return denyNarrowedRerunReason(p0, p1) }

func DetachedAttrs() *syscall.SysProcAttr { return detachedAttrs() }

func EditResultAdvisory(p0 DeferredJob, p1 PhaseOutcome, p2 string, p3 *sessionState, p4 string, p5 string) string {
	return editResultAdvisory(p0, p1, p2, p3, p4, p5)
}

func FileContentHash(p0 string) string { return fileContentHash(p0) }

func FinishedEditOutcome(p0 DeferredJob, p1 PhaseOutcome) deferredEditOutcome {
	return finishedEditOutcome(p0, p1)
}

func GcDeferredJobFiles(p0 string, p1 time.Duration, p2 time.Time) []GCCandidate {
	return gcDeferredJobFiles(p0, p1, p2)
}

func GreenLabel(p0 Outcome, p1 string, p2 time.Duration) string { return greenLabel(p0, p1, p2) }

func KillLivePID(p0 string) { killLivePID(p0) }

func LoadDeferredJob(p0 string, p1 string) (DeferredJob, bool) { return loadDeferredJob(p0, p1) }

func PidStillOurs(p0 DeferredJob) bool { return pidStillOurs(p0) }

func PromptHarvest(p0 string) string { return promptHarvest(p0) }

func ReapSessionDeferredJobs(p0 string) int { return reapSessionDeferredJobs(p0) }

func ResetDeferredSweepForTest() { resetDeferredSweepForTest() }

func SaveDeferredJob(p0 DeferredJob) { saveDeferredJob(p0) }

func SetPrimaryEdits(p0 string, p1 bool) error { return setPrimaryEdits(p0, p1) }

func SourceIdentity(p0 string, p1 string) string { return sourceIdentity(p0, p1) }

func SweepDeferredJobs(p0 time.Time) int { return sweepDeferredJobs(p0) }

func TailSnippet(p0 string) string { return tailSnippet(p0) }

func TreatAsEmptyPass(p0 SuiteResult) bool { return treatAsEmptyPass(p0) }

func WaiverAllowedMessage(p0 string) string { return waiverAllowedMessage(p0) }

func WaiverRevokedMessage(p0 string) string { return waiverRevokedMessage(p0) }

func WritePhaseResult(p0 string, p1 PhaseOutcome) { writePhaseResult(p0, p1) }
