package postedit

import (
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/aphrollo/aphrollo-tools/internal/tdd/internal/tddtest"
)

func TestIsGeneratedFile_ReadsTheCodeGeneratedMarker(t *testing.T) {
	root := t.TempDir()
	write(t, root, "gen.go", "// Code generated by sqlc. DO NOT EDIT.\n\npackage x\n")
	write(t, root, "plain.go", "package x\n\n// A comment that says Code generated by hand does not count\n")
	write(t, root, "py.py", "# Code generated by protoc. DO NOT EDIT.\nx = 1\n")
	write(t, root, "late.go", "package x\n"+strings.Repeat("// padding line\n", 200)+"// Code generated by sqlc. DO NOT EDIT.\n")

	cases := map[string]bool{"gen.go": true, "plain.go": false, "py.py": true, "late.go": false, "missing.go": false}
	for name, want := range cases {
		if got := isGeneratedFile(filepath.Join(root, name)); got != want {
			t.Errorf("isGeneratedFile(%s) = %v, want %v", name, got, want)
		}
	}
}

// A regen rewrites generated packages that have no tests of their own. The
// narrowed run selects nothing, and the ladder used to climb to every importer
// as one deferred job whose verdict was stale when it landed (issue #1189).
func TestWidenDeferredSelection_AGeneratedFileIsNotWidenedToItsImporters(t *testing.T) {
	t.Setenv("CLAUDE_CONFIG_DIR", t.TempDir())
	root := t.TempDir()
	write(t, root, "go.mod", "module m\n\ngo 1.22\n")
	write(t, root, "gen/gen.go", "// Code generated by sqlc. DO NOT EDIT.\n\npackage gen\n")
	write(t, root, "user/user.go", "package user\n\nimport _ \"m/gen\"\n")
	write(t, root, "user/user_test.go", "package user\n\nimport \"testing\"\n\nfunc TestUser(t *testing.T) {}\n")
	started := liveSpawner(t)
	narrow := Runner{Cmd: "go", Args: []string{"test", "./gen"}}
	file := filepath.Join(root, "gen", "gen.go")

	w := widenDeferredSelection(narrow, root, file, "", "h", "s-1189", "", time.Now().Add(time.Minute), SuiteResult{})

	if *started != 0 {
		t.Fatalf("runs started = %d, want none: the importers of generated code are not run for it", *started)
	}
	line := tddtest.Pathless(t, w.terminal)
	for _, want := range []string{"go test ./gen", "NO-TESTS-SELECTED", "gen/gen.go is generated code", "regen check", "NOT tested"} {
		if !strings.Contains(strings.ToUpper(line), strings.ToUpper(want)) {
			t.Errorf("line %q does not carry %q", line, want)
		}
	}
}
