package postedit

import (
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/aphrollo/aphrollo-tools/internal/tdd/internal/tddtest"
)

func TestIsGeneratedFile_ReadsTheCodeGeneratedMarker(t *testing.T) {
	root := t.TempDir()
	bom := "\xef\xbb\xbf"
	cases := map[string]string{
		"gen.go":       "// Code generated by sqlc. DO NOT EDIT.\n\npackage x\n",
		"licence.go":   "// Copyright 2026 X.\n\n// Code generated by sqlc. DO NOT EDIT.\n\npackage x\n",
		"bom.go":       bom + "// Code generated by sqlc. DO NOT EDIT.\npackage x\n",
		"crlf.go":      "// Code generated by sqlc. DO NOT EDIT.\r\npackage x\r\n",
		"py.py":        "# Code generated by protoc. DO NOT EDIT.\nx = 1\n",
		"plain.go":     "package x\n\n// A comment that says Code generated by hand does not count\n",
		"nodot.go":     "// Code generated by sqlc. DO NOT EDIT\npackage x\n",
		"after.go":     "package x\n\n// Code generated by sqlc. DO NOT EDIT.\n",
		"inline.go":    "package x // Code generated by sqlc. DO NOT EDIT.\n",
		"rawstring.go": "package x\n\nconst s = `\n// Code generated by sqlc. DO NOT EDIT.\n`\n",
		"indented.go":  "  // Code generated by sqlc. DO NOT EDIT.\npackage x\n",
		"missing.go":   "",
	}
	want := map[string]bool{"gen.go": true, "licence.go": true, "bom.go": true, "crlf.go": true, "py.py": true}
	for name, body := range cases {
		if name != "missing.go" {
			write(t, root, name, body)
		}
		if got := isGeneratedFile(filepath.Join(root, name)); got != want[name] {
			t.Errorf("isGeneratedFile(%s) = %v, want %v", name, got, want[name])
		}
	}
}

// A regen rewrites generated packages that have no tests of their own. The
// narrowed run selects nothing, and the ladder used to climb to every importer
// as one deferred job whose verdict was stale when it landed (issue #1189).
func TestWidenDeferredSelection_AGeneratedFileIsNotWidenedToItsImporters(t *testing.T) {
	t.Setenv("CLAUDE_CONFIG_DIR", t.TempDir())
	root := t.TempDir()
	write(t, root, "go.mod", "module m\n\ngo 1.22\n")
	write(t, root, "gen/gen.go", "// Code generated by sqlc. DO NOT EDIT.\n\npackage gen\n")
	write(t, root, "user/user.go", "package user\n\nimport _ \"m/gen\"\n")
	write(t, root, "user/user_test.go", "package user\n\nimport \"testing\"\n\nfunc TestAUser_Ok(t *testing.T) {}\n")
	started := liveSpawner(t)
	narrow := Runner{Cmd: "go", Args: []string{"test", "./gen"}}
	file := filepath.Join(root, "gen", "gen.go")

	w := widenDeferredSelection(narrow, root, file, "", "h", "s-1189", "", time.Now().Add(time.Minute), SuiteResult{})

	if *started != 0 {
		t.Fatalf("runs started = %d, want none: the importers of generated code are not run for it", *started)
	}
	line := tddtest.Pathless(t, w.terminal)
	for _, want := range []string{"go test ./gen", "NO-TESTS-SELECTED", "gen/gen.go is generated", "regen check", "NOT tested"} {
		if !strings.Contains(strings.ToUpper(line), strings.ToUpper(want)) {
			t.Errorf("line %q does not carry %q", line, want)
		}
	}
}

// A regen that also changes a hand-written file with no tests of its own: the
// run was built for both, and the hand-written one has nothing else to be judged
// by, so the ladder runs for it and no line claims the importers were skipped.
func TestWidenDeferredSelection_AGeneratedFileBesideAHandWrittenOneIsStillWidened(t *testing.T) {
	t.Setenv("CLAUDE_CONFIG_DIR", t.TempDir())
	root := t.TempDir()
	write(t, root, "go.mod", "module m\n\ngo 1.22\n")
	write(t, root, "gen/gen.go", "// Code generated by sqlc. DO NOT EDIT.\n\npackage gen\n")
	write(t, root, "handler/h.go", "package handler\n\nimport _ \"m/gen\"\n")
	write(t, root, "user/user.go", "package user\n\nimport _ \"m/handler\"\n")
	write(t, root, "user/user_test.go", "package user\n\nimport \"testing\"\n\nfunc TestAUser_Ok(t *testing.T) {}\n")
	started := liveSpawner(t)
	narrow := Runner{Cmd: "go", Args: []string{"test", "./gen", "./handler"}}
	gen, handler := filepath.Join(root, "gen", "gen.go"), filepath.Join(root, "handler", "h.go")

	w := widenDeferredSelection(narrow, root, gen, "", "h", "s-1189b", "", time.Now().Add(time.Minute), SuiteResult{}, handler)

	if *started == 0 {
		t.Fatalf("the ladder must run for the hand-written file, got terminal %q", w.terminal)
	}
	if strings.Contains(w.terminal, "generated") {
		t.Errorf("line %q claims the run was skipped as generated", w.terminal)
	}
}

// A restart is the same edit's run again: it must keep the files the write
// changed, or a mixed generated and hand-written write that restarts and
// selects nothing would skip the ladder as if everything were generated.
func TestRestartDeferredEditJob_KeepsTheFilesTheWriteChanged(t *testing.T) {
	t.Setenv("CLAUDE_CONFIG_DIR", t.TempDir())
	root := t.TempDir()
	write(t, root, "gen/gen.go", "// Code generated by sqlc. DO NOT EDIT.\n\npackage gen\n")
	write(t, root, "handler/h.go", "package handler\n")
	gen, handler := filepath.Join(root, "gen", "gen.go"), filepath.Join(root, "handler", "h.go")
	var spawned DeferredJob
	t.Cleanup(SetSpawnPhaseForTest(func(j DeferredJob) (DeferredJob, bool) { spawned = j; return j, true }))
	stale := DeferredJob{Project: root, Phase: "run", Dir: root, Runner: []string{"go", "test", "./gen", "./handler"}, File: gen, Touched: []string{handler}, Session: "s-restart"}

	if !restartDeferredEditJob(stale, "", "h") {
		t.Fatal("setup: the restart did not start")
	}

	if len(spawned.Touched) != 1 || spawned.Touched[0] != handler {
		t.Fatalf("restarted job carries touched %v, want %v", spawned.Touched, []string{handler})
	}
	if allGenerated(runFiles(spawned.File, spawned.Touched)) {
		t.Fatal("a generated file beside a hand-written one must not read as all generated after a restart")
	}
}
