// Code generated by tddsplit. DO NOT EDIT.

package postedit

import (
	tddtest "github.com/aphrollo/aphrollo-tools/internal/tdd/internal/tddtest"
	rapid "pgregory.net/rapid"
	testing "testing"
	time "time"
)

const nextestNoTestsOutput = tddtest.NextestNoTestsOutput

const watchdogSelectTest = `package m

import (
	"strings"
	"testing"
	"time"
)

func TestNarrowToRelatedTests_TerminatesOnAMountCycle(t *testing.T) {
	done := make(chan string, 1)
	go func() {
		done <- strings.Join(narrow(base, "a.rs", root), " ")
	}()
	select {
	case args := <-done:
		if !strings.Contains(args, "-E") {
			t.Fatalf("args = %q, want some module filter rather than none", args)
		}
	case <-time.After(30 * time.Second):
		t.Fatal("a mount cycle never terminated")
	}
}
`

var deferredPhases = tddtest.Phases[DeferredJob, PhaseOutcome]{
	SetSpawn: SetSpawnPhaseForTest,
	Start: func(j DeferredJob, pid int, started time.Time) DeferredJob {
		j.PID = pid
		j.Started = started
		saveDeferredJob(j)
		j, _ = loadDeferredJob(j.Session, j.Project)
		return j
	},
	Files:       func(j DeferredJob) (string, string) { return j.Log, j.Result },
	WriteResult: writePhaseResult,
	Enable:      EnableDeferredPhases,
}

func bashPayload(t *testing.T, session, cwd, command string) []byte {
	t.Helper()
	return tddtest.BashPayload(t, session, cwd, command)
}

func cargoCrate(t *testing.T, pkg string) string { t.Helper(); return tddtest.CargoCrate(t, pkg) }

func editPayload(t *testing.T, tool, path, session string) []byte {
	t.Helper()
	return tddtest.PreEditJSON(t, tool, path, session)
}

func fakePhases(t *testing.T, outcomes ...*PhaseOutcome) *[]DeferredJob {
	t.Helper()
	return tddtest.FakePhases(t, deferredPhases, outcomes...)
}

func firstBytes(s string, n int) string { return tddtest.FirstBytes(s, n) }

func gateLineFields(line string) (stage, verdict string, ok bool) {
	e, ok := parseGateLine(line)
	return e.Stage, e.Verdict, ok
}

func gateLogText(t *testing.T, cfg string) string { t.Helper(); return tddtest.GateLogText(t, cfg) }

func gitDo(t *testing.T, dir string, args ...string) { t.Helper(); tddtest.GitDo(t, dir, args...) }

func gitInit(t *testing.T, dir string) { t.Helper(); tddtest.GitInit(t, dir) }

func makeCargoRepo(t *testing.T) string { t.Helper(); return tddtest.MakeCargoRepo(t) }

func makeGoRepo(t *testing.T) string { t.Helper(); return tddtest.MakeGoRepo(t) }

func mkProject(t *testing.T, markers ...string) string {
	t.Helper()
	return tddtest.MkProject(t, markers...)
}

func mustWrite(t *testing.T, path, content string) { t.Helper(); tddtest.MustWrite(t, path, content) }

func powerShellPayload(t *testing.T, session, cwd, command string) []byte {
	t.Helper()
	return tddtest.PowerShellPayload(t, session, cwd, command)
}

func primaryRepo(t *testing.T) (primary, linked string) { t.Helper(); return tddtest.PrimaryRepo(t) }

func putFakeNextest(t *testing.T) { t.Helper(); tddtest.PutFakeNextest(t) }

func ratchetPayload(t *testing.T, tool, path string, fields map[string]any) []byte {
	t.Helper()
	return tddtest.RatchetPayload(t, tool, path, fields)
}

func requireLoggedVerdict(t *testing.T, cfg, verdict string) {
	t.Helper()
	tddtest.RequireLoggedVerdict(t, cfg, verdict, gateLineFields)
}

func safePathSegment(t *rapid.T, label string) string {
	return rapid.StringMatching(`[a-zA-Z][a-zA-Z0-9_]{0,8}`).Draw(t, label)
}

func stubGoTestReach(t *testing.T, fn func(root, dir string) ([]string, error)) func() {
	t.Helper()
	return SetGoTestReachForTest(fn)
}

func withIsolatedBuildLock(t *testing.T) {
	t.Helper()
	tddtest.IsolateBuildLock(t, setBuildLockPathOverride, SetPostEditLockWaitForTest, SetPrecommitLockWait)
}

func write(t *testing.T, dir, rel, content string) { t.Helper(); tddtest.Write(t, dir, rel, content) }
